### ISSUE TITLE
Add initial type defintions

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/triggers#10]
## Expected behavior

We should have the structure of the types we want to add for Tekton Triggers clearly defined in this repo and agreed on by all owners:

- `EventListener`
- `TriggerBinding`
- `TriggerTemplate`

Each type should:
- Be defined in `go` such that it can be fed to `update-codegen.sh`
- Be agreed on by all owners
- Be clearly documented in comments (so that it would be fully documented in godoc form)
- Have an example in an `examples` dir (even if we aren't testing this yet, see #11)

## Actual behavior

The structure of the types is basically just in exist in example yaml in [the design doc](https://docs.google.com/document/d/1fngeNn3kGD4P_FTZjAnfERcEajS7zQhSEUaN7BYIlTw/edit#heading=h.iyqzt1brkg3o) which means that:

1. the actual structure and purpose of each field is not clearly defined
2. each person reviewing + authoring may have a different idea of what the field actually is

## Additional info

Design for these types lives in https://docs.google.com/document/d/1fngeNn3kGD4P_FTZjAnfERcEajS7zQhSEUaN7BYIlTw/edit [(visible to members of tekton-dev)](https://github.com/tektoncd/community/blob/master/contact.md#mailing-list)

**Comment by iancoffey** [comment]
Closed prematurely, theres still items to address despite the PR being merged 😅

**Comment by ncskier** [comment]
@iancoffey What work is still left under this issue? Is it the work outlined in [this](https://github.com/tektoncd/triggers/pull/17#issuecomment-510496225) comment?

**Comment by iancoffey** [comment]
@ncskier Yes, I just wanted to make sure I made followup issues if they didnt exist for each of those items (which I have not done yet)

**Comment by ncskier** [comment]
Ok, sounds good! I was just looking over the issues for another one to pick up, and I wasn't positive what was left to do for this one 😁That would be great if you could create new issues documenting the remaining work 👍

**Comment by iancoffey** [comment]
This is long since merged, Im going to close this one.
