### ISSUE TITLE
Cluster interceptor documentation doesn't demonstrate how to invoke existing interceptors in new formation

### ISSUE THREAD

**Issue by jmcshane** [tektoncd/triggers#1023]
Update documentation to reflect cel filter usage as released in #1006 using the ClusterInterceptors with deprecated kinds

**Comment by jmcshane** [comment]
I'm definitely willing to assist in this one to help people migrate, we may want to provide a small migration document as well.

**Comment by jmcshane** [comment]
@dibyom this may be helpful in the 0.13 release

**Comment by dibyom** [comment]
The examples should have been updated. But I'll write up something.
