### ISSUE TITLE
CoreInterceptors Installer controller

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#1027]
### Feature request

The goal is to have an optional component (maybe a Job?) that will wait for the ClusterInterceptor CRD to become established and then create the 4 core interceptors.

### Use case

The main use case is that this will allow users to install Triggers in a single command.

**Comment by sm43** [comment]
@dibyom what if we add this as a part of interceptor server? like before starting the server we can check if the core
interceptors exist, if not create it and then start the server. would that be possible?
if we add a job then we will have to ship an additional image to user.

**Comment by dibyom** [comment]
@sm43 Sorry, I missed your comment -- so I like the idea of adding it as part of the interceptors server. One issue with that though is that the Interceptor server would need a cluster role to create the CoreInterceptor CRDs...which might be an ok thing to do if we limit the role to only being able to create the 4 core interceptors using`resourceNames`
