### ISSUE TITLE
Interceptors: Library to make it easier to author interceptors

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#1033]
### Feature request

We should make it easy to do common things for Interceptor authors in Go so that they can just focus on writing business logic (similar to [knative/pkg/webhook](https://github.com/knative/pkg/tree/main/webhook))

Some functionality that this library can have 
* Setting up web server with sensible defaults (users only implement a handler)
* Helper functions to convert errors to InterceptorResponse.Statuses (e.g. https://pkg.go.dev/google.golang.org/grpc/status#FromError)
* (in the future) auto TLS support using something like Knative pkg's [certificates controller](https://github.com/knative/pkg/tree/main/webhook/certificates)
* (in the future) openAPI validation for Interceptor params or config

**Comment by jmcshane** [comment]
I have created an initial implementation of this: https://github.com/jmcshane/interceptor-sdk

Its not exactly in line with the knative webhook package linked above, but it does add a couple necessary pieces:

* Generate ClusterInterceptor CRD
* Provide ko build `config/` directory

I think this may be a starting point to break into two pieces. The first piece is a library that can be referenced for things like the `server.go` and the entrypoint (probably lives in triggers repo directory), but then there's a starter repository for creating new ones (this would be a new repository). Feel free to poke around at the implementation and let me know how/where this may be appropriate to bring into tekton as well as any other feedback.

I do have a fully worked example here, if you follow the README, you should be able to get the custom interceptor deployed into your cluster and referenced via a trigger.
