### ISSUE TITLE
Updated values of TriggerTemplate and TriggerBinding not getting reflected in EventListener

### ISSUE THREAD

**Issue by VeereshAradhya** [tektoncd/triggers#1036]
# Expected Behavior
Updated values of TriggerTemplate and TriggerBinding should get reflected in EventListener

# Actual Behavior
Updated values of TriggerTemplate and TriggerBinding not getting reflected in EventListener

# Steps to Reproduce the Problem

1. Create TriggerTemplate, TriggerBinding, Trigger and EventListener and bind them
2. Change the name of the resource in created TriggerTemplate
3. Trigger an event and observe if there is any change in the resource created by eventListener

cc: @savitaashture 
# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  $ kubectl version
  Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"5797eaecac19b9c0e4d10d3d6b559c074e3c3c88", GitTreeState:"clean", BuildDate:"2021-01-27T07:28:48Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+bafe72f", GitCommit:"bafe72fb05eddc8246040b9945ec242b9f805935", GitTreeState:"clean", BuildDate:"2021-03-14T16:01:39Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

```
$ tkn version
Client version: 0.17.1
Pipeline version: v0.22.0
Triggers version: main
```

**Comment by jmcshane** [comment]
This is the same issue as #1026. I'll have a PR up soon to resolve for the v0.13.0 release

**Comment by jmcshane** [comment]
Thanks for this report @VeereshAradhya. I believe this is a regression in release v0.12.1. You can downgrade to v0.12.0 or take a look at #1037
