### ISSUE TITLE
Could not resolve interceptor URL

### ISSUE THREAD

**Issue by felipecruz91** [tektoncd/triggers#1055]
Hi,

I'm trying to trigger a pipeline from a Bitbucket git push, using this [example](https://github.com/tektoncd/triggers/tree/main/examples/bitbucket) as a reference.

However, I get the following error in the event listener container:

```json
{
   "level":"error",
   "ts":"2021-04-15T11:46:22.786Z",
   "logger":"eventlistener",
   "caller":"sink/sink.go:234",
   "msg":"could not resolve interceptor URL: url resolution failed for interceptor bitbucket with: cluster ││ interceptor.triggers.tekton.dev \"bitbucket\" not found",
   "knative.dev/controller":"eventlistener",
   "/triggers-eventid":"c6662be3-c47f-4d35-ab2d-6dbb6e291cf4",
   "/trigger":"bitbucket-triggers",
   "stacktrace":"gi ││ thub.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:234\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func4\n\tgithub.com/tektoncd/triggers/pk ││ g/sink/sink.go:154"
}
```

By the error msg `cluster.interceptor.triggers.tekton.dev "bitbucket" not found` it seems something is missing.

If I try to find the interceptors installed, there are none:

```bash
$ kubectl get clusterinterceptor.triggers.tekton.dev
No resources found
```

I've previously installed Tekton Triggers with 
```bash
$ kubectl apply --filename https://storage.googleapis.com/tekton-releases/triggers/latest/release.yaml

$ kubectl get pods --namespace tekton-pipelines --watch
NAME                                          READY   STATUS    RESTARTS   AGE
tekton-dashboard-77494c6d96-pcct6             1/1     Running   5          3d2h
tekton-pipelines-controller-6b94f5f96-c46tc   1/1     Running   3          3d2h
tekton-pipelines-webhook-5bfbbd6475-5l89k     1/1     Running   3          3d2h
tekton-triggers-controller-7cbd49fbb8-lct9j   1/1     Running   0          104m
tekton-triggers-webhook-748fb7778c-7wwmg      1/1     Running   0          104m
```

/cc @savitaashture @dibyom

**Comment by rauanmayemir** [comment]
Confirming same issue with `github` interceptor on the latest pipelines `v0.23` and triggers `v0.13`.
I'm using a setup similar to this: https://github.com/tektoncd/triggers/blob/07bc97a568d1efbcb9e2def7966edab4e80dabb3/examples/github/github-eventlistener-interceptor.yaml

**Comment by dibyom** [comment]
What is the output of `kubectl get clusterinterceptors`?

**Comment by rauanmayemir** [comment]
@dibyom Sorry about that, should have read the release notes properly.
@felipecruz91 You need to apply `interceptors.yaml` from the release notes.

**Comment by felipecruz91** [comment]
Thank you.

My impression initially was that installing Tekton Triggers will provide everything I needed (even Interceptors), however, the latest release notes says otherwise.

Shouldn't that be mentioned as part of the main README.md file in the project?

**Comment by dibyom** [comment]
Its mentioned in the section on Installing Triggers: https://github.com/tektoncd/triggers/blob/main/docs/install.md#installing-tekton-triggers-on-your-cluster

**Comment by dibyom** [comment]
I think this is safe to close this now?
/close
