### ISSUE TITLE
ClusterInterceptor docs should explicitly mention using `continue: false` instead of an error

### ISSUE THREAD

**Issue by tualeron** [tektoncd/triggers#1056]
ClusterInterceptor docs should explicitly mention using `continue: false` instead of an error when the interceptor should filter Trigger processing.

_Originally posted by @jmcshane in https://github.com/tektoncd/triggers/pull/1048#discussion_r612895782_

**Comment by jmcshane** [comment]
To add a little more context, the interceptor response object has the ability to specify both a status and a boolean `continue` field. What is an interceptor responding with `continue: false` be expected to provide in terms of status? Is just filtering an issue valid or should all things filtered out provide some context to "why" they are not continuing in the status body.
