### ISSUE TITLE
`template.ParseJSONPath` should have an additional input to tweak the `AllowMissingKey` behavior

### ISSUE THREAD

**Issue by sh-ch** [tektoncd/triggers#1059]
### Feature request

Currently `template.ParseJSONPath` always returns an error if the provided path does not exist in the JSON payload, since `AllowMissingKey` is hard coded to be false. We can add an additional `allowMissingKey bool` to the input to control if the missing key is desired to result in an error or empty string. 

### Use case

With `AllowMissingKey` always set to false, it is hard to distinguish if the error comes from parsing error, missing field error, or something else, when the client really wants an empty string if the path does not exist. One can do conditional check on the error to determine if the error really is missing field, but that is brittle and subject to future changes.

**Comment by dibyom** [comment]
> One can do conditional check on the error to determine if the error really is missing field, but that is brittle and subject to future changes.

If the only use case is better error handling support, we could return specific error types and clients could check on those types instead of on a string. 

But if there are other use cases for not returning an error on `allowMissingKey`, then I'm happy to add in the param.
