### ISSUE TITLE
Getting Connection Refused for EventListener

### ISSUE THREAD

**Issue by johnlongo** [tektoncd/triggers#1062]
HI,
Getting Connection Refused (see attached) for EventListener that I created (see below).
Is there anyway to set an initial delay on the live probes when the Event Listener pod is created?
Any advice will be greatly appreciated, thank you in advance.

apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: build-completable-future-app-pipeline-run
  namespace: completable-future-app
spec:
  serviceAccountName: default
  triggers:
    - name: trigger-completable-future-app-pipeline-run
      template:
        ref: build-completable-future-app-pipeline-run

<img width="906" alt="2021-04-20_4-25-01" src="https://user-images.githubusercontent.com/23619505/115363486-842f7f80-a190-11eb-9c1e-e02884f8ce41.png">

**Comment by dibyom** [comment]
Currently, we add the /live endpoint after we have sync'd all the caches: https://github.com/tektoncd/triggers/blob/main/cmd/eventlistenersink/main.go#L139-L144

I suspect this is what is leading to the delays. I think we should start the liveness endpoint earlier in the startup cycle. This might mean that we have to move the liveness probe to its own port.
