### ISSUE TITLE
Eventlistener expose information about cluster

### ISSUE THREAD

**Issue by chmouel** [tektoncd/triggers#1070]
# Expected Behavior

Not showing the namespace where the eventlistenner is running

# Actual Behavior

```json
{"eventListener":"openshift-pipelines-ascode-interceptor","namespace":"pipelines","eventID":"773414d6-f8e7-4b4e-a3fb-f99d7758cfa6"}
```

# Additional Info

It's usually bad security practice to expose cluster internal information to the public, since the eventlistenner are usually exposed to the internet for GitHUB or other VCS webhooks it may be better to hide this information.

**Comment by afrittoli** [comment]
Nice catch. The `eventListener` part too might be considered sensitive, as it implies the service name. 
We could perhaps make that information available as opt-in via the service configuration?

**Comment by dibyom** [comment]
> It's usually bad security practice to expose cluster internal information to the public, since the eventlistenner are usually exposed to the internet for GitHUB or other VCS webhooks it may be better to hide this information.

Agreed. Is there a particular issue that exposing the namespace/el name exposes us to? 
The trade-off here is around ease of debugging. Having the EL name and the namespace along with the eventID gives one all the required information to look up the logs for a particular event for debugging. Without those two, the user would have to manually figure out which event listener/namespace the webhook is connected.
