### ISSUE TITLE
Cache secret fetches in interceptors

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#1084]
### Feature request

Currently, we make calls to the API server directly in the interceptors for fetching secrets for secret validation. We should switch to an informer/lister ([like we do in the EventListener](https://github.com/tektoncd/triggers/blob/main/pkg/sink/sink.go#L59-L65)) so that we cache the responses.

### Use case

1. Prevent interceptor calls to the API server from being throttled e.g.
```
I0506 20:29:25.612641       1 request.go:645] Throttling request took 1.090343987s, request: GET:https://10.2.0.1:443/api/v1/namespaces/cicd/secrets/provisioning-steps-webhook-secret
```

**Comment by ljupchokotev** [comment]
Looking at [this code](https://github.com/tektoncd/triggers/blob/main/pkg/interceptors/github/github.go#L84), an improvement would be to check the event type before trying to load the secret. This way, a single event will not read the webhook secret for all GitHub interceptors, but only for the ones where the event type matches.

**Comment by dibyom** [comment]
@ljupchokotev Agreed. That would be a good change too :)
