### ISSUE TITLE
GitLab Interceptor - Filter on specific types of Merge Request webhook

### ISSUE THREAD

**Issue by GJKrupa** [tektoncd/triggers#1092]
### Feature request

GitLab webhook events for merge requests can be generated on a number of conditions that may not require a new build (e.g. description change, MR merged or closed, labels added). Can the interceptor be updated to allow filtering of changes based on user needs? This could be as simple as filtering on the keys in the "changes" object in the JSON payload and by comparing the current and previous values of changes.createdAt.

### Use case

I want to compile and test a project when a merge requests is created or a new commit is made to an existing merge request but I do not want to re-build the MR when its description is changed or a new label is applied.

**Comment by dibyom** [comment]
While this isn't possible via the Gitlab Interceptor, you should be able to use the CEL interceptor to craft a filter that does what you want.

**Comment by GJKrupa** [comment]
Perfect. After some trial and error I've managed to get a pipeline to trigger on all of the right conditions using the CEL interceptor. Thanks, @dibyom .

**Comment by lioramilbaum** [comment]
@GJKrupa Can you please share the code snippet? That could be very useful for me. BTW, were you able to add a label to the PipelineRun with the merge request id?
