### ISSUE TITLE
Add automated coverage for examples

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/triggers#11]
## Expected behavior

Any examples we add to the repo should have at least a base level of testing applied to them with each PR, e.g. making sure the structure is sound (even if we don't verify the behavior).

## Actual behavior

In #10 we'll be adding types and examples, but we don't yet have any tests for them.

## Additional info

* In the pipelines repo, these "tests" are called "yaml tests" and are verified with https://github.com/tektoncd/pipeline/blob/master/test/e2e-tests-yaml.sh
* In https://github.com/tektoncd/triggers/issues/6 we'll add an initial skeleton of end to end test automation, we might want to hook in yaml tests there b/c those tests also require a running cluster

**Comment by vtereso** [comment]
I haven't found any good tooling to help automate the process for when the examples are updated (to avoid copy pasting into the markdown doc files). It would be advantageous to retain the formatting that we get by GitHub's native code fencing so I will make some utilities that will update/check the files for this purpose. In addition to asserting the examples in an e2e test.

**Comment by ncskier** [comment]
If I'm not mistaken, it looks like this issue is complete. Can we close it? @vtereso
