### ISSUE TITLE
Webhook yaml shouldn't utilise microclimate-utils image

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/triggers#110]
# Expected Behavior
We should find an image (ideally built from open-source, Microclimate isn't and I used to work on it!) that we can use instead, ideally one that's maintained for us so won't have CVEs/need to be refreshed etc

# Actual Behavior
It does 😢 

# Steps to Reproduce the Problem

1. Have a look at https://github.com/tektoncd/triggers/blob/master/docs/create-webhook.yaml#L55

@akihikokuroda added this as we couldn't find an image that lets us have both kubectl, curl, and openssl in, that we can run as non-root

**Comment by akihikokuroda** [comment]
https://github.com/tektoncd/triggers/pull/99 include the changes.

**Comment by a-roberts** [comment]
Thanks all, closing 😄
