### ISSUE TITLE
Implement EventListener response codes (e.g. bad request on empty)

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/triggers#111]
# Expected Behavior
If I curl my event listener with no data, I should get back an error that I've sent it a bad request - and be told what the format should be. Noticed this when working https://github.com/tektoncd/triggers/issues/109 (figuring out what data I should be sending and for fun, sending nothing to see what I'd get back)

# Actual Behavior
I get an empty response and a return code 200

# Steps to Reproduce the Problem

1. Apply example resources from this repository
2. `kubectl port-forward *listener pod name* 8082`
3. curl -X POST http://localhost:8082
4. Observe you get a 200 back with no data

In Postman:
![image](https://user-images.githubusercontent.com/12814972/64776930-0ab1c300-d551-11e9-9f86-f4dd737a7101.png)

# Additional Info
Fix to go in https://github.com/tektoncd/triggers/blob/2f2c62517fdc45a1c0bed3882a8d27d9a8cceec1/pkg/sink/sink.go#L43 I expect

**Comment by akihikokuroda** [comment]
PR: https://github.com/tektoncd/triggers/pull/198

**Comment by ncskier** [comment]
Thanks @akihikokuroda 👍 The PR was merged, so I'm going to close this issue.
