### ISSUE TITLE
Package Roles for EventListener SA's with Triggers Releases

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#1119]
### Feature request

The RBAC roles needed by an EventListener ServiceAccount is currently documented in the [examples/rbac.yaml ](https://github.com/tektoncd/triggers/blob/main/examples/rbac.yaml) file.

Everytime we change the RBAC roles, we update the file. But since the roles are not part of the packaged release, we have to update the release notes and users have to manually update the roles themselves.

We should ship the roles as part of the Triggers Release yaml. Then users only need a single RoleBinding per namespace to use the Role.

**Comment by dibyom** [comment]
Specifically what I'm thinking is:

1. One ClusterRole (tekton-triggers-eventlistener) that contains all Roles

2. The example is updated to use a standard RoleBinding for the default namespace that uses the above ClusterRole.

**Comment by sm43** [comment]
@dibyom do we want to merge [`tekton-triggers-example-minimal`](https://github.com/tektoncd/triggers/blob/042a8dd502aaf8ec8946fb6e8fa349d9cf8f43f4/examples/rbac.yaml#L6) and [`tekton-triggers-example-clusterrole`](https://github.com/tektoncd/triggers/blob/042a8dd502aaf8ec8946fb6e8fa349d9cf8f43f4/examples/rbac.yaml#L43) both the roles to together or keep separate?
for `tekton-triggers-example-minimal` we can have a rolebinding in default ns for examples but for `tekton-triggers-example-clusterrole` we will need a clusterrolebinding as it has clusterscope resources listed.
if we merge both and create one clusterrolebinding then serviceaccount would have extra permissions in other namespaces 😄
wdyt? how do we wanna proceed?

**Comment by dibyom** [comment]
Discussed at WG - we can try having two ClusterRoles - one for roles that need a RoleBinding, and one for the ones that need a ClusterRoleBinding

**Comment by sm43** [comment]
done in #1158 
/close
