### ISSUE TITLE
Add logging for handling events 

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/triggers#112]
# Expected Behavior
We should provide useful logging in https://github.com/tektoncd/triggers/blob/master/pkg/sink/sink.go#L43 (in my case I had a PipelineRun and PipelineResources created, it just wasn't immediately obvious to me - and tailing the listener logs didn't give me any clues

# Actual Behavior
I expect to see, for example: created PipelineRun named x with PipelineResources (a, b, c)

# Steps to Reproduce the Problem

1. Create an event listener and successfully create a PipelineRun and PipelineResources using the example code for this repository (I'm planning to add some docs to make this easy)

# Additional info
This would be an awesome first issue

**Comment by akihikokuroda** [comment]
I added log entry for each resource generation.  If it fails, the error log entry follows the log entry.
```
2019/10/30 19:38:11 Generating resource: kind: PipelineResource, name: source-repo-jgcpl 
2019/10/30 19:38:11 Generating resource: kind: PipelineResource, name: image-source-jgcpl 
2019/10/30 19:38:11 Generating resource: kind: Task, name: devopsascode-task-jgcpl 
2019/10/30 19:38:11 Generating resource: kind: TaskRun, name: devopsascode-taskrun-1 
2019/10/30 19:38:11 taskruns.tekton.dev "devopsascode-taskrun-1" already exists
```

**Comment by akihikokuroda** [comment]
PR: https://github.com/tektoncd/triggers/pull/197
