### ISSUE TITLE
when replicas is 2, pipeline wile run 2 times.

### ISSUE THREAD

**Issue by 13567436138** [tektoncd/triggers#1128]
# Expected Behavior

# Actual Behavior
simple-pipeline-run-lrltc-say-bye-4rt8s-pod-nkbtq       0/2     Pending            0          1s
simple-pipeline-run-lrltc-say-bye-4rt8s-pod-nkbtq       0/2     Pending            0          1s
simple-pipeline-run-lrltc-say-bye-4rt8s-pod-nkbtq       0/2     Init:0/1           0          2s
simple-pipeline-run-2crzx-say-bye-srlkj-pod-wbfx8       0/2     Completed          0          43s
simple-pipeline-run-lrltc-say-bye-4rt8s-pod-nkbtq       0/2     PodInitializing    0          7s
simple-pipeline-run-lrltc-say-bye-4rt8s-pod-nkbtq       2/2     Running            0          20s
simple-pipeline-run-lrltc-say-bye-4rt8s-pod-nkbtq       2/2     Running            0          20s
simple-pipeline-run-lrltc-say-bye-4rt8s-pod-nkbtq       1/2     NotReady           0          33s
simple-pipeline-run-lrltc-say-bye-4rt8s-pod-nkbtq       0/2     Completed          0          34s
# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

**Comment by dibyom** [comment]
Interesting...are you sure the request made it to a single replica or both replicas?
