### ISSUE TITLE
No more arm32v7 images available after v0.12.1

### ISSUE THREAD

**Issue by grunlab** [tektoncd/triggers#1136]
Until release v0.12.1, arm32v7 images were available.
See manifests here: https://console.cloud.google.com/gcr/images/tekton-releases/GLOBAL/github.com/tektoncd/triggers/cmd/controller@sha256:96a63ec6d0cc0871d7dfea9d831b6da20df474bbdcbd01caf62f488e2d682db4/details?tab=info
Available platform architectures were: amd64, arm, arm64, ppc64le, s390x

Starting from v0.13.0, no more arm32v7 images were available.
See manifests here: https://console.cloud.google.com/gcr/images/tekton-releases/GLOBAL/github.com/tektoncd/triggers/cmd/controller@sha256:58baa0aa0eaca368b8090bcb6e88024847d14df2952cdfe7f22be6132a7732c9/details?tab=info
Available platform architectures were: amd64, arm64, ppc64le, s390x

So arm32v7 users are currently blocked in v0.12.1, not possibility to upgrade to next releases.

**Comment by dibyom** [comment]
This seems related to https://github.com/tektoncd/pipeline/issues/4059 and https://github.com/tektoncd/pipeline/pull/3717.

I think when we updated the release pipeline, we used the same platforms that pipelines was built for. It should be easy enough to add `linux/arm` to the list of [platforms](https://github.com/tektoncd/triggers/blob/main/tekton/publish.yaml#L31)

However I don't think there is much of a use case for releasing triggers for linux/arm without also doing the same for pipelines :)
Also, the only supported architecture is x86, others are on a best effort basis

/cc @vdemeester @nikhil-thomas

**Comment by bobcatfish** [comment]
@imjasonh recently brought back building arm v7 images for Pipelines (https://github.com/tektoncd/pipeline/pull/4331) given that precent maybe we can bring it back here as well?

**Comment by lbernick** [comment]
Pipelines now supports arm, we should prioritize fixing this in triggers especially because the fix should be relatively simple.

/assign dibyom
/remove-label help wanted
