### ISSUE TITLE
EventListener fuzzy matching is used to termine the target of an incoming event

### ISSUE THREAD

**Issue by DJW-00000** [tektoncd/triggers#1146]
In Tekton triggers version `v0.10.2` `EventListeners` will use fuzzy matching to determine the target of an incoming event.

An event is routed if the name of the event is prefixed with the name of the `EventListener`.

This means that if you have a dangerous pipeline `my-dangerous-pipeline` it will respond to multiple names such as:
- `my-dangerous-pipeline`
- `my-dangerous-pipeline-dry-run`
- `my-dangerous-pipeline-foo`
- `my-dangerous-pipeline-bar`

In our eyes this behavior should be replaced with literal string matching. Incoming events without exact name match should be discarded, logged and return HTTP Status Code `404`. 

At least, there should be some documentation explaining how names are matched in the docs below.

https://github.com/tektoncd/triggers/blob/main/docs/eventlisteners.md#specifying-triggers

# Steps to Reproduce the Problem

1. Make an EventListener called `my-dangerous-pipeline`
2.Perform a POST on /my-dangerous-pipeline-foo-bar-baz
3.HTTP Status Code 201 is returned and the pipeline is executed

# Additional Info

- Kubernetes version:

```
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.17-eks-c5067d", GitCommit:"c5067dd1eb324e934de1f5bd4c593b3cddc19d88", GitTreeState:"clean", BuildDate:"2021-03-05T23:39:01Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
Pipeline version: v0.18.0
Triggers version: v0.10.2
Dashboard version: v0.12.0
```

**Comment by khrm** [comment]
Hi,
I didn't get this. How are we doing fuzzy matching? At present, EventListener sink receives an event at route / and process all Triggers or Triggers Ref.

**Comment by lbernick** [comment]
Triggers doesn't do fuzzy matching currently, but the docs could use an update to better explain how trigger processing works.

/remove-lifecycle rotten
