### ISSUE TITLE
Trying to apply the following listner to okd 4.7

### ISSUE THREAD

**Issue by johnlongo** [tektoncd/triggers#1149]
Trying to apply the following listner to okd 4.7, can anyone tell me what's wrong with my definition?
I also attached the yaml file to.

apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: build-completable-future-app-pipeline-run
  namespace: completable-future-app
spec:
  serviceAccountName: default
  triggers:
    - name: trigger-completable-future-app-pipeline-run
      template:
        ref: build-completable-future-app-pipeline-run

Error from server (BadRequest): error when creating "trigger-completable-future-app-listener.yaml": admission webhook "webhook.triggers.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "name"

[trigger-completable-future-app-listener.txt](https://github.com/tektoncd/triggers/files/6796884/trigger-completable-future-app-listener.txt)

**Comment by dibyom** [comment]
Switching from `name` to `ref` should help
