### ISSUE TITLE
0.12: PR #969 breaks custom interceptors that convert non-json to JSON

### ISSUE THREAD

**Issue by bitsofinfo** [tektoncd/triggers#1152]
# Expected Behavior

in triggers < v0.12, my interceptor that convert non-JSON bodies to JSON, work fine. For example I have Slack POSTing a body to my event listener endpoint where BODY = `payload=[urlencodedvalue]`

My interceptor converts the url encoded payload value into JSON and returns it back to the caller (event listener) then the rest of the interceptor continues and things move forward

https://github.com/bitsofinfo/cicdstatemgr/blob/master/examples/tekton/pipelines/triggers.event-listener.yaml#L404 & https://github.com/bitsofinfo/slack-payload-handler

In > 0.12, the interceptors are no longer called, instead the event listener immediately fails fast on these POSTs with:

```
{"level":"error","ts":"2021-07-14T17:13:04.159Z","logger":"eventlistener","caller":"sink/validate_payload.go:39","msg":"Invalid event body format format: invalid character 'p' looking for beginning of value","knative.dev/controller":"eventlistener","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.IsValidPayload.func1\n\tgithub.com/tektoncd/triggers/pkg/sink/validate_payload.go:39\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2069\ngithub.com/tektoncd/triggers/pkg/sink.(*Sink).NewMetricsRecorderInterceptor.func1\n\tgithub.com/tektoncd/triggers/pkg/sink/metrics.go:81\ngithub.com/tektoncd/triggers/pkg/sink.(*MetricsHandler).Intercept.func1\n\tgithub.com/tektoncd/triggers/pkg/sink/metrics.go:153\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2069\nnet/http.(*ServeMux).ServeHTTP\n\tnet/http/server.go:2448\nnet/http.(*timeoutHandler).ServeHTTP.func1\n\tnet/http/server.go:3316"}
```

# Actual Behavior

See above:

# Steps to Reproduce the Problem

https://github.com/bitsofinfo/cicdstatemgr/tree/master/examples/tekton

Change: https://github.com/bitsofinfo/cicdstatemgr/blob/master/examples/tekton/core/install.sh#L36 to v12+ prior to going through the example.

# Additional Info

- Tekton Pipeline version: v0.20.1

see #969 

@boarder981

**Comment by dibyom** [comment]
/cc @khrm 

Is the issue here that non JSON payload is being sent to the EventListener? The EventListener was always designed to support only JSON payloads...it's just that we were not actually enforcing that via early validation until recently.

**Comment by bitsofinfo** [comment]
Yes, for example, we use Slack to provide end user interactivity w/ tekton and slack buttons, which are interactive controls. Slack posts non-json payloads, which we leverage a custom webhook interceptor in the even listener to convert what slack sends to json. This seems like a completely reasonable use case that we've been using in production fine, but after moving to 0.12 it no longer works. Seems like the validation of JSON should only occur after interceptors have the chance to manipulate the payloads.

**Comment by dibyom** [comment]
> Seems like the validation of JSON should only occur after interceptors have the chance to manipulate the payloads.

That's definitely one option. On the other hand we have had reports of users not detecting misconfigured non JSON webhooks with the previous behavior. All built in interceptors expect JSON payloads and fail when they can't marshal the body to JSON.

Is there no way to configure Slack to send JSON payloads?

**Comment by bitsofinfo** [comment]
Slack sends a POSTs form encoded data where the body = `payload=<url encoded json>`  or some variant of that depending on the interactivity type (buttons, vs slash commands etc)

https://api.slack.com/interactivity/handling#payloads
https://api.slack.com/interactivity/slash-commands#app_command_handling

there are others who've demonstrated uses of webhooks to do this conversion as well
https://bigkevmcd.github.io/tekton/triggers/slack/commands/2020/03/02/slack-slash-tekton.html
https://github.com/bigkevmcd/slack-webhook-interceptor

The Event Listener should be open as this limits integration. At least skip the forced JSON expectation on the 1st interceptor or permit a configurable option to toggle this, we absolutely need a way to handle this and have numerous tekton deployments using this non-json to JSON conversion method.

**Comment by dibyom** [comment]
Thanks for the details @bitsofinfo The Slack API that sends the JSON payload as a field within the body is ....interesting.

@khrm This is simple to implement but I wanted to check on the original motivation for #969 . Is it ok to make that optional (default would be that we validate for JSON, but we can relax that requirement using a flag of some sort?)

**Comment by boarder981** [comment]
I'm also leveraging Slack and ran into this issue when upgrading to Triggers v0.12.  A way to toggle JSON validation on/off would be great.

**Comment by khrm** [comment]
@dibyom A way to toggle validation would be the way forward. I would look into this.

**Comment by bitsofinfo** [comment]
@khrm any update on this?

**Comment by sm43** [comment]
/assign 
based on discussion in WG, waiting for #1110 to get merged then I will create a pr to enable/disable json validation through `feature-flags` configmap.

**Comment by sm43** [comment]
#1189  adds a feature to disable payload validation.
Previously, we discussed it to add as a feature flag but that would mean all eventlistener will have payload validation disabled.

so instead of that to start with the pr add support for an annotation.

User can add an annotation `tekton.dev/disable-payload-validation: "true"` on an eventlistener and this will disable payload validation for that eventlistener only.
