### ISSUE TITLE
PodSecurityPolicy deprecated in Kubernetes 1.21

### ISSUE THREAD

**Issue by pietervincken** [tektoncd/triggers#1159]
# Expected Behavior
The released deployment manifest doesn't have deprecated resources listed in it.

# Actual Behavior
PodSecurityPolicy tekton-triggers is listed in the deployment manifest which is a deprecated resource as of 1.21.

# Steps to Reproduce the Problem

1. Download the latest release yaml (tested with 0.15.0)

# Additional Info

- Kubernetes version: 1.21

  **Output of `kubectl version`:**
N/A

- Tekton Triggers version:

0.15.0

**Comment by dibyom** [comment]
Related to https://github.com/tektoncd/pipeline/issues/4112
In particular, we should track when Pipelines removes its PSP and also then also remove the Triggers PSP: https://github.com/tektoncd/pipeline/pull/4122

**Comment by dibyom** [comment]
Waiting on pipelines to update with the PSP replacement before adding it to triggers.
