### ISSUE TITLE
Create a working validate example

### ISSUE THREAD

**Issue by ncskier** [tektoncd/triggers#117]
# Expected Behavior
Now that https://github.com/tektoncd/triggers/pull/89 has been merged, Triggers has the capability to validate http POST events. For someone learning about Triggers, I expect there to be example YAML files that I can apply to create a working example of this validation.

# Actual Behavior
There is nothing in the `examples/` directory that creates an EventListener with working validation.

# Additional Info
It could be very helpful to have an accompanying README, like the one created in https://github.com/tektoncd/triggers/pull/113.

**Comment by ncskier** [comment]
Thanks for picking this up @khrm! 🙂

**Comment by ncskier** [comment]
@vtereso pointed out that the [validate-event.md](https://github.com/tektoncd/triggers/blob/master/docs/validate-event.md) page has a static example, so under the issue, please update the page to use your new validation example with `<!-- FILE: examples/path/to/new/validate-example.yaml -->` and run `./hack/update-docs.sh`

**Comment by akihikokuroda** [comment]
The validate-github-event.yaml has issue https://github.com/tektoncd/triggers/pull/119
