### ISSUE TITLE
bitbucket tekton eventlistener openshift

### ISSUE THREAD

**Issue by vyom-soft** [tektoncd/triggers#1177]
# Expected Behavior
The eventListener (sink) is should receive the expected payload from bitbucket push.
# Actual Behavior
{"level":"error","ts":"2021-08-06T14:43:14.827Z","logger":"eventlistener","caller":"sink/validate_payload.go:39","msg":"Invalid event
body format format: unexpected end of JSON input","knative.dev/controller":"eventlistener","stacktrace":"github.com/tektoncd/triggers/
pkg/sink.Sink.IsValidPayload.func1\n\t/opt/app-root/src/go/src/github.com/tektoncd/triggers/pkg/sink/validate_payload.go:39\nnet/http.
HandlerFunc.ServeHTTP\n\t/usr/lib/golang/src/net/http/server.go:2053\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/lib/golang/src/net/http/s
erver.go:2428\nnet/http.(*timeoutHandler).ServeHTTP.func1\n\t/usr/lib/golang/src/net/http/server.go:3279"}

1. Already a tekton pipeline is created and tested .
2. Would like to invoke the pipeline via Bitbucket push. ( Configured the bitbucket webhook with the route exposed by event listener.
3.  Using openshift tekton pipeline and Eventlistener, tekton template and Tektonbinding are generated. (alpha version is used)

# Additional Info

- Kubernetes version:
1.19
- Tekton Pipeline version:
Client version: 0.15.0
Pipeline version: v0.22.0
Triggers version: v0.12.1

**Comment by khrm** [comment]
Did you select `Application/json` for webhook? From the error log we can see that payload isn't json.

**Comment by dibyom** [comment]
(Will close this out, plz feel free to reopen if @khrm's suggestion did not help)
