### ISSUE TITLE
example bitbucket listener.yaml

### ISSUE THREAD

**Issue by vyom-soft** [tektoncd/triggers#1180]
During creation of the bitbucket-listerner.yaml (alpha)  following error is seen

**Error from server (BadRequest): error when creating "bbucket-eventlistener.yaml": admission webhook "webhook.triggers.te
kton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "params"**

Could you please hint why the unknown field "params" error is coming.

Best Regards
Sanjeev

**Comment by savitaashture** [comment]
Hey @vyom-soft 
Based on the error it shows that you are using old triggers version and latest example
It would be helpful if you provide triggers version so that we can give more details on error.

**Comment by dibyom** [comment]
I'll close out this issue. Feel free to reopen if this persists
/close

**Comment by vyom-soft** [comment]
Hello, 
Here are the information. 
I am using Redhat openshift pipelines 1.41 provided by redhat.
https://github.com/openshift/tektoncd-pipeline
https://github.com/openshift/tektoncd-operator
Components
Tekton Pipelines: v0.22.0
Tekton Triggers: v0.12.1
ClusterTasks based on Tekton Catalog 0.22

**Comment by vyom-soft** [comment]
> Hey @vyom-soft
> Based on the error it shows that you are using old triggers version and latest example
> It would be helpful if you provide triggers version so that we can give more details on error.

Hello @savitaashture 
Here are the information.
I am using Redhat openshift pipelines 1.41 provided by redhat.
https://github.com/openshift/tektoncd-pipeline
https://github.com/openshift/tektoncd-operator
Components
Tekton Pipelines: v0.22.0
Tekton Triggers: v0.12.1
ClusterTasks based on Tekton Catalog 0.22
