### ISSUE TITLE
Add baseline level of user docs

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/triggers#12]
## Expected behavior

It'll be easier to iterate on docs and we'll be in a better position docs-wise in the future if we start with some basic docs now that we can continue to add to.

## Actual behavior

In #2 we'll add the bare minimum required docs that each tekton project needs to have, but those are more for the contributors and maintainers of the project, and less about users of the project.

**Comment by vtereso** [comment]
@iancoffey For the current examples, I had only been asserting them against D4D, which is why people have run into permissions issues etc. Just for the sake of clarity, I think it would be great to include the environments tested in the docs/examples.
