### ISSUE TITLE
Add webhook conversion to triggers

### ISSUE THREAD

**Issue by savitaashture** [tektoncd/triggers#1223]
### Feature request

From 0.15.x release triggers support `v1beta1` API version.
As triggers support both `v1beta1` and `v1alpha1` webhook conversion is required
For more info : https://tektoncd.slack.com/archives/CL3T51NRF/p1630935534009800

### Use case
Conversion webhook is needed to convert things on the “way out” too, so if somebody does a watch or get against a different version of the resource than what is stored by the API server, the conversion webhook will then convert things to the proper shape.

/cc @dibyom @mattmoor @vdemeester @vaikas

**Comment by vaikas** [comment]
Is this something that we should be writing a TEP for? I was going to type down my thoughts on this into a Google doc for discussion, but wasn't quite sure what y'all would prefer as discussion medium? If it's not frowned upon, I'll be doing that and hoping to circulate something early next week.

**Comment by savitaashture** [comment]
+1 on TEP because most of the Tekton feature discussions are done using TEP

**Comment by mattmoor** [comment]
My $0.02 is that a TEP feels heavy for conversion webhooks.  There really aren't a lot of choices to be made or design to surface, it's mostly just executing/implementing what the framework provides.

Pipelines implements this, and I don't think it had a TEP for this? https://github.com/tektoncd/pipeline/blob/2b6c6a0f4edf26142f5bdb769f22ae496f0eb2ac/pkg/apis/pipeline/v1beta1/task_conversion.go#L29

**Comment by savitaashture** [comment]
> My $0.02 is that a TEP feels heavy for conversion webhooks. There really aren't a lot of choices to be made or design to surface, it's mostly just executing/implementing what the framework provides.
> 

Yup this is also valid point i mean if there won't be lot of choices for design and implementation writing TEP is heavy.

With my limited knowledge i see TEP is one place where we go and look for new features design implementation details. 

I may be thinking in narrow way :smile_cat:  so i would leave to @vdemeester @dibyom thoughts

> Pipelines implements this, and I don't think it had a TEP for this? https://github.com/tektoncd/pipeline/blob/2b6c6a0f4edf26142f5bdb769f22ae496f0eb2ac/pkg/apis/pipeline/v1beta1/task_conversion.go#L29

I think TEP idea arrived after this all implementation /cc @vdemeester

**Comment by dibyom** [comment]
Generally, we have TEPs for user facing API changes or large changes where there are a lot of design trade offs. So, that might be a bit of an overkill here. A doc or GH issue should be fine.
