### ISSUE TITLE
Tekton event listener X-Hub-Signature header

### ISSUE THREAD

**Issue by vyom-soft** [tektoncd/triggers#1226]
Hello, 
I am seeing the below error. Could you please see, what could be cause of it.

{"level":"info","ts":"2021-09-15T11:13:08.362Z","logger":"eventlistener","caller":"sink/sink.go:213","msg":"interceptor stopped trigger processing:
 rpc error: code = InvalidArgument desc = no X-Hub-Signature header set","knative.dev/controller":"eventlistener","/triggers-eventid":"c1eb2f5c-946
b-4a7b-ae3b-7d6dd7f43f66","/trigger":"bitbucket-triggers"}

**Environment.**
Red Hat OpenShift Pipelines
1.4.1 provided by Red Hat
OpenShift Tekton Pipeline GitHub Repository
https://github.com/openshift/tektoncd-pipeline
OpenShift Pipelines Operator GitHub Repository
https://github.com/openshift/tektoncd-operator
Components
Tekton Pipelines: v0.22.0
Tekton Triggers: v0.12.1
ClusterTasks based on Tekton Catalog 0.22

**Comment by savitaashture** [comment]
Hey @vyom-soft could you give us the steps which you executed so that it will be easy for us to reproduce and see what went wrong

**Comment by vyom-soft** [comment]
**Binding**:
When I create this resource  https://github.com/tektoncd/triggers/blob/main/examples/v1beta1/bitbucket/triggerbinding.yaml
I see following error:
error: unable to recognize "bb-binding.yaml": no matches for kind "TriggerBinding" in version "triggers.tekton.dev/v1beta1".
_Hence I used the v1alpha1 version for  binding. Which succeded._

**Listener**:
Using this https://github.com/tektoncd/triggers/blob/main/examples/v1beta1/bitbucket/bitbucket-listener.yaml
**throws** : error: unable to recognize "bbucket-eventlistener.yaml": no matches for kind "EventListener" in version "triggers.tekt.dev/v1beta1"
For the same Listener, When I simply replace v1beta1 with v1alpha1
I  see error  **Error** from server (BadRequest): error when creating "bbucket-eventlistener.yaml": admission webhook "webhook.triggers.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "params"
Even I use this https://github.com/tektoncd/triggers/blob/main/examples/v1alpha1/bitbucket/bitbucket-listener.yaml
It throws the same error as above for the **Listener**

Hence I am using this listener which get created successfully.
`apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: bitbucket-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: bitbucket-triggers
      interceptors:
      - bitbucket:
          secretRef:
            secretName: git-vyom-tkn
            secretKey: password
          eventTypes:
          - repo:refs_changed
      bindings:
        - ref: bitbucket-binding
      template:
        ref: trigger-template-vyom-pl-mgr-helm`
 
**Template** This get created successfully.
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template-vyom-pl-mgr-helm
  namespace: e-vyom-mgr
spec:
  params:
    - name: GIT_REPO_REVISION
    - name: GIT_REPO_URL
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        annotations: {}
        generateName: vyom-pl-mgr-helm-
        labels:
          tekton.dev/pipeline: vyom-pl-mgr-helm
        namespace: e-vyom-mgr
      spec:
        params:
          - name: IMAGE_NAME
            value: >-
              image-registry.openshift-image-registry.svc:5000/e-vyom-mgr/vyom-minserver
          - name: APP_PROFILE
            value: springboot
          - name: APP_NAME
            value: vyom-minserver
          - name: GIT_REPO_URL
            value: 'https://bb.vyom.intern/scm/vyom/vyom-minserver.git'
          - name: GIT_REPO_REVISION
            value: develop
        pipelineRef:
          name: vyom-pl-mgr-helm
        resources: []
        status: null
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: vyom-pvc-claim
          - configMap:
              name: settings-mvn
            name: settings-mvn

**Comment by savitaashture** [comment]
> Binding:
When I create this resource https://github.com/tektoncd/triggers/blob/main/examples/v1beta1/bitbucket/triggerbinding.yaml
I see following error:
error: unable to recognize "bb-binding.yaml": no matches for kind "TriggerBinding" in version "triggers.tekton.dev/v1beta1".
Hence I used the v1alpha1 version for binding. Which succeded.

@vyom-soft  this is because you are using old version of trigger which is `v0.12.1` and `v1beta1` is supported from Triggers `0.15.0` version https://github.com/tektoncd/triggers/releases/tag/v0.15.0 and thats the reason you are getting ` no matches for kind "TriggerBinding" in version "triggers.tekton.dev/v1beta1"`

**Comment by savitaashture** [comment]
>For the same Listener, When I simply replace v1beta1 with v1alpha1
I see error Error from server (BadRequest): error when creating "bbucket-eventlistener.yaml": admission webhook "webhook.triggers.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "params"

Again `0.12.1` doesn't support `params`  as its supported from `0.13.0` https://github.com/tektoncd/triggers/releases/tag/v0.13.0

**Comment by savitaashture** [comment]
So i would say if you are using triggers `0.12.1` then use examples from [0.12.1](https://github.com/tektoncd/triggers/tree/v0.12.1)
so that you won't stuck with those kind of issues.

**Comment by savitaashture** [comment]
@vyom-soft once after successful creation did you face below error again 
```
rpc error: code = InvalidArgument desc = no X-Hub-Signature header set","knative.dev/controller":"eventlistener","/triggers-eventid":"c1eb2f5c-946
```

**Comment by vyom-soft** [comment]
> So i would say if you are using triggers `0.12.1` then use examples from [0.12.1](https://github.com/tektoncd/triggers/tree/v0.12.1)
> so that you won't stuck with those kind of issues.

@savitaashture Thank you. I will try again with version 0.12.1. And post the outcome.

**Comment by savitaashture** [comment]
> {"level":"info","ts":"2021-09-16T14:39:41.347Z","logger":"eventlistener","caller":"eventlistenersink/main.go:133","msg":
"Listen and serve on port 8000","knative.dev/controller":"eventlistener"}
{"level":"info","ts":"2021-09-16T14:43:41.052Z","logger":"eventlistener","caller":"sink/sink.go:213","msg":"interceptor
stopped trigger processing: rpc error: code = InvalidArgument desc = no X-Hub-Signature header set","knative.dev/control
ler":"eventlistener","/triggers-eventid":"f6c6dbbd-d8f7-4517-94a0-18becff5a0a3","/trigger":"bitbucket-triggers"}

error is coming from here https://github.com/tektoncd/triggers/blob/main/pkg/interceptors/bitbucket/bitbucket.go#L76

How did you set your webhook ?
