### ISSUE TITLE
Propagate an eventid label to resources created in response to an event 

### ISSUE THREAD

**Issue by dibbles** [tektoncd/triggers#124]
Proposal to add a label to all resources created in response to an event with the same label, for example:

labels:
  triggers-eventid: 12345

this would enable items to lookup other artefacts created in response to the same event.  For example, a github webhook triggers the event listener causing 2 pipelineruns to launch (2 separate trigger templates) and a monitor taskrun to launch (a 3rd triggertemplate).

The monitor task could now use the downwars api to set the eventid as an environment variable it could use to find which pipelineruns it needs to monitor and report on.  This task could then collate the status and report it once.

@ncskier  has a good understanding of the use case here.

**Comment by ncskier** [comment]
Thanks for creating this issue @dibbles! I think that this is an important use case for us to consider where we're orchestrating work across multiple TriggerTemplates.

This `eventUID` sounds very similar to the `$(uid)` interpolation variable we currently have in the [TriggerTemplates](https://github.com/tektoncd/triggers/blob/master/docs/triggertemplates.md). One suggestion I have is to treat the `eventUID` like we do the existing `uid`. I think it could be helpful to give users the option of using `$(eventUID)` as an interpolation variable in their TriggerTemplates for increased flexibility; for example, `$(eventUID)` could be used as a label or as a name postfix to orchestrate work across TriggerTemplates.

Also, we should include clear documentation from this issue about the difference between the existing `uid` and this proposed `eventUID`.

**Comment by akihikokuroda** [comment]
PR: https://github.com/tektoncd/triggers/pull/133
