### ISSUE TITLE
How to configure a webhook secret on CEL Interceptors?

### ISSUE THREAD

**Issue by crdnb** [tektoncd/triggers#1257]
# Expected Behavior
The docs show how we can configure webhook secrets on github and bitbucket interceptors. It would be great to also have an example how to secure cel interceptors.

# Actual Behavior
No docs found.

# Steps to Reproduce the Problem
See the docs: https://tekton.dev/docs/triggers/interceptors/#cel-interceptors

# Additional Info

**Comment by dibyom** [comment]
hi @crdnb This should be possible using the `compareSecret` extension function. See the docs here: https://github.com/tektoncd/triggers/blob/main/docs/cel_expressions.md#list-of-extension-functions
