### ISSUE TITLE
Params without defaults

### ISSUE THREAD

**Issue by vtereso** [tektoncd/triggers#126]
As per discussion on [this PR](https://github.com/tektoncd/triggers/pull/123), perhaps it is more explicit/better separation to _only_ allow for static parameters to be passed from the top level `EventListener`. Should we find sensible, remove the default field within the `TriggerBinding` input parametes and/or the `TriggerTemplate` params.

**Comment by ncskier** [comment]
@vtereso does https://github.com/tektoncd/triggers/pull/127 close this issue? Or is there still more discussion that you want to have about removing `default` from TriggerTemplate parameters?

**Comment by vtereso** [comment]
Yeah, I would keep it open for discussion about `TriggerTemplate` defaults.

**Comment by vtereso** [comment]
As per WG, the `TriggerTemplate` author should be able to well define the parameters such that  `TriggerTemplate` could be valid without bindings. Closing.
