### ISSUE TITLE
Core interceptor logging is not managed by the logging config map

### ISSUE THREAD

**Issue by guillaumerose** [tektoncd/triggers#1299]
# Expected Behavior

Verbosity is changed

# Actual Behavior

Nothing happen

# Steps to Reproduce the Problem

1. Use triggers with an interceptor
2. Observe logs of the interceptor
3. Change settings in config-logging-triggers
4. Observe logs of the interceptor - nothing changed

# Additional Info

The code is directly calling `zap.NewProduction()` at https://github.com/tektoncd/triggers/blob/main/cmd/interceptors/main.go#L51. I guess it should follow the same path as sharedmain.

**Comment by dibyom** [comment]
Hmm yes, we had https://github.com/tektoncd/triggers/pull/1042/files#diff-e70a102727a8db5630e71a62c7573e669ef5dd56c374af9e9d962cbb184af61d that introduced sharedmain style  for interceptors. I have a branch that rebases that with latest commits - https://github.com/tektoncd/triggers/compare/main...dibyom:feature/interceptor-sdk?expand=1

That might fix this
