### ISSUE TITLE
EventListener sometimes fails

### ISSUE THREAD

**Issue by badamowicz** [tektoncd/triggers#1303]
# Expected Behavior
Every time an EventListener receives a JSON payload  by a webhook (e.g. from Bitbucket) it executes the associated Trigger.

# Actual Behavior
Sometimes the EL will emit this error message:
```
{"level":"error","ts":"2022-01-31T12:10:52.436Z","logger":"eventlistener","caller":"sink/sink.go:278","msg":"couldn't create resource with group version kind \"tekton.dev/v1beta1, Resource=pipelineruns\": admission webhook \"webhook.pipeline.tekton.dev\" denied the request: mutation failed: cannot create patch for round tripped newBytes: cannot marshal interface: json: error calling MarshalJSON for type v1beta1.ArrayOrString: impossible ArrayOrString.Type: \"\"","knative.dev/controller":"eventlistener","eventlistener":"casa-push-listener","namespace":"sre-ci","eventlistenerUID":"bb40fa25-564d-43d1-92ba-db1668d37151","/triggers-eventid":"c30233b8-99bc-4e2e-adb2-79ca8fdb4b35","/trigger":"casa-ci-push-trigger","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:278\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func4\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:164"}
```

# Steps to Reproduce the Problem
As mentioned it is unfortunately not possible to create a reproducible scenario. It happens in about 5% of the EL calls.

# Additional Info

- Kubernetes version:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```
It also happens on our Openshift cluster:
```
$ oc version
Client Version: 4.7.0-202109031319.p0.git.e6f2e9b.assembly.stream-e6f2e9b
Kubernetes Version: v1.21.6+b4b4813
```

- Tekton Pipeline version:

```
$ tkn version
Client version: 0.21.0
Pipeline version: v0.26.0
```
Triggers version is v0.14.2. (For whatever reason not shown in the output.)

On Openshift:
```
$ tkn version
Client version: 0.21.0
Pipeline version: v0.24.3
Triggers version: v0.14.2
```

# Important hint
It is important to note that the problem occurred _after_ we introduced FluxCD for managing all our resources inside thee clusters. So maybe this is not a Trigger bug at all and instead some other weird things are going on. So this issue is more about asking the question: Are there any ideas / suggestions of how we could dig deeper into this issue to get more information?
Thanks in advance!

**Comment by dibyom** [comment]
hey @badamowicz sorry for the delayed response. 
Looking at the error message `error calling MarshalJSON for type v1beta1.ArrayOrString: impossible ArrayOrString.Type:` , I think what is happening is that Triggers is creating a pipelinerun but the pipeline webhook is rejecting it.

The error message comes from https://github.com/tektoncd/pipeline/blob/main/pkg/apis/pipeline/v1beta1/param_types.go#L131

I'd look in the TriggerTemplate and see if there is a place where you are specifying a param whose type is not string or array for some reason (maybe you are specifying an empty string or null or something?) It does seem weird though that this is happening for only a small percentage of calls.
