### ISSUE TITLE
Add frontmatter to API docs

### ISSUE THREAD

**Issue by geriom** [tektoncd/triggers#1306]
### Feature request

Add frontmatter to [docs/triggers-api](https://github.com/tektoncd/triggers/blob/main/docs/triggers-api.md) so it can be included in the [website docs](https://tekton.dev/vault/triggers-main/). The frontmatter would look something like this:

```
<!--
---
title: Triggers API
linkTitle: Triggers API
---
-->
<p>Packages:</p>
...
```

### Use case

The current file can not be included in the website docs because it has no frontmatter. This issue also blocks updating the website theme to a later version, this is causing the build in [this PR](https://github.com/tektoncd/website/pull/339) to fail. The latest versions of Hugo fail if there's a html-only file.

**Comment by khrm** [comment]
@geriom I added frontmatter to `triggers-api.md`.  Will be included in this release.
