### ISSUE TITLE
EventListenerTrigger should have a Name property

### ISSUE THREAD

**Issue by dibbles** [tektoncd/triggers#132]
# Expected Behavior

I expect to be able to easily identify different triggers within an eventlistener.   I would propose that each trigger have a Name, thus I can easily find an entry I want to delete in the situation where only a parameter value differs between multiple entries

# Actual Behavior

If I have multiple entries in an eventlistener using the same triggerbinding and triggertemplate but maybe one different parameter value i have to quite clumsy programmatically check all the values for each trigger until I find the one matching my requirements.

**Comment by khrm** [comment]
@dibbles Are you looking for something like this: https://github.com/tektoncd/triggers/pull/134
