### ISSUE TITLE
 Error when creating "triggers.yaml": create not allowed while custom resource definition is terminating

### ISSUE THREAD

**Issue by soukainakhalkhouli** [tektoncd/triggers#1344]
Hi team ,

While running triggers.yaml by kubectl -n getting-started apply -f triggers.yaml i'm getting this error :

  **kubectl -n getting-started apply -f triggers.yaml
I0407 16:45:26.283014   52144 request.go:665] Waited for 1.175873611s due to client-side throttling, not priority and fairness, request: GET:https://c114-e.us-south.containers.cloud.ibm.com:32006/apis/triggers.tekton.dev/v1alpha1?timeout=32s
triggertemplate.triggers.tekton.dev/getting-started-triggertemplate unchanged
triggerbinding.triggers.tekton.dev/getting-started-pipelinebinding unchanged
Error from server (MethodNotAllowed): error when creating "triggers.yaml": create not allowed while custom resource definition is terminating
**

I'm using the same tutorial and same steps as mentioned in this link  https://github.com/tektoncd/triggers/tree/v0.17.0/docs/getting-started

- Tekton Pipeline version:

  **Output of `tkn version` (base) soukainakhalkhouli@soukainas-MacBook-Pro cicd-2 % tkn version
Client version: 0.23.1
Pipeline version: v0.34.1
Triggers version: v0.19.1
`**

**Comment by dibyom** [comment]
Did you uninstall/reinstall triggers right before you ran the command? From the error message it looks like the triggers CRDs are being deleted when you are trying to create your trigger
