### ISSUE TITLE
Triggerbindings without `spec` is not allowed to create by validation hook

### ISSUE THREAD

**Issue by hakuna-matatah** [tektoncd/triggers#1358]
# Expected Behavior
```
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: load
  namespace: tekton-pipelines
```
Above spec should be created without issues or validation webhook errors

# Actual Behavior
When above yaml is created it throws off the following error:

 ```admission webhook "validation.webhook.triggers.tekton.dev" denied the request: validation failed: missing field(s): spec```

It expects at least spec body to be initialized.
 
# Steps to Reproduce the Problem

1. Create a trigger binding with above spec and you will see the error mentioned above

# Additional Info
Tekton helm charts being used:

		"https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.33.2/release.yaml",
		"https://storage.googleapis.com/tekton-releases/triggers/previous/v0.19.0/release.yaml",
		"https://github.com/tektoncd/dashboard/releases/download/v0.24.1/tekton-dashboard-release.yaml

- Kubernetes version: 1.21

  **Output of `kubectl version`:**

  ```
admission webhook "validation.webhook.triggers.tekton.dev" denied the request: validation failed: missing field(s): spec
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

**Comment by savitaashture** [comment]
Hi @hakuna-matatah 
Any usecase of TriggerBinding without spec filed :thinking:

**Comment by hakuna-matatah** [comment]
> Hi @hakuna-matatah Any usecase of TriggerBinding without spec filed 🤔

Sorry, could you elaborate ?
