### ISSUE TITLE
Should Trigger be a separate Custom Resource

### ISSUE THREAD

**Issue by khrm** [tektoncd/triggers#136]
# Expected Behavior
Trigger inside Eventlistener feels like an independent cr. It has template ref, binding, param, and name. Latter of which seems to be better off with having an ObjectMeta based on the usecase for which it is added. 
If listener have just ref to trigger and trigger is a separate cr, then various operations on triggers can be easily done using verbs.
# Actual Behavior
At present, if we have to change trigger, then we have to loop through triggers and then patch event listener.

/cc @dibyom @ncskier @vtereso @vincent-pli @iancoffey @bobcatfish

**Comment by dibyom** [comment]
So, I think initially we had many of these inside a TriggerBinding and then we extracted them out to make the bindings more reusable/have each CR be responsible for one thing. 

I like the idea of not having to patch event listeners if we have to modify a trigger. Though it might make sense to embed trigger specs in an EL spec as well to reduce the number of things we have to create or for getting started scenarios?

**Comment by vtereso** [comment]
Yeah, I do agree making updates to the Trigger definition is tedious as things stand. In contrast, this does allow for the sink to iterate over the triggers within an `EventListener` without having to make additional API calls. I think this has merit, but we should probably wait until things are slightly more stable before making this decision.

**Comment by vtereso** [comment]
I am biased towards less resources until we see a strong case in terms functionality one way vs the other. With less resources, there is less burden on the user and there is less to go wrong.

**Comment by iancoffey** [comment]
> I am biased towards less resources until we see a strong case in terms functionality one way vs the other.
I agree with this, but am also open to the idea if it proves to make life easier for operators.

**Comment by dibyom** [comment]
There is an active TEP for this now: TEP-009.
