### ISSUE TITLE
Error executing command: fork/exec /bin/sh: exec format error

### ISSUE THREAD

**Issue by akhil97** [tektoncd/triggers#1361]
# Steps to Reproduce the Problem

1. kubectl -n getting-started logs create-webhook-run-pod -c step-create-webhook.

# Additional Info

- Kubernetes version: 

  **Output of `kubectl version`:
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7+k3s1", GitCommit:"8432d7f239676dfe8f748c0c2a3fabf8cf40a826", GitTreeState:"clean", BuildDate:"2022-02-24T23:03:47Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7+k3s1", GitCommit:"8432d7f239676dfe8f748c0c2a3fabf8cf40a826", GitTreeState:"clean", BuildDate:"2022-02-24T23:03:47Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
**

  

- Tekton Pipeline version: v0.35.0

**Comment by akhil97** [comment]
![trigger_logs](https://user-images.githubusercontent.com/19953362/167622096-e1a03d4b-782a-42ae-a09d-cb8945fe58ae.png)
This is the only log that I am getting from the command you shared

**Comment by khrm** [comment]
Did you update the following fields in 'webhook-run.yaml' as it says in the documentation? ```

    GitHubOrg - the GitHub organization you're using for the namespace in this tutorial.
    GitHubUser - your GitHub username.
    GitHubRepo - the GitHub repository you're using for this tutorial.
    ExternalDomain - set this to a value appropriate to your environment: the external domain of the event listener instance.
    GitHubDomain (optional) - if you are using github enterprise, set this to your GitHub domain (e.g. git.corp.com)

```

It's saying `repos/iancoffey/ulmaceae/hooks` in logs.

**Comment by akhil97** [comment]
![image](https://user-images.githubusercontent.com/19953362/167765198-16c9f73e-2d37-4060-a469-0a3f1b8b166c.png)
I have updated the webhook-run.yaml file with the GitHub username. I did not understand from your description what values need to be given for GitHubOrg, GitHubRepo, ExternalDomain. I only have a private IP for my cluster so I don't know how to expose the  eventlistener service and what value to be given for ExternalDomain.

**Comment by khrm** [comment]
For `GitHubOrg`, please put `akhil97`.  GitHubRepo as `ulmaceae` is fine if you use the forked repo of `ulmaceae`. 

If you cannot expose the cluster, then use some website like https://beeceptor.com/ with an endpoint. You will get webhook/triggers at the beeceptor's endpoint endpoint. Use the same request which you receive beeceptor's endpoint and send it as curl after port-forwarding EL pod.

**Comment by akhil97** [comment]
These are the logs that I got now after making the above mentioned changes:- 
Create Webhook
Note: Unnecessary use of -X or --request, POST is already inferred.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0*   Trying 13.233.76.15:443...
* Connected to api.github.com (13.233.76.15) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /cacert.pem
*  CApath: none
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [2456 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [79 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [36 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [36 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=*.github.com
*  start date: Mar 16 00:00:00 2022 GMT
*  expire date: Mar 16 23:59:59 2023 GMT
*  subjectAltName: host "api.github.com" matched cert's "*.github.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Server auth using Basic with user 'akhil97'
* h2h3 [:method: POST]
* h2h3 [:path: /repos/akhil97/ulmaceae/hooks]
* h2h3 [:scheme: https]
* h2h3 [:authority: api.github.com]
* h2h3 [authorization: Basic YWtoaWw5NzpnaHBfUjNmYWpCekxWS2laaGFla3NuaVdpdGhPbnZYTUVuMjhIcExr]
* h2h3 [user-agent: curl/7.83.1-DEV]
* h2h3 [accept: */*]
* h2h3 [content-length: 201]
* h2h3 [content-type: application/x-www-form-urlencoded]
* Using Stream ID: 1 (easy handle 0x7fa9bb4190)
} [5 bytes data]
> POST /repos/akhil97/ulmaceae/hooks HTTP/2
> Host: api.github.com
> authorization: Basic YWtoaWw5NzpnaHBfUjNmYWpCekxWS2laaGFla3NuaVdpdGhPbnZYTUVuMjhIcExr
> user-agent: curl/7.83.1-DEV
> accept: */*
> content-length: 201
> content-type: application/x-www-form-urlencoded
> 
} [5 bytes data]
* We are completely uploaded and fine
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [57 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [57 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
< HTTP/2 201 
< server: GitHub.com
< date: Wed, 11 May 2022 09:55:46 GMT
< content-type: application/json; charset=utf-8
< content-length: 790
< cache-control: private, max-age=60, s-maxage=60
< vary: Accept, Authorization, Cookie, X-GitHub-OTP
< etag: "aca64f15beea0bdd022345ba426bc0851f8e5676a4bface5077ed8f4e753a218"
< x-oauth-scopes: admin:repo_hook, delete_repo, repo
< x-accepted-oauth-scopes: admin:repo_hook, public_repo, repo, write:repo_hook
< github-authentication-token-expiration: 2022-06-09 07:40:13 UTC
< location: https://api.github.com/repos/akhil97/ulmaceae/hooks/357624848
< x-github-media-type: github.v3; format=json
< x-ratelimit-limit: 5000
< x-ratelimit-remaining: 4999
< x-ratelimit-reset: 1652266546
< x-ratelimit-used: 1
< x-ratelimit-resource: core
< access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
< access-control-allow-origin: *
< strict-transport-security: max-age=31536000; includeSubdomains; preload
< x-frame-options: deny
< x-content-type-options: nosniff
< x-xss-protection: 0
< referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
< content-security-policy: default-src 'none'
< vary: Accept-Encoding, Accept, X-Requested-With
< x-github-request-id: C701:5C2C:15DE46:18559D:627B8822
< 
{ [35 bytes data]
{
  "type": "Repository",
  "id": 357624848,
  "name": "web",
  "active": true,
  "events": [
    "pull_request",
    "push"
  ],
  "config": {
    "content_type": "json",
    "insecure_ssl": "1",
    "secret": "********",
    "url": "https://akhiltriggers.free.beeceptor.com"
  },
  "updated_at": "2022-05-11T09:55:46Z",
  "created_at": "2022-05-11T09:55:46Z",
  "url": "https://api.github.com/repos/akhil97/ulmaceae/hooks/357624848",
  "test_url": "https://api.github.com/repos/akhil97/ulmaceae/hooks/357624848/test",
  "ping_url": "https://api.github.com/repos/akhil97/ulmaceae/hooks/357624848/pings",
  "deliveries_url": "https://api.github.com/repos/akhil97/ulmaceae/hooks/357624848/deliveries",
  "last_response": {
    "code": null,
    "status": "unused",
    "message": null
  }
}
100   991  100   790  100   201    267     68  0:00:02  0:00:02 --:--:--   335
* Connection #0 to host api.github.com left intact
I am assuming that it is successful since I got a 201 response this time. 
![image](https://user-images.githubusercontent.com/19953362/167825181-d674c106-8afc-43d4-9b04-59de33ec2f4e.png)
So, now my question is in which repository should I use the git commit commands mentioned above in the docs considering the fact that I am using the forked repo of ulmaceae

**Comment by khrm** [comment]
Please used forked repo of `ulmaceae`.

**Comment by akhil97** [comment]
![image](https://user-images.githubusercontent.com/19953362/167839967-ec2435dc-4f8a-498d-8f14-cd9f8c7211c9.png)
I don't know why I am getting this error when I created a personal access token and added it to secret.yaml file 
![image](https://user-images.githubusercontent.com/19953362/167840734-f9684bac-5d5b-4aaf-a568-804ec3ac5146.png)
I had to do a push to master branch as it was not even asking for username and password when pushing it to any other branch (like mybranch) despite creating it.
![image](https://user-images.githubusercontent.com/19953362/167841225-d1fa2bb9-6d32-47f5-b9ae-bf130dbba1f7.png)

**Comment by khrm** [comment]
@akhil97 Please use `git clone git@github.com:akhil97/ulmaceae.git` instead of https version. After this, you should be able to merge.

**Comment by akhil97** [comment]
It is asking me to provide correct access rights
![image](https://user-images.githubusercontent.com/19953362/167911190-823bccb0-5d2d-41d4-9bef-82795bf2c5ef.png)

**Comment by khrm** [comment]
Please follow this:

https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

**Comment by akhil97** [comment]
I am now able to do a git clone. How do I check the status of the pod if created? I tried the command mentioned in the trigger docs
![image](https://user-images.githubusercontent.com/19953362/167920571-ddc417cc-2070-40e4-a2e7-cb7e2e916f98.png)

**Comment by khrm** [comment]
Check the response in beeceptor. And send that using curl and port-forward.

Please check example folders. It has information on how to use triggers if no external domain.

**Comment by akhil97** [comment]
Are you talking about these examples?:- https://github.com/tektoncd/triggers/tree/main/examples

**Comment by akhil97** [comment]
But this link does not have anything about creating event listener and when I run the commands mentioned in the docs I am getting an error
![image](https://user-images.githubusercontent.com/19953362/168048837-3d87b55d-26b7-47ea-aac7-fa78601dfb69.png)

$ kubectl port-forward service/el-github-pr-7b5947b74f-mzf67 8080
Error from server (NotFound): services "el-github-pr-7b5947b74f-mzf67" not found

**Comment by khrm** [comment]
Check what's your EL service and port-forward that service instead of the one given.

**Comment by akhil97** [comment]
![image](https://user-images.githubusercontent.com/19953362/168219348-1539cc0c-2d5c-4b5d-ab4c-600a8e7a3e75.png)
I have used those commands for my EL service only but I am still getting the same error. Also I want to know from this github link:- https://github.com/tektoncd/triggers/tree/main/docs/getting-started#getting-started-with-triggers at which step is the event listener service getting created? I don't see the corresponding yaml file for it.

**Comment by khrm** [comment]
Check using `kubectl get svc`.

Also, that's pod name in the cmd not EL name.

**Comment by akhil97** [comment]
This is the ouput for kubectl get svc:-
![image](https://user-images.githubusercontent.com/19953362/168226190-83bf9a24-634d-4a8a-9e7c-4f3b70c9e4c8.png)
And for kubectl get el:-
![image](https://user-images.githubusercontent.com/19953362/168226303-3db16731-fcf4-43f7-8def-51eebb38d2d8.png)
Additionally for some reason the event listener pod status is not showing as running. So can you also please tell me where the yaml file for event listener is?

**Comment by khrm** [comment]
EL's yaml:
https://github.com/tektoncd/triggers/blob/104279fbd8ae2791a4a56393003035a42931a121/docs/getting-started/triggers.yaml#L61


Also, can you share EL's deployment/pod? `kc get pod {el-pod-name} -o yaml`

**Comment by akhil97** [comment]
Okay now I understand. I have used the event listener from the same triggers.yaml file that you have specified. However the issue is that the pod is showing status as CrashLoopBackOff and it is restarting automatically.
![image](https://user-images.githubusercontent.com/19953362/168241979-1529dcd6-f31a-4ccb-b2f2-566da48d9c01.png)

**Comment by akhil97** [comment]
These are the logs that I am getting for my event listener:-
![event-listener-logs](https://user-images.githubusercontent.com/19953362/168245504-7fa3e0f3-ddb8-413c-98ef-6c26bb1d98b6.PNG)

**Comment by khrm** [comment]
Try applying admin-roles.yaml file here https://github.com/tektoncd/triggers/pull/1367/files:
```
kubectl apply -f https://raw.githubusercontent.com/tektoncd/triggers/a60fde8fa63bf04e85aa4a0f7a836849e004118f/docs/getting-started/rbac/admin-role.yaml
```

**Comment by akhil97** [comment]
What should I do after this?:-
![image](https://user-images.githubusercontent.com/19953362/168264916-630b44ba-89bc-4aa6-89dd-ced9bd72a220.png)

**Comment by khrm** [comment]
Delete the deployment and then check.
```
kc delete  deployment/el-getting-started-listener
```

**Comment by akhil97** [comment]
Still the same issue:-
![image](https://user-images.githubusercontent.com/19953362/168270272-253f3c54-c644-4523-a8e9-8f9f686a6a6e.png)

**Comment by khrm** [comment]
Is log still the same?

**Comment by akhil97** [comment]
Yeah

**Comment by khrm** [comment]
Try this:
```
kubectl -n getting-started apply -f https://raw.githubusercontent.com/tektoncd/triggers/a60fde8fa63bf04e85aa4a0f7a836849e004118f/docs/getting-started/rbac/admin-role.yaml
kc delete  deployment/el-getting-started-listener -n getting-started
```

**Comment by akhil97** [comment]
It is not working. In fact another event listener is getting created with a different id and its state is changing continuously between Running and CrashLoopBackOff
![image](https://user-images.githubusercontent.com/19953362/168272632-bb0b3316-9296-48af-8494-914bfd71db07.png)

**Comment by khrm** [comment]
Can you share the logs for the pod? Is it still the same?

**Comment by akhil97** [comment]
Yeah, still the same. The pod is somehow restarting by itself with another id
![image](https://user-images.githubusercontent.com/19953362/168274409-dfd3ad1e-3da9-49f3-af62-941397fdca78.png)

**Comment by khrm** [comment]
What's the version of Triggers that you are using? Can you try latest release?
```
kubectl apply -f https://storage.googleapis.com/tekton-releases/triggers/previous/v0.20.0/release.yaml
kubectl apply -f https://storage.googleapis.com/tekton-releases/triggers/previous/v0.20.0/interceptors.yaml
```

**Comment by akhil97** [comment]
Okay, I think the restarting issue is resolved now. So should I now try out these steps?:- https://github.com/tektoncd/triggers/tree/main/examples

**Comment by khrm** [comment]
Yes.

**Comment by akhil97** [comment]
Can I give another port number for this step:-
kubectl port-forward service/el-${EVENTLISTENER_NAME} 8080
beacuse it is saying address already in use. If yes what changes shouls I make?
![image](https://user-images.githubusercontent.com/19953362/168282885-e7d59805-8ac5-4d3f-bd37-b94697f1576c.png)

**Comment by khrm** [comment]
Yes, you can use different port.

**Comment by khrm** [comment]
Sorry, you can't.

**Comment by khrm** [comment]
Try this:

```
kubectl port-forward service/el-${EVENTLISTENER_NAME} 8080
```

**Comment by khrm** [comment]
Semicolon is the difference here.

**Comment by akhil97** [comment]
Okay that worked. Now for the next step here what should be given for the commit id:-
![image](https://user-images.githubusercontent.com/19953362/168288918-1ae087fc-8d5e-4049-ba16-97da10bf31c9.png)

**Comment by khrm** [comment]
Your forked repo's latest commit id

**Comment by akhil97** [comment]
I have given the latest commit id but the curl command just says not found:-
![image](https://user-images.githubusercontent.com/19953362/168298137-f3d2be12-9c16-47c8-b663-59091e2535d0.png)
![image](https://user-images.githubusercontent.com/19953362/168298200-33f1cbf6-ae12-4b46-99d2-8a5dd8925df6.png)
![image](https://user-images.githubusercontent.com/19953362/168298288-3ca06c28-0dfd-4e13-b4d7-ae66c8b8ae9b.png)

**Comment by khrm** [comment]
What's the port number where you have port-forwarded? Check that.

**Comment by akhil97** [comment]
![image](https://user-images.githubusercontent.com/19953362/168299068-40287995-6387-405b-bd0d-6b375af858cf.png)
It is 8080 only

**Comment by khrm** [comment]
It's `localhost:34053`. @akhil97

**Comment by akhil97** [comment]
![image](https://user-images.githubusercontent.com/19953362/168302936-14be3b7b-fc2d-40b6-b992-dadd34304d0e.png)
![image](https://user-images.githubusercontent.com/19953362/168303064-265fcb08-6728-42b3-92a8-20989bf6584f.png)
Curl command gives empty reply from server and some error in port forwarding command too

**Comment by khrm** [comment]
What's your dev environment? Is it Linux? Or Mac? Install socat.

**Comment by akhil97** [comment]
I am using Linux.
I am still facing the socat issue
![image](https://user-images.githubusercontent.com/19953362/168335172-ce2067b6-2676-4775-92fb-17be0fd0214f.png)

**Comment by khrm** [comment]
How have you installed Kubernetes? Are you using https://github.com/kubernetes-sigs/kind/ ? Or something else?

**Comment by akhil97** [comment]
I have followed the steps mentioned in this documentation for installing via minikube:- https://tekton.dev/docs/getting-started/tasks/

**Comment by akhil97** [comment]
I have mentioned these details right in the beginning while creating a new issue: -
Kubernetes version:

**Output of kubectl version:
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7+k3s1", GitCommit:"8432d7f239676dfe8f748c0c2a3fabf8cf40a826", GitTreeState:"clean", BuildDate:"2022-02-24T23:03:47Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7+k3s1", GitCommit:"8432d7f239676dfe8f748c0c2a3fabf8cf40a826", GitTreeState:"clean", BuildDate:"2022-02-24T23:03:47Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
**

Tekton Pipeline version: v0.35.0

**Comment by khrm** [comment]
Try:

```
minikube service  {service-name-el}

```

**Comment by akhil97** [comment]
So which type of clusters should be used for running your example?

**Comment by akhil97** [comment]
I also wanted to know if we can use GKE cluster on GCP for running this example?

**Comment by khrm** [comment]
Yes, we can use GKE. Did you try running `minikube service  {service-name-el}`? Did it work?

**Comment by akhil97** [comment]
Sorry @khrm , a correction from my side based on the previous comments. I am not using minikube cluster. I am using k3s cluster.
 **Output of kubectl version:
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7+k3s1", GitCommit:"8432d7f239676dfe8f748c0c2a3fabf8cf40a826", GitTreeState:"clean", BuildDate:"2022-02-24T23:03:47Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7+k3s1", GitCommit:"8432d7f239676dfe8f748c0c2a3fabf8cf40a826", GitTreeState:"clean", BuildDate:"2022-02-24T23:03:47Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
So the minikube command simply returned bash: minikube: command not found

**Comment by akhil97** [comment]
The package socat is not found error is not coming on GKE cluster. But I am getting a message in the log that some parameter for git repository url is missing and I am unable to understand which yaml file needs to be changed 
![image](https://user-images.githubusercontent.com/19953362/169027002-170ecd53-03b2-4ed0-8f8e-48e923bae75d.png)

**Comment by khrm** [comment]
I think if you are using GKE, then you don't need to port-forwards. Use IP and then getting started should work.

**Comment by khrm** [comment]
Directly configure using ingress.

**Comment by akhil97** [comment]
The pipeline run pod is getting created but it is not in running state
![image](https://user-images.githubusercontent.com/19953362/169475191-44f73ba9-7d9b-4936-b19e-027521bfb834.png)
This is the description of that pipeline run pod:-
Name:         getting-started-pipeline-run-bfhrt-build-docker-image-pmz-68zrj
Namespace:    getting-started
Priority:     0
Node:         gke-sample-cluster-default-pool-3d1016ca-57js/10.128.0.3
Start Time:   Wed, 18 May 2022 13:53:19 +0000
Labels:       app.kubernetes.io/managed-by=tekton-pipelines
              tekton.dev/conditionCheck=getting-started-pipeline-run-bfhrt-build-docker-image-pmz-q2bqs
              tekton.dev/conditionName=go-test
              tekton.dev/pipeline=getting-started-pipeline
              tekton.dev/pipelineRun=getting-started-pipeline-run-bfhrt
              tekton.dev/pipelineTask=build-docker-image
              tekton.dev/taskRun=getting-started-pipeline-run-bfhrt-build-docker-image-pmz-q2bqs
              triggers.tekton.dev/eventlistener=getting-started-listener
              triggers.tekton.dev/trigger=
              triggers.tekton.dev/triggers-eventid=879b7a7a-485f-49b2-b7ad-6c6bf664c1ad
Annotations:  pipeline.tekton.dev/release: v0.20.0
              tekton.dev/ready: READY
Status:       Failed
IP:           10.40.1.14
IPs:
  IP:           10.40.1.14
Controlled By:  TaskRun/getting-started-pipeline-run-bfhrt-build-docker-image-pmz-q2bqs
Init Containers:
  working-dir-initializer:
    Container ID:  containerd://7ce4b0691056545db49041f8b7f7ab3218bc3745316acc3b982fb0cb7578534f
    Image:         gcr.io/distroless/base@sha256:92720b2305d7315b5426aec19f8651e9e04222991f877cae71f40b3141d2f07e
    Image ID:      gcr.io/distroless/base@sha256:92720b2305d7315b5426aec19f8651e9e04222991f877cae71f40b3141d2f07e
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
    Args:
      -c
      mkdir -p /workspace/source-repo
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 18 May 2022 13:53:21 +0000
      Finished:     Wed, 18 May 2022 13:53:21 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /tekton/home from tekton-internal-home (rw)
      /tekton/results from tekton-internal-results (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-kn7pp (ro)
      /workspace from tekton-internal-workspace (rw)
  place-tools:
    Container ID:  containerd://67796212dc0512e615b5ab493d1fd39c85c44511eea89e4509cfda48ee135d1f
    Image:         gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.20.0@sha256:9621a893ae2d4eb91fa8d56bf6f15774be8abd26e5d3f5e10a3f8eb8f31d540a
    Image ID:      gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint@sha256:9621a893ae2d4eb91fa8d56bf6f15774be8abd26e5d3f5e10a3f8eb8f31d540a
    Port:          <none>
    Host Port:     <none>
    Command:
      /ko-app/entrypoint
      cp
      /ko-app/entrypoint
      /tekton/tools/entrypoint
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 18 May 2022 13:53:21 +0000
      Finished:     Wed, 18 May 2022 13:53:22 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /tekton/tools from tekton-internal-tools (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-kn7pp (ro)
Containers:
  step-git-source-source-repo-hfq5v:
    Container ID:  containerd://33bba701ba0bd8698afe6099c7196439965818516e67fc5d8defed8b9150f254
    Image:         gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.20.0@sha256:6b6a8fd4a7aeae8995a4acd2b2fb77458c287b309f2ccabdb257a067f37521b8
    Image ID:      gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init@sha256:6b6a8fd4a7aeae8995a4acd2b2fb77458c287b309f2ccabdb257a067f37521b8
    Port:          <none>
    Host Port:     <none>
    Command:
      /tekton/tools/entrypoint
    Args:
      -wait_file
      /tekton/downward/ready
      -wait_file_content
      -post_file
      /tekton/tools/0
      -termination_path
      /tekton/termination
      -entrypoint
      /ko-app/git-init
      --
      -url
      https://github.com/akhil97/ulmaceae
      -path
      /workspace/source-repo
      -revision
      master
    State:          Terminated
      Reason:       Completed
      Message:      [{"key":"commit","value":"794594bf3352eb09337ad9161c19a6ef25cd7b6c","resourceName":"source-repo","resourceRef":{"name":"source-repo"}},{"key":"url","value":"https://github.com/akhil97/ulmaceae","resourceName":"source-repo","resourceRef":{"name":"source-repo"}},{"key":"StartedAt","value":"2022-05-18T13:53:49.541Z","type":"InternalTektonResult"}]
      Exit Code:    0
      Started:      Wed, 18 May 2022 13:53:25 +0000
      Finished:     Wed, 18 May 2022 13:53:50 +0000
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:                0
      ephemeral-storage:  0
      memory:             0
    Environment:
      HOME:                  /tekton/home
      TEKTON_RESOURCE_NAME:  source-repo
      HOME:                  /tekton/home
    Mounts:
      /tekton/creds from tekton-creds-init-home-p6hxw (rw)
      /tekton/downward from tekton-internal-downward (rw)
      /tekton/home from tekton-internal-home (rw)
      /tekton/results from tekton-internal-results (rw)
      /tekton/tools from tekton-internal-tools (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-kn7pp (ro)
      /workspace from tekton-internal-workspace (rw)
  step-condition-check-go-test:
    Container ID:  containerd://bb5b46abb3347df5b136ddc5612d6fd9973d50833bbdf712452490c334327b3a
    Image:         golang
    Image ID:      docker.io/library/golang@sha256:02c05351ed076c581854c554fa65cb2eca47b4389fb79a1fc36f21b8df59c24f
    Port:          <none>
    Host Port:     <none>
    Command:
      /tekton/tools/entrypoint
    Args:
      -wait_file
      /tekton/tools/0
      -post_file
      /tekton/tools/1
      -termination_path
      /tekton/termination
      -entrypoint
      go
      --
      test
      ./...
    State:          Terminated
      Reason:       Error
      Message:      [{"key":"StartedAt","value":"2022-05-18T13:53:51.354Z","type":"InternalTektonResult"}]
      Exit Code:    1
      Started:      Wed, 18 May 2022 13:53:48 +0000
      Finished:     Wed, 18 May 2022 13:53:51 +0000
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:                0
      ephemeral-storage:  0
      memory:             0
    Environment:
      HOME:  /tekton/home
    Mounts:
      /tekton/creds from tekton-creds-init-home-k7tjd (rw)
      /tekton/home from tekton-internal-home (rw)
      /tekton/results from tekton-internal-results (rw)
      /tekton/tools from tekton-internal-tools (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-kn7pp (ro)
      /workspace from tekton-internal-workspace (rw)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  tekton-internal-workspace:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  tekton-internal-home:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  tekton-internal-results:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  tekton-internal-tools:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  tekton-internal-downward:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.annotations['tekton.dev/ready'] -> ready
  tekton-creds-init-home-p6hxw:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  tekton-creds-init-home-k7tjd:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  kube-api-access-kn7pp:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:                      <none>

**Comment by dibyom** [comment]
Might be resolved. @khrm to check

**Comment by dibyom** [comment]
From @khrm - we might need to create a new pipeline to fix this again

**Comment by dibyom** [comment]
From @khrm - the tutorial works but we still need to update the pipeline to remove pipeline resources. Tracked in 
https://github.com/tektoncd/triggers/issues/1421
