### ISSUE TITLE
Error: a container name must be specified for pod pipeline run for build docker image step

### ISSUE THREAD

**Issue by akhil97** [tektoncd/triggers#1369]
# Steps to Reproduce the Problem

1. kubectl -n getting-started apply -f ./docs/getting-started/pipeline.yaml
# Additional Info
The following command is giving this error in the log
kubectl logs --follow getting-started-pipeline-run-nplnw-build-docker-image-pxc-g5x8c -n getting-started
error: a container name must be specified for pod getting-started-pipeline-run-nplnw-build-docker-image-pxc-g5x8c, choose one of: [step-git-source-source-repo-xj6kr step-condition-check-python-test] or one of the init containers: [working-dir-initializer place-tools]

- Kubernetes version:

  **Output of `kubectl version`:
```
 Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.11-gke.1100", GitCommit:"20da4c21b3a6b1a56ff6ad5ecb7dee013aaf1b83", GitTreeState:"clean", BuildDate:"2022-04-01T09:40:07Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
  ```
**  

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`
v0.20.0
**

I am using GKE based cluster on GCP

**Comment by AlanGreene** [comment]
As the error message states you must specify the name of the container for which to retrieve the logs, or you can explicitly request logs for all containers in the Pod.

For example, to display logs of the `step-condition-check-python-test` container:
`kubectl logs getting-started-pipeline-run-nplnw-build-docker-image-pxc-g5x8c -n getting-started -c step-condition-check-python-test`

or to display logs for all containers in the pod:
`kubectl logs getting-started-pipeline-run-nplnw-build-docker-image-pxc-g5x8c -n getting-started --all-containers`

You can find more details in the `kubectl` docs: https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#logs

**Comment by akhil97** [comment]
I tried the second command mentioned and I am getting this in my logs 
![image](https://user-images.githubusercontent.com/19953362/170541700-3ac97965-2d98-42a4-bf96-edea125484ad.png)
I am using a GCS repository on google cloud and I have created the private ssh key and added it to secret.yaml but it is saying permission denied due to some reason
