### ISSUE TITLE
Update EventListener Reconciler 

### ISSUE THREAD

**Issue by vtereso** [tektoncd/triggers#137]
Before https://github.com/tektoncd/triggers/pull/70, on reconciliation we would [check the existing resources against the intended resources](https://github.com/tektoncd/triggers/blob/f4ef2ffa611c3d2bcd9d2400bf94b51646b231fc/pkg/reconciler/v1alpha1/eventlistener/eventlistener.go#L152), which should always result in an update since the internal resources never have the defaults set by the K8S API server (these also vary between K8S). Now, this is handled with multiple checks against only the fields that were internally specified [through individual checks](https://github.com/vtereso/triggers/blob/3773c571ce64319aa7b073f0f2fe9fbb8d982d8d/pkg/reconciler/v1alpha1/eventlistener/eventlistener.go#L239). 

This is less than ideal, but it is a result of the `EventListener` reconciler attempting to play the role of the admission webhook for our reconciled resources (we revert changes that should not have been approved). On `EventListener` creation, a service and deployment are generated. After this point, the reconciler should do nothing additional for this same `EventListener`, that is to say, the reconciler is only concerned with `EventListener` create events. EDIT: I suppose we still need to handle updates for if the `Deployment` status changes?

Since generated resources have well defined labels, we can use these to specify validation for only our resources. This way, we will deny all updates except the ones we deem acceptable (as of now probably only scaling the deployment replicas above 1). This cleans up the aforementioned reconciliation on updates, but the overall tests as well and creates a better separation of responsibilities.

**Comment by vtereso** [comment]
Also note, that currently we have an informer on Deployments/Services that is doing a pass through to the `EventListener` reconciler, which would be unnecessary with the above.

**Comment by vincent-pli** [comment]
@vtereso 
I just back from another project, maybe missing some discussion.
I wonder to know why `Controller` of `EventListener` take the responsibility like a `webhook ` for resources (deployment, SVC)? 

I think we just need make sure the resources are existed, no need to guarantee them from destruction with intent.
Maybe I missing something 🤔

**Comment by vtereso** [comment]
Ideally, the reconciler would only propogate changes from the `EventListener` downward into the `Service` and `Deployment`. However, since the `Deployment` status can be updated, we need the informer to enqueue the `EventListener` reconciler to get this updated status. I believe the only manual configuration we want to permit would be scaling the replicas on a `Deployment` so this too would trigger the `EventListener` reconciler due to the aforementioned reconciler enqueue.

Contrary to this, our generated `Service` and `Deployment` allow any update to their definition normally permissable by the K8s apiserver. This way, the reconciler is getting triggered and we must make comparisons against our intended creation state and "revert" the definition. This makes for some ugly code as mentioned above and also isn't a great separation of responsibility.

**Comment by vtereso** [comment]
The above would be a nice to have I suppose. Initially I was trying to use one of the K8s libraries to default the values for the Deployment internally, but our locked versioned don't necessary coincide with the K8s environment. However, using https://kubernetes.io/docs/reference/using-api/api-concepts/#dry-run should achieve the intended result and at least cleans up the ugly code portion of this.
