### ISSUE TITLE
Remove conditions from getting-started example

### ISSUE THREAD

**Issue by savitaashture** [tektoncd/triggers#1380]
**Details:**
As part of Pipeline [v0.37.0](https://github.com/tektoncd/pipeline/releases/tag/v0.37.0) release `Conditions` are completely removed and Triggers [getting-started](https://github.com/tektoncd/triggers/blob/main/docs/getting-started/pipeline.yaml#L109-L122) example using `Conditions` and because of that all the integration tests are failing for Pull Request with below error

```
resource mapping not found for name: "go-test" namespace: "getting-started" from "/home/prow/go/src/github.com/tektoncd/triggers/docs/getting-started/pipeline.yaml": no matches for kind "Condition" in version "tekton.dev/v1alpha1"
ensure CRDs are installed first
Error from server (BadRequest): error when creating "/home/prow/go/src/github.com/tektoncd/triggers/docs/getting-started/pipeline.yaml": admission webhook "webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "conditions"
```

**Comment by khrm** [comment]
Resolved by #1381
