### ISSUE TITLE
tekton trigger : {"level":"error","ts":"2022-07-14T10:07:57.253Z","logger":"eventlistener","caller":"sink/sink.go:278","msg":"couldn't unmarshal json from the TriggerTemplate: invalid character 'r' after object key:value pair","knative.dev/controller":"

### ISSUE THREAD

**Issue by rremella** [tektoncd/triggers#1392]
# Expected Behavior

Need to split the body.pullRequest.fromRef.id from bitbucket payload

# Actual Behavior

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
{"level":"error","ts":"2022-07-14T10:07:57.253Z","logger":"eventlistener","caller":"sink/sink.go:278","msg":"couldn't unmarshal json from the TriggerTemplate: invalid character 'r' after object key:value pair","knative.dev/controller":"eventlistener","eventlistener":"bitbucket-listener","namespace":"p2","eventlis
  ```

- Tekton Pipeline version:

Client version: 0.22.0
Pipeline version: v0.24.3
Triggers version: v0.14.2

apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: bitbucket-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: bitbucket-triggers
      interceptors:
        - ref:
            name: "bitbucket"
          params:
            - name: secretRef
              value:
                secretName: bitbucket-secret
                secretKey: secretToken
            - name: eventTypes
              value:
                 - pr:opened
        - cel:
            overlays:
            - key: REF_NAME
              expression: body.pullRequest.fromRef.id.split('/')
      bindings:
        - ref: bucket-binding
      template:
        ref: bucket-template

----

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: bucket-binding
spec:
  params:
    - name: PULL_REQUEST_FROM_BRANCH
      value: $(body.pullRequest.fromRef.id)
    - name: SPLIT
      value: $(extensions.REF_NAME)

**Comment by dibyom** [comment]
@rremella looking at the error it looks like the msg is from the trigger template replacement, could you share the triggerTemplate?

**Comment by rremella** [comment]
@dibyom , thanks for the response, please find the trigger template I am using

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: bucket-template
spec:
  params:
  - name: PULL_REQUEST_FROM_BRANCH
    default: default-triggertemplate-value
  - name: SPLIT
    default: default-triggertemplate-value
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: example-parameterized-pipelinerun-
    spec:
      pipelineRef:
        name: bucket-pipeline
      params:
        - name: PULL_REQUEST_FROM_BRANCH
          value: $(tt.params.PULL_REQUEST_FROM_BRANCH)
        - name: SPLIT
          value: $(tt.params.SPLIT)

**Comment by rremella** [comment]
> @dibyom , thanks for the response, please find the trigger template I am using
> 
> apiVersion: triggers.tekton.dev/v1alpha1 kind: TriggerTemplate metadata: name: bucket-template spec: params:
> 
> * name: PULL_REQUEST_FROM_BRANCH
>   default: default-triggertemplate-value
> * name: SPLIT
>   default: default-triggertemplate-value
>   resourcetemplates:
> * apiVersion: tekton.dev/v1beta1
>   kind: PipelineRun
>   metadata:
>   generateName: example-parameterized-pipelinerun-
>   spec:
>   pipelineRef:
>   name: bucket-pipeline
>   params:
>   - name: PULL_REQUEST_FROM_BRANCH
>   value: $(tt.params.PULL_REQUEST_FROM_BRANCH)
>   - name: SPLIT
>   value: $(tt.params.SPLIT)

**Comment by rremella** [comment]
@dibyom , thanks for the response, please find the trigger template I am using

> 
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: bucket-template
spec:
  params:
  - name: PULL_REQUEST_FROM_BRANCH
    default: default-triggertemplate-value
  - name: SPLIT
    default: default-triggertemplate-value
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: example-parameterized-pipelinerun-
    spec:
      pipelineRef:
        name: bucket-pipeline
      params:
        - name: PULL_REQUEST_FROM_BRANCH
          value: $(tt.params.PULL_REQUEST_FROM_BRANCH)
        - name: SPLIT
          value: $(tt.params.SPLIT)

**Comment by rremella** [comment]
@dibyom 

Any comment on trigger template above ?

**Comment by rremella** [comment]
@dibyom

Any comment on trigger template above ?

**Comment by dibyom** [comment]
hi @rremella not sure if this is the case in your template or an issue with the pasted formatting in your comment above but there is a missing space  in `value` fields for params i.e. it should be aligned with the name field.
