### ISSUE TITLE
Bug: Configuring Debug log for EventListeners does not work

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#1399]
# Expected Behavior

Users should be able to configure debug logging for their ELs by following  https://github.com/tektoncd/triggers/blob/main/docs/troubleshooting.md#configuring-debug-logging-for-eventlisteners

# Actual Behavior

Log level does not get changed to debug.

# Steps to Reproduce the Problem

1. Follow steps in https://github.com/tektoncd/triggers/blob/main/docs/troubleshooting.md#configuring-debug-logging-for-eventlisteners

# Additional Info

Reported in https://tektoncd.slack.com/archives/CL3T51NRF/p1658482763866399

**Comment by khrm** [comment]
Change in the documentation: https://github.com/tektoncd/triggers/pull/1401

**Comment by dibyom** [comment]
I just tried this for https://github.com/tektoncd/triggers/pull/1423#issuecomment-1224899518 and my EL log was still set to info till restart

**Comment by dibyom** [comment]
Hmm, the docs do mention the need to delete and recreate the EL. So, I think this works but having to restart the EL just to set debug logging seems excessive

**Comment by khrm** [comment]
This one was fixed. Need to change behaviour of logging tracked by another issue.
