### ISSUE TITLE
Create docs for each type

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/triggers#14]
## Expected behavior

Users of Triggers should have a place to look for docs on each CRD that they'll be interacting with.

## Actual behavior

We have no docs, but in #10 we'll be adding the types. The only docs we have at the moment are in [the design doc](https://docs.google.com/document/d/1fngeNn3kGD4P_FTZjAnfERcEajS7zQhSEUaN7BYIlTw/edit#heading=h.iyqzt1brkg3o).

## Additional info

One decision we may want to make at this point is whether we want to have a markdown file per type, the way that [Tekton Pipelines does](https://github.com/tektoncd/pipeline/tree/master/docs),  or if we want this kind of documentation to live with the code and primarily be visible at https://godoc.org/.

If we decide to rely on godocs, we need to have more carefully curated godocs than https://godoc.org/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1alpha1 does, specifically:

* We need to avoid including docs here that shouldn't be user facing
* We should have inline examples
* We'd need to include docs like this https://github.com/tektoncd/pipeline/blob/master/docs/pipelines.md#ordering which aren't necessarily about individual types

It may also be harder to version godocs and present them nicely in an interface such as https://knative.dev/docs/ or https://skaffold.dev/docs/ (which i think both use netlify?)

**Comment by vtereso** [comment]
I will approach this in the Tekton way with a markdown for each.
