### ISSUE TITLE
[Docs] RBAC link points to google cloud docs

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/triggers#1408]
# Expected Behavior

RBAC link points to k8s docs

# Actual Behavior

> You must grant the `cluster-admin` privilege to the user with which you installed Tekton Pipelines.

Is this information correct?

> For instructions, see [Role-based access control](https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control#prerequisites_for_using_role-based_access_control).

The RBAC link points to google cloud docs?

**Comment by dibyom** [comment]
@afrittoli which doc page is this link in ?

**Comment by AlanGreene** [comment]
Looks like https://tekton.dev/docs/triggers/install/

last point in the Prerequisites
