### ISSUE TITLE
Following example instructions gives me 2 listener pods - examples broken as cant follow instructions

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/triggers#142]
Followed the instructions in example/README.md
I created the resources for the example by following instruction No 1

This gave me 2 listener svc and 2 listener pods 
Both were cerated at the exact same time and then when trying to port forward in step No 4 it breaks as there is 2 pods called listener on the same port with a label called listener  

This happens when when you apply `kubectl apply -f eventlisteners/eventlistener.yaml`

**Comment by dibyom** [comment]
Haven't run into this yet. Is this still a problem @CarolynMabbott ?

**Comment by CarolynMabbott** [comment]
Dont get this issue anymore, have tried multiple times and works every time now
