### ISSUE TITLE
Sink timeout config is invalid

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#1429]
# Expected Behavior

Newly created eventlisteners with no customization should not have invalid configuration

# Actual Behavior

I see the following log line when I create a new listener:

```
[github-listener-el-github-listener-57b8fdb677-zdtd6]: {"level":"warn","ts":"2022-08-23T20:52:42.423Z","logger":"eventlistener","caller":"v2/config.go:178","msg":"Sink timeout configuration is invalid, default to -1 (no timeout)"}

```

# Steps to Reproduce the Problem

1. Use Triggers release v0.20.2
2. Apply the github example
3. tkn logs el github-listener

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

**Comment by khrm** [comment]
We don't use this value at all, it's coming from the knative eventing package we use.
