### ISSUE TITLE
Enabling debug mode requires restarting event listener

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#1430]
### Feature request

When the Triggers controller creates the EventListener deployment it passes in an env var called `K_LOGGING_CONFIG` which contains a JSON string describing the logging config (currently, we pass in the same logging config that applies to the controller itself). The EventListener deployment/pod then uses this logging config to initialize its logger.

To update the logging config for an EL, our docs say to update `config-logging-triggers` i.e. the controller logging config and then to delete the EL deployment. This results in the controller creating a new EL deployment with the updated logging config. 
To rollback, one would have to repeat both steps above. For something as simple as enabling debug logs, this seems excessive

In addition, this means that debug logging is enabled on the controller as well as any new event listeners that were created while these log changes were active.

### Potential solutions

1. Update our docs to directly update K_LOGGING_CONFIG on the EL deployment - this will require a change in the reconciler to ignore updates to this field when reconciling ELs.

2. Add some annotation or label to the EL to indicate that debug logging should be enabled - we'd be adding custom code

3. Always log the event body on failure - this may be excessive since many events will fail due to filtering and event body sizes can be large (MBs)

4. Add a `tkn command` to enable debug logging - this can automate the current process

5. Add a separate `config-logging-el` config map per namespace - this is what we used to do before the move to K_LOGGING_CONFIG.

### Use case

1. I'd like to log the event body when my trigger processing fails

**Comment by khrm** [comment]
I like the 3rd approach better.

**Comment by khrm** [comment]
Also, the fifth approach won't require access to the tekton-pipelines namespace.

**Comment by khrm** [comment]
/reopen
/remove-lifecycle-rotten
This needs to be done.

**Comment by khrm** [comment]
/remove-lifecycle rotten
/lifecycle frozen We need to do this but it's not part of immediate milestones. But it's part of a long term roadmap.

**Comment by khrm** [comment]
/remove-lifecycle rotten
/lifecycle-frozen
We need to add this later on.
