### ISSUE TITLE
PodSecurityPolicy removed in Kubernetes 1.25

### ISSUE THREAD

**Issue by SQLExceptionPhil** [tektoncd/triggers#1447]
# Expected Behavior
The released deployment manifest doesn't have deprecated resources listed in it.

# Actual Behavior
PodSecurityPolicy tekton-pipelines is listed in the deployment manifest which is a deprecated resource as of 1.21 and will be deleted in 1.25.

# Steps to Reproduce the Problem

1. download the latest release.yaml (tested v0.20.2 - is also included in v0.21.0)

# Additional Info

- Kubernetes version: 1.24

  **Output of `kubectl version`:**

  ```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-08-17T18:54:23Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:15:38Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version: v0.37.3

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
Client version: 0.25.0
Pipeline version: v0.37.3
Triggers version: v0.20.2
Dashboard version: v0.28.0

**Comment by dibyom** [comment]
We are tracking our alternative to PSP deprecation in https://github.com/tektoncd/pipeline/issues/4112

**Comment by dibyom** [comment]
We need to port https://github.com/tektoncd/pipeline/pull/5536 to Triggers

**Comment by dibyom** [comment]
https://github.com/tektoncd/pipeline/pull/5652/ added PSA restricted to the entire tekton-pipelines namespace which means triggers controllers will fail to come up with Pipeline v0.41

**Comment by savitaashture** [comment]
@dibyom I see your PR for this issue so assigned to you
