### ISSUE TITLE
tekton trigger controller support args "-el-image-pull-secrets" for pull eventlistenersink docker image

### ISSUE THREAD

**Issue by gsgs-libin** [tektoncd/triggers#1448]
I push all the image to private docker repositories, So I hope to support the setup for imagePullSecrets.

https://github.com/tektoncd/triggers/blob/main/cmd/controller/main.go

![image](https://user-images.githubusercontent.com/22513159/190984062-b1ca40aa-97ab-464a-9e86-29d04e8e600e.png)

**Comment by savitaashture** [comment]
Hey @gsgs-libin 

You can specify imagePullSecrets by providing `kubernetesResource` in eventlistener object https://github.com/tektoncd/triggers/blob/main/pkg/apis/triggers/v1beta1/event_listener_types.go#L85

**Comment by savitaashture** [comment]
Let me know if you have any other query

**Comment by gsgs-libin** [comment]
> Hey @gsgs-libin
> 
> You can specify imagePullSecrets by providing `kubernetesResource` in eventlistener object https://github.com/tektoncd/triggers/blob/main/pkg/apis/triggers/v1beta1/event_listener_types.go#L85

Thank you for your reply, but I set it up to find that it will report an error, I don't know if there is a problem with my configuration，but the annotations is in effect。https://github.com/tektoncd/triggers/blob/96a078b105762f26a77dc9e52eb3cb34e0ad5de9/vendor/k8s.io/client-go/applyconfigurations/core/v1/podspec.go#L46
```shell
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: eventlister-h5-eve
  namespace: tekton-run
spec:
  resources:
    kubernetesResource:
      spec:
        template:
          metadata:
            annotations:
              meitu.com/tekton: lb6
          spec:
            imagePullSecrets:
            - name: swr-image-pull-secret
```

```shell
$ k apply -f eventlister.yaml -n tekton-run
Error from server (BadRequest): error when creating "h5-eve.yaml": admission webhook "validation.webhook.triggers.tekton.dev" denied the request: validation failed: must not set the field(s): spec.resources.kubernetesResource.spec.template.spec.imagePullSecrets
```

**Comment by savitaashture** [comment]
Ah i see
