### ISSUE TITLE
Migrate create-webhook and create-ingress to the Tekton Catalog

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#1450]
The two tasks are part of the getting-started tutorial and are usable in general outside of the tutorial. I think having it in the catalog would help make it more discoverable

https://github.com/tektoncd/triggers/blob/main/docs/getting-started/create-webhook.yaml

https://github.com/tektoncd/triggers/blob/main/docs/getting-started/create-ingress.yaml

**Comment by ehudyonasi** [comment]
I would like to take it as a good first issue.
As I understand it's moving those files to the catalog repo so that can be installed via the kubectl / tkn cli?
