### ISSUE TITLE
Eventlistener service not associated with correct listner pod / deployment

### ISSUE THREAD

**Issue by akihikokuroda** [tektoncd/triggers#146]
# Expected Behavior

The event listener service is associated the corresponding event listener pod / deployment.  The event sent the event listener service should be sent the right event lister pod / deployment.

# Actual Behavior

The event listener service is associated with the corresponding pod / deployment by the selector labels but the pod / deployment for the event listener doesn't have a unique label for the event listener so that the event listener service can not identify the correct pod / deployment.

The current labels of the deployment are:
```
      app.kubernetes.io/managed-by: EventListener
      app.kubernetes.io/part-of: Triggers
```
and pod are:
```
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    pod-template-hash: 7554db554
```
# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

**Comment by dibyom** [comment]
Hmm, I thought we added the eventlistener name as a label as well
