### ISSUE TITLE
Remove webhook validation on delete

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#1468]
@dibyom I think this is also needed for triggers

_Originally posted by @vdemeester in https://github.com/tektoncd/pipeline/issues/5610#issuecomment-1283591181_

**Comment by bigkevmcd** [comment]
Looks to me like this is done?

https://github.com/tektoncd/triggers/commit/74b4749fc ?

**Comment by dibyom** [comment]
Yup #1470 fixes this
