### ISSUE TITLE
The error type is not understood

### ISSUE THREAD

**Issue by PollosD** [tektoncd/triggers#1481]
I tried to use filter to determine whether the string "develop" exists in the ref field, but the error " rpc error: code = InvalidArgument desc = error evaluating cel expression: expression \"body.ref.exists(r, r.name == 'refs/heads/develop')\" failed to evaluate: got 'types.String', expected iterable type"", I don't understand what this means, my expression is as follows: body.ref .exists(r, r.name == 'refs/heads/develop'), where body.ref is the information returned by the webhook

**Comment by bigkevmcd** [comment]
Hi @PollosD 

`exists` takes an array or list, and calls the "predicate" on each of them, and returns true if any of them return true.

https://github.com/google/cel-spec/blob/master/doc/langdef.md#macros

It's not clear what you're trying to do, but if you want to check that `body.ref` is not empty, and it matches `"refs/heads/develop"` you could perhaps try `has(body.ref) && body.ref == "refs/heads/develop"`
