### ISSUE TITLE
Allow to define dynamic `pipelineRef`s in PipelineRuns in TriggerTemplates

### ISSUE THREAD

**Issue by ArturFortunato** [tektoncd/triggers#1486]
### Feature request

I'm looking for a way to define a single EventListener and TriggerTemplate to use for multiple repositories. But every repository has a different Pipeline.
The Pipeline name for each repository is well known, which can be retrieved from the TriggerTemplate parameters.

### Use case

Here's an example of what I'm looking for:

<img width="524" alt="image" src="https://user-images.githubusercontent.com/34646884/204790915-3912e020-581f-466a-9fe5-d8e20e225f86.png">

Notice the `$(params.repository_name) `on the `pipelineRef.name` (line 38), which is not resolved by Tekton.
Is this possible to do in a different way? 

Thank you 🙏

**Comment by khrm** [comment]
If you write `tt.params.repository_name`, it should resolve.

**Comment by ArturFortunato** [comment]
Lifesaver @khrm, thank you! 🙏 🙏
