### ISSUE TITLE
Invalid X-GitLab-Token

### ISSUE THREAD

**Issue by yuanzhilei** [tektoncd/triggers#1493]
我在熟悉tekton，创建事件监听器后从gitlab发送了一个测试事件，taskrun没有被触发。事件监听器中报错：`"msg":"interceptor stopped trigger processing: rpc error: code = InvalidArgument desc = Invalid X-GitLab-Token"`。我大概看了代码这个地方是在比较密码，但是我配置的webhook和secret中的密码是一致的。两边都改成：1234567还是会报这个错。

**Comment by savitaashture** [comment]
Hi @yuanzhilei 
Could you provide some detailed info on issue like which field is inconsistent and steps to reproduce the bug
Thanks

**Comment by yuanzhilei** [comment]
> Hi @yuanzhilei Could you provide some detailed info on issue like which field is inconsistent and steps to reproduce the bug Thanks

之前这个地方报错`Invalid X-GitLab-Token`我用nc 接收了下webhook的请求，发现接收到的Head中是X-Gitlab-Token、X-Gitlab-Token。代码中是“X-GitLab-Token”，可能并不是这里的问题。https://github.com/tektoncd/triggers/blob/b4a404dea9b6eed2bbbb15f749543c08f5fc7794/pkg/interceptors/gitlab/gitlab.go#L69 ；

**Comment by khrm** [comment]
@yuanzhilei Can you raise the pr with your modification? What should be the exact value of Header that we need?
