### ISSUE TITLE
Interceptor references without a `kind` don't get a URL set for execution

### ISSUE THREAD

**Issue by abayer** [tektoncd/triggers#1499]
# Expected Behavior

Interceptor references without a `kind` should default to being treated as `ClusterInterceptor`s and have their URL set appropriately on Triggers v0.22.0, which worked properly in v0.21.0 and earlier.

# Actual Behavior

On v0.22.0, interceptor references without a `kind` skip over the if block at https://github.com/tektoncd/triggers/blob/8797cc0e00de7864cbd6c419919d2d12d1627f05/pkg/sink/sink.go#L510-L539 and never get `url` set, causing errors to show up in the eventlistener logs like:
```
{"severity":"error","timestamp":"2022-12-20T12:50:32.302Z","logger":"eventlistener","caller":"sink/sink.go:320","message":"Post \"\": unsupported protocol scheme \"\"","eventlistener":"tekton-events","namespace":"default","/triggers-eventid":"7b12fc21-7d0b-4f86-ad11-f33a03b87231","eventlistenerUID":"b37832bb-3e30-4516-9b04-c41d626e9321","/triggers-eventid":"7b12fc21-7d0b-4f86-ad11-f33a03b87231","/triggergroup":"ci-job-triggers"}
```

# Steps to Reproduce the Problem

1. On Triggers v0.22.0, create an `EventListener` referencing an interceptor by name without specifying the `kind`.
2. Try to trigger that event listener.
3. See failures.

# Additional Info

This was encountered on Tekton's dogfooding cluster after upgrading to v0.22.0.

**Comment by abayer** [comment]
I think #1492 is likely the same root problem.

**Comment by savitaashture** [comment]
Hi @abayer i see we have added default kind as `ClusterInterceptor` here https://github.com/tektoncd/triggers/blob/release-v0.22.x/pkg/apis/triggers/v1beta1/trigger_types.go#L129-L133

And I have tried installing Triggers `v0.22.x` and installed github example and sent a curl request by following README from here https://github.com/tektoncd/triggers/tree/release-v0.22.x/examples/v1beta1/github and its working without any issues

**Comment by abayer** [comment]
I'd suggest trying to install v0.21.0, create an `EventListener`/`Trigger`/etc, and then upgrade to v0.22.0 - I'm pretty sure that the new field isn't being defaulted for existing resources, just new/updated ones.

**Comment by abayer** [comment]
Worth mentioning that we [call `SetDefaults`](https://github.com/tektoncd/pipeline/blob/330eef89148d0af26ea83b4ec58dc0155074275b/pkg/reconciler/pipelinerun/pipelinerun.go#L385) in the `PipelineRun` reconciler to deal with this sort of problem.

**Comment by abayer** [comment]
...and I see that's called in the `EventListener` reconciler too...

Ah! I think the problem is that we're using `.Spec.TriggerGroups`, and [the defaulting in `EventListener`](https://github.com/tektoncd/triggers/blob/42f8a9d452fe15273b6d4b825a1f329637098fcf/pkg/apis/triggers/v1beta1/event_listener_defaults.go#L42-L49) only covers `.Spec.Triggers`!
