### ISSUE TITLE
E2E tests failing on kind in prow?

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#1519]
@dibyom i see  failure because of 

```
    eventlistener_test.go:383: EventListener is ready
W0130 15:38:00.261492   34032 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0130 15:38:00.261610   34032 client_config.go:622] error creating inClusterConfig, falling back to default config: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
    eventlistener_test.go:484: Forwarding stream of data failed:: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

is this somehow related to https://github.com/tektoncd/triggers/issues/1515 ?

Because when i run locally i see e2e tests are passing

_Originally posted by @savitaashture in https://github.com/tektoncd/triggers/issues/1516#issuecomment-1408851452_

**Comment by dibyom** [comment]
From the logs it seems like there is something wrong in how the portforward command is setting up its kubeconfig -- not sure why it only affects when running on kind.

Will revert the plumbing change to switch back to GKE clusters for now

**Comment by dibyom** [comment]
One idea: the port forwarder seems complex - I'm not sure why we need to portforward to that specific eventlistener pod and not access it via its service like all other clients will do? That would also simplify the code quite a bit I think.

**Comment by dibyom** [comment]
(we still need to find and fix the actual root cause )

**Comment by winston0410** [comment]
Can this ticket be reopened? I am still seeing that bizzare error message from the `eventlistenersink:v0.28.0`

```sh
Error building kubeconfig: failed to create client config: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

**Comment by khrm** [comment]
I resolved this by using extra port mapping while setting up NodePort and modifying the test to use it.
