### ISSUE TITLE
slack interceptors - EventListeners removes form part of the request payload 

### ISSUE THREAD

**Issue by ilan-pinto** [tektoncd/triggers#1526]
# Expected Behavior

While working on a slack custom interceptor, I discovered that [InterceptorRequest](https://github.com/tektoncd/triggers/blob/8a1267a9f4048b18077b288ea2b8693d9d30c0cf/pkg/apis/triggers/v1beta1/interceptor_types.go#L21 ) doesn't pass [HTTP form](https://developer.mozilla.org/en-US/docs/Learn/Forms/Sending_and_retrieving_form_data) data 

given the fact that Slack "slash commands" sends form data over HTTP form. it prevents integrating Slack "slash commands" with Tekton

# Actual Behavior
event listner should not commit form and if possible transform it to json 

# Steps to Reproduce the Problem

a dummy env could be created using kind following this [repo](https://github.com/ilan-pinto/buildbot-tekton)

# Additional Info

Tekton Pipelines: v0.41.0 
Tekton Triggers: v0.22.0 
Kubernetes version v1.24.6

**Comment by dibyom** [comment]
yeah the initial design for InterceptorRequest assumed JSON body (since trigger bindings assume JSON). I think we could add a new field for passing FormData if it exists? What do you think?

**Comment by khrm** [comment]
Should we close this issue as done, @ilan-pinto ?

**Comment by ilan-pinto** [comment]
yes
