### ISSUE TITLE
Document how to expose EventListeners to the world

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#153]
A guide with all the options on exposing EventListeners:
1. Using the default Ingress
2. Using Nginx Ingress
3. Using a system like knative/eventing

**Comment by vtereso** [comment]
@dibyom Anything outstanding?

**Comment by dibyom** [comment]
Yeah the last one -- an example using knative + triggers. I think we could point to Ian's https://github.com/iancoffey/brokers-tekton
