### ISSUE TITLE
The marshalJSON function doesn't marshal lists

### ISSUE THREAD

**Issue by tgravestijn** [tektoncd/triggers#1538]
# Expected Behavior
The expected behavior is that the pipeline starts and the correct JSON information is geven as parameter to the Pipeline.
Knative sends JSON data to the EventListener pod and uses the marshalJSON function to make a string of it for the next Task.

# Actual Behavior
The actual behavior is that the Pipeline doesn't even start at all. The EventListener pod gives the following error.
```
rpc error: code = InvalidArgument desc = error evaluating cel expression: expression \"body.spec.tags.marshalJSON()\" failed to evaluate: no such overload: marshalJSON(list)"
```
But the JSON code inside the `body.spec.tags.marshalJSON()` is valid JSON (checked separately).
This means there is a issue inside the marshalJSON function that can't handle a given list, while the documentation says it can handle a list.

# Steps to Reproduce the Problem

1. Send JSON payload (from Knative in this case) to the EventListener pod
2. use 'marshalJSON()' inside TriggerTemplate to process this JSON payload
3. View logs inside the EventListener pod

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  OpenShift 4.12.0
  Kubernetes Version v1.25.4+77bec7a
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

  ```
  Client version: 0.28.0
  Pipeline version: v0.41.0
  Triggers version: v0.22.0
  Operator version: v0.63.0
  ```

Right now I made a work-around that creates a list, even while there is already a list given, so the marshalJSON function can handle this.
The current cel expression in my EventListener yaml looks like this:
```
params:
- name: overlays
  value:
  - key: imagestream-tags
    expression: "{\"tags-list\": body.spec.tags}.marshalJSON()"
```

**Comment by bigkevmcd** [comment]
Hi @tgravestijn what does your JSON look like? can you provide a small version?

I've checked, and this _seems_ to work.

**Comment by tgravestijn** [comment]
I will post the entire JSON payload.

`{"severity":"debug","timestamp":"2023-02-23T14:34:16.467Z","logger":"eventlistener","caller":"sink/sink.go:177","message":"handling event with path /, payload: {\"apiVersion\":\"image.openshift.io/v1\",\"kind\":\"ImageStream\",\"metadata\":{\"annotations\":{\"openshift.io/display-name\":\"Python\",\"openshift.io/image.dockerRepositoryCheck\":\"2023-01-15T08:22:30Z\",\"samples.operator.openshift.io/version\":\"4.12.0\"},\"creationTimestamp\":\"2023-01-15T08:22:14Z\",\"generation\":2,\"labels\":{\"samples.operator.openshift.io/managed\":\"true\"},\"managedFields\":[{\"apiVersion\":\"image.openshift.io/v1\",\"fieldsType\":\"FieldsV1\",\"fieldsV1\":{\"f:metadata\":{\"f:annotations\":{\".\":{},\"f:openshift.io/display-name\":{},\"f:samples.operator.openshift.io/version\":{}},\"f:labels\":{\".\":{},\"f:samples.operator.openshift.io/managed\":{}}},\"f:spec\":{\"f:tags\":{\".\":{},\"k:{\\\"name\\\":\\\"2.7-ubi8\\\"}\":{\".\":{},\"f:annotations\":{\".\":{},\"f:description\":{},\"f:iconClass\":{},\"f:openshift.io/display-name\":{},\"f:openshift.io/provider-display-name\":{},\"f:sampleRepo\":{},\"f:supports\":{},\"f:tags\":{},\"f:version\":{}},\"f:from\":{},\"f:generation\":{},\"f:importPolicy\":{\".\":{},\"f:importMode\":{}},\"f:name\":{},\"f:referencePolicy\":{\".\":{},\"f:type\":{}}},\"k:{\\\"name\\\":\\\"3.6-ubi8\\\"}\":{\".\":{},\"f:annotations\":{\".\":{},\"f:description\":{},\"f:iconClass\":{},\"f:openshift.io/display-name\":{},\"f:openshift.io/provider-display-name\":{},\"f:sampleRepo\":{},\"f:supports\":{},\"f:tags\":{},\"f:version\":{}},\"f:from\":{},\"f:generation\":{},\"f:importPolicy\":{\".\":{},\"f:importMode\":{}},\"f:name\":{},\"f:referencePolicy\":{\".\":{},\"f:type\":{}}},\"k:{\\\"name\\\":\\\"3.8\\\"}\":{\".\":{},\"f:annotations\":{\".\":{},\"f:description\":{},\"f:iconClass\":{},\"f:openshift.io/display-name\":{},\"f:openshift.io/provider-display-name\":{},\"f:sampleRepo\":{},\"f:supports\":{},\"f:tags\":{},\"f:version\":{}},\"f:from\":{},\"f:generation\":{},\"f:importPolicy\":{\".\":{},\"f:importMode\":{}},\"f:name\":{},\"f:referencePolicy\":{\".\":{},\"f:type\":{}}},\"k:{\\\"name\\\":\\\"3.8-ubi7\\\"}\":{\".\":{},\"f:annotations\":{\".\":{},\"f:description\":{},\"f:iconClass\":{},\"f:openshift.io/display-name\":{},\"f:openshift.io/provider-display-name\":{},\"f:sampleRepo\":{},\"f:supports\":{},\"f:tags\":{},\"f:version\":{}},\"f:from\":{},\"f:generation\":{},\"f:importPolicy\":{\".\":{},\"f:importMode\":{}},\"f:name\":{},\"f:referencePolicy\":{\".\":{},\"f:type\":{}}},\"k:{\\\"name\\\":\\\"3.8-ubi8\\\"}\":{\".\":{},\"f:annotations\":{\".\":{},\"f:description\":{},\"f:iconClass\":{},\"f:openshift.io/display-name\":{},\"f:openshift.io/provider-display-name\":{},\"f:sampleRepo\":{},\"f:supports\":{},\"f:tags\":{},\"f:version\":{}},\"f:from\":{},\"f:generation\":{},\"f:importPolicy\":{\".\":{},\"f:importMode\":{}},\"f:name\":{},\"f:referencePolicy\":{\".\":{},\"f:type\":{}}},\"k:{\\\"name\\\":\\\"3.9-ubi8\\\"}\":{\".\":{},\"f:annotations\":{\".\":{},\"f:description\":{},\"f:iconClass\":{},\"f:openshift.io/display-name\":{},\"f:openshift.io/provider-display-name\":{},\"f:sampleRepo\":{},\"f:supports\":{},\"f:tags\":{},\"f:version\":{}},\"f:from\":{},\"f:generation\":{},\"f:importPolicy\":{\".\":{},\"f:importMode\":{}},\"f:name\":{},\"f:referencePolicy\":{\".\":{},\"f:type\":{}}},\"k:{\\\"name\\\":\\\"3.9-ubi9\\\"}\":{\".\":{},\"f:annotations\":{\".\":{},\"f:description\":{},\"f:iconClass\":{},\"f:openshift.io/display-name\":{},\"f:openshift.io/provider-display-name\":{},\"f:sampleRepo\":{},\"f:supports\":{},\"f:tags\":{},\"f:version\":{}},\"f:from\":{},\"f:generation\":{},\"f:importPolicy\":{\".\":{},\"f:importMode\":{}},\"f:name\":{},\"f:referencePolicy\":{\".\":{},\"f:type\":{}}},\"k:{\\\"name\\\":\\\"latest\\\"}\":{\".\":{},\"f:annotations\":{\".\":{},\"f:description\":{},\"f:iconClass\":{},\"f:openshift.io/display-name\":{},\"f:openshift.io/provider-display-name\":{},\"f:sampleRepo\":{},\"f:supports\":{},\"f:tags\":{}},\"f:from\":{},\"f:generation\":{},\"f:importPolicy\":{\".\":{},\"f:importMode\":{}},\"f:name\":{},\"f:referencePolicy\":{\".\":{},\"f:type\":{}}}}}},\"manager\":\"cluster-samples-operator\",\"operation\":\"Update\",\"time\":\"2023-01-15T08:22:14Z\"}],\"name\":\"python\",\"namespace\":\"openshift\",\"resourceVersion\":\"152713\",\"uid\":\"f9b99681-df31-4544-86b9-45fd100f41ed\"},\"spec\":{\"lookupPolicy\":{\"local\":false},\"tags\":[{\"annotations\":{\"description\":\"Build and run Python 2.7 applications on UBI 8. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-python-container/blob/master/2.7/README.md.\",\"iconClass\":\"icon-python\",\"openshift.io/display-name\":\"Python 2.7 (UBI 8)\",\"openshift.io/provider-display-name\":\"Red Hat, Inc.\",\"sampleRepo\":\"https://github.com/sclorg/django-ex.git\",\"supports\":\"python:2.7,python\",\"tags\":\"builder,python\",\"version\":\"2.7\"},\"from\":{\"kind\":\"DockerImage\",\"name\":\"registry.redhat.io/ubi8/python-27:latest\"},\"generation\":2,\"importPolicy\":{\"importMode\":\"Legacy\"},\"name\":\"2.7-ubi8\",\"referencePolicy\":{\"type\":\"Local\"}},{\"annotations\":{\"description\":\"Build and run Python 3.6 applications on UBI 8. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-python-container/blob/master/3.6/README.md.\",\"iconClass\":\"icon-python\",\"openshift.io/display-name\":\"Python 3.6 (UBI 8)\",\"openshift.io/provider-display-name\":\"Red Hat, Inc.\",\"sampleRepo\":\"https://github.com/sclorg/django-ex.git\",\"supports\":\"python:3.6,python\",\"tags\":\"builder,python\",\"version\":\"3.6\"},\"from\":{\"kind\":\"DockerImage\",\"name\":\"registry.redhat.io/ubi8/python-36:latest\"},\"generation\":2,\"importPolicy\":{\"importMode\":\"Legacy\"},\"name\":\"3.6-ubi8\",\"referencePolicy\":{\"type\":\"Local\"}},{\"annotations\":{\"description\":\"Build and run Python 3.8 applications on RHEL 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-python-container/blob/master/3.8/README.md.\",\"iconClass\":\"icon-python\",\"openshift.io/display-name\":\"Python 3.8\",\"openshift.io/provider-display-name\":\"Red Hat, Inc.\",\"sampleRepo\":\"https://github.com/sclorg/django-ex.git\",\"supports\":\"python:3.8,python\",\"tags\":\"builder,python,hidden\",\"version\":\"3.8\"},\"from\":{\"kind\":\"DockerImage\",\"name\":\"registry.redhat.io/rhscl/python-38-rhel7:latest\"},\"generation\":2,\"importPolicy\":{\"importMode\":\"Legacy\"},\"name\":\"3.8\",\"referencePolicy\":{\"type\":\"Local\"}},{\"annotations\":{\"description\":\"Build and run Python 3.8 applications on UBI 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-python-container/blob/master/3.8/README.md.\",\"iconClass\":\"icon-python\",\"openshift.io/display-name\":\"Python 3.8 (UBI 7)\",\"openshift.io/provider-display-name\":\"Red Hat, Inc.\",\"sampleRepo\":\"https://github.com/sclorg/django-ex.git\",\"supports\":\"python:3.8,python\",\"tags\":\"builder,python\",\"version\":\"3.8\"},\"from\":{\"kind\":\"DockerImage\",\"name\":\"registry.redhat.io/ubi7/python-38:latest\"},\"generation\":2,\"importPolicy\":{\"importMode\":\"Legacy\"},\"name\":\"3.8-ubi7\",\"referencePolicy\":{\"type\":\"Local\"}},{\"annotations\":{\"description\":\"Build and run Python 3.8 applications on UBI 8. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-python-container/blob/master/3.8/README.md.\",\"iconClass\":\"icon-python\",\"openshift.io/display-name\":\"Python 3.8 (UBI 8)\",\"openshift.io/provider-display-name\":\"Red Hat, Inc.\",\"sampleRepo\":\"https://github.com/sclorg/django-ex.git\",\"supports\":\"python:3.8,python\",\"tags\":\"builder,python\",\"version\":\"3.8\"},\"from\":{\"kind\":\"DockerImage\",\"name\":\"registry.redhat.io/ubi8/python-38:latest\"},\"generation\":2,\"importPolicy\":{\"importMode\":\"Legacy\"},\"name\":\"3.8-ubi8\",\"referencePolicy\":{\"type\":\"Local\"}},{\"annotations\":{\"description\":\"Build and run Python 3.9 applications on UBI 8. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-python-container/blob/master/3.9/README.md.\",\"iconClass\":\"icon-python\",\"openshift.io/display-name\":\"Python 3.9 (UBI 8)\",\"openshift.io/provider-display-name\":\"Red Hat, Inc.\",\"sampleRepo\":\"https://github.com/sclorg/django-ex.git\",\"supports\":\"python:3.9,python\",\"tags\":\"builder,python\",\"version\":\"3.9\"},\"from\":{\"kind\":\"DockerImage\",\"name\":\"registry.redhat.io/ubi8/python-39:latest\"},\"generation\":2,\"importPolicy\":{\"importMode\":\"Legacy\"},\"name\":\"3.9-ubi8\",\"referencePolicy\":{\"type\":\"Local\"}},{\"annotations\":{\"description\":\"Build and run Python 3.9 applications on UBI 9. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-python-container/blob/master/3.9/README.md.\",\"iconClass\":\"icon-python\",\"openshift.io/display-name\":\"Python 3.9 (UBI 9)\",\"openshift.io/provider-display-name\":\"Red Hat, Inc.\",\"sampleRepo\":\"https://github.com/sclorg/django-ex.git\",\"supports\":\"python:3.9,python\",\"tags\":\"builder,python\",\"version\":\"3.9\"},\"from\":{\"kind\":\"DockerImage\",\"name\":\"registry.redhat.io/ubi9/python-39:latest\"},\"generation\":2,\"importPolicy\":{\"importMode\":\"Legacy\"},\"name\":\"3.9-ubi9\",\"referencePolicy\":{\"type\":\"Local\"}},{\"annotations\":{\"description\":\"Build and run Python applications on UBI. For more information about using this builder image, including OpenShift considerations, see https://github.com/sclorg/s2i-python-container/blob/master/3.9/README.md.\\n\\nWARNING: By selecting this tag, your application will automatically update to use the latest version of Python available on OpenShift, including major version updates.\",\"iconClass\":\"icon-python\",\"openshift.io/display-name\":\"Python (Latest)\",\"openshift.io/provider-display-name\":\"Red Hat, Inc.\",\"sampleRepo\":\"https://github.com/sclorg/django-ex.git\",\"supports\":\"python\",\"tags\":\"builder,python\"},\"from\":{\"kind\":\"ImageStreamTag\",\"name\":\"3.9-ubi8\"},\"generation\":1,\"importPolicy\":{\"importMode\":\"Legacy\"},\"name\":\"latest\",\"referencePolicy\":{\"type\":\"Local\"}}]},\"status\":{\"dockerImageRepository\":\"image-registry.openshift-image-registry.svc:5000/openshift/python\",\"publicDockerImageRepository\":\"default-route-openshift-image-registry.apps-crc.testing/openshift/python\",\"tags\":[{\"items\":[{\"created\":\"2023-01-15T08:22:30Z\",\"dockerImageReference\":\"registry.redhat.io/ubi8/python-27@sha256:6974774fc16fa0472c49fa16264f7895c6dc4bdc291a4a00c62c2a1739627bba\",\"generation\":2,\"image\":\"sha256:6974774fc16fa0472c49fa16264f7895c6dc4bdc291a4a00c62c2a1739627bba\"}],\"tag\":\"2.7-ubi8\"},{\"items\":[{\"created\":\"2023-01-15T08:22:30Z\",\"dockerImageReference\":\"registry.redhat.io/ubi8/python-36@sha256:80fc3870bec32f6717f32ced5c2aa5457f7e569eb75c1c2877e4a106bfecb0d7\",\"generation\":2,\"image\":\"sha256:80fc3870bec32f6717f32ced5c2aa5457f7e569eb75c1c2877e4a106bfecb0d7\"}],\"tag\":\"3.6-ubi8\"},{\"items\":[{\"created\":\"2023-01-15T08:22:30Z\",\"dockerImageReference\":\"registry.redhat.io/rhscl/python-38-rhel7@sha256:f8586d5abc2b3bf7153dad087daaa4f1cda95fc7c72ff130bef755791d8e1239\",\"generation\":2,\"image\":\"sha256:f8586d5abc2b3bf7153dad087daaa4f1cda95fc7c72ff130bef755791d8e1239\"}],\"tag\":\"3.8\"},{\"items\":[{\"created\":\"2023-01-15T08:22:30Z\",\"dockerImageReference\":\"registry.redhat.io/ubi7/python-38@sha256:f8586d5abc2b3bf7153dad087daaa4f1cda95fc7c72ff130bef755791d8e1239\",\"generation\":2,\"image\":\"sha256:f8586d5abc2b3bf7153dad087daaa4f1cda95fc7c72ff130bef755791d8e1239\"}],\"tag\":\"3.8-ubi7\"},{\"items\":[{\"created\":\"2023-01-15T08:22:30Z\",\"dockerImageReference\":\"registry.redhat.io/ubi8/python-38@sha256:08a7d00fcf6b8d8a0fa2e79f4920a692ce21d1b77b505ffd59ce2b8bc71f9789\",\"generation\":2,\"image\":\"sha256:08a7d00fcf6b8d8a0fa2e79f4920a692ce21d1b77b505ffd59ce2b8bc71f9789\"}],\"tag\":\"3.8-ubi8\"},{\"items\":[{\"created\":\"2023-01-15T08:22:30Z\",\"dockerImageReference\":\"registry.redhat.io/ubi8/python-39@sha256:9e5f0096476f35dcf037bf3fd7fccb73a97331e67d995f64bbcd16ecc2317f36\",\"generation\":2,\"image\":\"sha256:9e5f0096476f35dcf037bf3fd7fccb73a97331e67d995f64bbcd16ecc2317f36\"}],\"tag\":\"3.9-ubi8\"},{\"items\":[{\"created\":\"2023-01-15T08:22:30Z\",\"dockerImageReference\":\"registry.redhat.io/ubi9/python-39@sha256:fe5e61df902bd607b3935f21b1e746d15f1ac3c176f4f91d203c2798df923b1a\",\"generation\":2,\"image\":\"sha256:fe5e61df902bd607b3935f21b1e746d15f1ac3c176f4f91d203c2798df923b1a\"}],\"tag\":\"3.9-ubi9\"},{\"items\":[{\"created\":\"2023-01-15T08:22:30Z\",\"dockerImageReference\":\"registry.redhat.io/ubi8/python-39@sha256:9e5f0096476f35dcf037bf3fd7fccb73a97331e67d995f64bbcd16ecc2317f36\",\"generation\":2,\"image\":\"sha256:9e5f0096476f35dcf037bf3fd7fccb73a97331e67d995f64bbcd16ecc2317f36\"}],\"tag\":\"latest\"}]}} and header: map[Accept-Encoding:[gzip] Ce-Id:[268812c8-1a58-456e-bc8a-5140e4e3c32a] Ce-Kind:[ImageStream] Ce-Name:[python] Ce-Namespace:[openshift] Ce-Source:[https://10.217.4.1:443] Ce-Specversion:[1.0] Ce-Subject:[/apis/image.openshift.io/v1/namespaces/openshift/imagestreams/python] Ce-Time:[2023-02-23T14:34:16.269574669Z] Ce-Type:[dev.knative.apiserver.resource.update] Content-Length:[11956] Content-Type:[application/json] Traceparent:[00-fe5d05d27ef3b9460ca78ca0a1200993-2261d585e053f5d7-00] User-Agent:[Go-http-client/1.1]]","commit":"b4a404d","eventlistener":"image-eventlistener","namespace":"tooling","/triggers-eventid":"4a7d21b6-4937-4242-97c7-f9e37bc876e8","eventlistenerUID":"81068478-5ef0-4394-a9e1-6846b340e4d4","/triggers-eventid":"4a7d21b6-4937-4242-97c7-f9e37bc876e8"}`
