### ISSUE TITLE
`githubOwners`  not creating pipelinerun/taskrun when the owner creates a pull request from different branch

### ISSUE THREAD

**Issue by VeereshAradhya** [tektoncd/triggers#1571]
# Expected Behavior
`githubOwners`  should create pipelinerun/taskrun when the owner creates a pull request from a different branch

# Actual Behavior
`githubOwners`  not creating pipelinerun/taskrun when owner creates a pull request from different branch

# Steps to Reproduce the Problem

1. Create a new repository in github and do not add OWNERS file
2. Create an eventlistener that uses github interceptor with `githubOwners` param
3. Add webhook to the repository
4. Create a pull request to main from different branch

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: v1.25.7
  Kustomize Version: v4.5.7
  Server Version: v1.24.11+af0420d
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
  ```
  tkn version                                                                                            ✔  10:57:12 AM 
  Client version: 0.30.0
  Pipeline version: v0.44.0
  Triggers version: v0.23.0
  Operator version: v0.65.1
  ```

**Comment by nagasree9** [comment]
@VeereshAradhya Could you also share the values you have set for `githubOwners` param

**Comment by VeereshAradhya** [comment]
```
- name: "githubOwners"
              value: 
                enabled: true
                checkType: none
```

**Comment by nagasree9** [comment]
I would say set the `checkType` value to `repoMembers` and also passin the `PersonalAccessToken` to make api calls into the repository

**Comment by VeereshAradhya** [comment]
Pipelinerun is getting created after setting `checkType` to `repoMembers`. So, the feature is working as expected. Shall I close the bug?

**Comment by savitaashture** [comment]
@VeereshAradhya Yes you can close the bug

**Comment by VeereshAradhya** [comment]
Marking the bug as closed as the test data that I used to test was not correct.
