### ISSUE TITLE
Make all cel extensions available

### ISSUE THREAD

**Issue by khrm** [tektoncd/triggers#1612]
### Feature request

The documentation (https://tekton.dev/docs/triggers/cel_expressions/#cel-go-extensions) says that all extensions at https://github.com/google/cel-go/tree/master/ext are available for use.
@ggallen tried to use sets.contains without luck.

**Comment by TristonianJones** [comment]
@khrm if you bump to cel-go v0.17.1 (released yesterday) there are also some additional validation features and support for list slices.

**Comment by khrm** [comment]
@TristonianJones Thanks. Sure will update to cel-go v0.17.1
