### ISSUE TITLE
Content-Type isn't send to Interceptor

### ISSUE THREAD

**Issue by khrm** [tektoncd/triggers#1614]
# Expected Behavior

`Content-Type` should be sent to Interceptor when making a POST request.
Some of web frameworks in other languages expect this header.

# Actual Behavior
At present, when making a POST request to the interceptor, we don't set `Content-Type` header.

**Comment by khrm** [comment]
@ ggallen Do we need this? How did you solve this? Was there some issue in the interceptor that you have written?

**Comment by khrm** [comment]
@ggallen Do we need this? How did you solve this? Was there some issue with the interceptor that you have written?

**Comment by ggallen** [comment]
Yes, this is an actual bug. To work around it we have a filter that is adding the required header.
