### ISSUE TITLE
Knative undefined: injection.Dynamic

### ISSUE THREAD

**Issue by mike-sirs** [tektoncd/triggers#1628]
Knative dropped dynamic wrapped client generation

it results in a compile error
`triggers@v0.24.1/pkg/client/injection/client/client.go:51:12: undefined: injection.Dynamic`

# Steps to Reproduce the Problem
update to knative.dev/pkg v0.0.0-20230815132840-4f651e092853

related issue

https://github.com/knative/pkg/issues/2739

**Comment by khrm** [comment]
@mike-sirs Didn't we remove it here? https://github.com/tektoncd/triggers/commit/c366270ccd9c6ad118eec4ff791cb360bdbf492f

**Comment by khrm** [comment]
We will do a v0.25 next week or week after next.

**Comment by mike-serchenia** [comment]
[like]  Michael Serchenia reacted to your message:
________________________________

**Comment by mike-serchenia** [comment]
[0]     Michael Serchenia reacted to your message:
________________________________

**Comment by mike-sirs** [comment]
@khrm the issues still persist, the PR you've mentioned removed `Dynamic` from `eventlistenersink/main.go`
while the problem is with  
https://github.com/tektoncd/triggers/blob/cc1b7b73f165e9480f0cd92ac0b0f36e0f0be3e0/pkg/client/injection/client/client.go#L51C2-L51C64

```
/go/pkg/mod/github.com/tektoncd/triggers@v0.25.0/pkg/client/injection/client/client.go:51:12: undefined: injection.Dynamic

go.mod:
	github.com/tektoncd/pipeline v0.50.1
	github.com/tektoncd/triggers v0.25.0
        knative.dev/pkg v0.0.0-20230718152110-aef227e72ead
```

could someone look at this, please?
