### ISSUE TITLE
Knative undefined: injection.Dynamic 

### ISSUE THREAD

**Issue by mike-sirs** [tektoncd/triggers#1639]
Knative dropped dynamic wrapped client generation

closed issue https://github.com/tektoncd/triggers/issues/1628

@khrm the issues still persist, the PR you've mentioned removed `Dynamic` from `eventlistenersink/main.go`
while the problem is with  
https://github.com/tektoncd/triggers/blob/cc1b7b73f165e9480f0cd92ac0b0f36e0f0be3e0/pkg/client/injection/client/client.go#L51C2-L51C64

```
/go/pkg/mod/github.com/tektoncd/triggers@v0.25.0/pkg/client/injection/client/client.go:51:12: undefined: injection.Dynamic

go.mod:
	github.com/tektoncd/pipeline v0.50.1
	github.com/tektoncd/triggers v0.25.0
        knative.dev/pkg v0.0.0-20230718152110-aef227e72ead
```

could someone look at this, please?

https://github.com/knative/pkg/issues/2739

**Comment by khrm** [comment]
Sure, I would remove this.

**Comment by khrm** [comment]
@mike-sirs Can you pick this up?

**Comment by mike-sirs** [comment]
@khrm https://github.com/tektoncd/triggers/pull/1687

**Comment by khrm** [comment]
@mike-sirs This is done now. Should be part of the next release.
