### ISSUE TITLE
Enable Triggers to create custom non-Tekton resources

### ISSUE THREAD

**Issue by GijsvanDulmen** [tektoncd/triggers#1696]
### Feature request

It would be great if it was configurable for Tekton Triggers to create custom resources instead of only Tekton resources.
I understand it's not useful for everybody and maybe shouldn't be the default, but in a lot of use cases it does improves the plugin nature of Tekton Triggers.

### Use case
In our case we wanted to use K8qu to create a "Queued" PipelineRun. This involves creating a custom QueueJob resource which creates the PipelineRun. But in other use cases I can imagine you sometimes also want to create K8s Jobs to trigger based on something sent into the EventListener.

**Comment by savitaashture** [comment]
WG discussion:

During call we discussed that we can enable this feature and creation of resources can be enabled based on the SA permissions

**Comment by savitaashture** [comment]
Hi @GijsvanDulmen 
Definitely would you like to contribute ?
