### ISSUE TITLE
Add more cel extensions

### ISSUE THREAD

**Issue by venc0r** [tektoncd/triggers#1717]
### Feature request

the docs say the cel interceptor should support all extensions
> All the functionality from the cel-go project’s [CEL extension](https://github.com/google/cel-go/tree/master/ext) is available in your CEL expressions.

Over the last months there are new extensions added to cel, but not enabled in the cel-eval interceptor.

### Use case

I want to get a slice of an array like: `[1,2,3,4].slice(1,3)` => `[2,3]`

**Comment by khrm** [comment]
@venc0r Won't a update to the latest library fix this? https://github.com/tektoncd/triggers/pull/1718

**Comment by khrm** [comment]
It will be fixed by #1730
