### ISSUE TITLE
Why not to specify TriggerTemplate as resource type?

### ISSUE THREAD

**Issue by dancer1325** [tektoncd/triggers#1726]
# Expected Behavior
Specify clearly that 'TriggerTemplate' is a resource under the package 'triggers.tekton.dev/v1beta1', since it's a standalone CR

> Resource Types:
> [ClusterTriggerBinding](https://tekton.dev/docs/triggers/triggers-api/#triggers.tekton.dev/v1beta1.ClusterTriggerBinding)
> [EventListener](https://tekton.dev/docs/triggers/triggers-api/#triggers.tekton.dev/v1beta1.EventListener)
> [Trigger](https://tekton.dev/docs/triggers/triggers-api/#triggers.tekton.dev/v1beta1.Trigger)
> [TriggerBinding](https://tekton.dev/docs/triggers/triggers-api/#triggers.tekton.dev/v1beta1.TriggerBinding)
> [TriggerTemplate](https://tekton.dev/docs/triggers/triggers-api/#triggers.tekton.dev/v1beta1.TriggerTemplate)

# Actual Behavior
'TriggerTemplate' is NOT specified clearly as a CR

> Resource Types:
> [ClusterTriggerBinding](https://tekton.dev/docs/triggers/triggers-api/#triggers.tekton.dev/v1beta1.ClusterTriggerBinding)
> [EventListener](https://tekton.dev/docs/triggers/triggers-api/#triggers.tekton.dev/v1beta1.EventListener)
> [Trigger](https://tekton.dev/docs/triggers/triggers-api/#triggers.tekton.dev/v1beta1.Trigger)
> [TriggerBinding](https://tekton.dev/docs/triggers/triggers-api/#triggers.tekton.dev/v1beta1.TriggerBinding)

# Steps to Reproduce the Problem

1. Navigate to https://tekton.dev/docs/triggers/triggers-api/#triggers.tekton.dev/v1beta1

# Additional Info
* I know that the markdown is in https://github.com/tektoncd/triggers/blob/main/docs/triggers-api.md#triggers.tekton.dev%2fv1beta1, but not sure if that was the right place to report it

**Comment by dibyom** [comment]
cc @khrm @savitaashture - this looks like a missing tag somewhere?

**Comment by khrm** [comment]
The Tag was there. Not sure why it requires a new line before it. 
https://github.com/tektoncd/triggers/pull/1727/files#diff-b298db60f09e46c7935921f4e629ae4066da95202fccdfb1fd42b11b4ede776f
