### ISSUE TITLE
The EventListener running in HTTPS still offers TLS 1.0, and 1.1

### ISSUE THREAD

**Issue by arturdzm** [tektoncd/triggers#1779]
### Feature request

The EventListener server HTTPS mode still offers TLS 1.0, and 1.1 and should be set to min version of 1.2
Or at least it should be made configurable.

https://github.com/tektoncd/triggers/blob/c6d2a8dfae9dea34cc05b37489c04bb6554a15b7/pkg/adapter/adapter.go#L256

**Comment by bigkevmcd** [comment]
This should be handled by Go automatically [since 1.22](https://github.com/tektoncd/triggers/commit/0cb388614c020034bee0e2e9edd649e8a9bf98ce).

> By default, the minimum version offered by crypto/tls servers is now TLS 1.2 if not specified with [config.MinimumVersion](https://tip.golang.org/pkg/crypto/tls#Config.MinimumVersion), matching the behavior of crypto/tls clients. This change can be reverted with the tls10server=1 GODEBUG setting.

@arturdzm What version are you running?

**Comment by arturdzm** [comment]
Thank you, for pointing to go version. Looks like the version of Tekton triggers is 0.26 which is still on Go 1.19. Will need to upgrade
