### ISSUE TITLE
Fragile object creation order issues

### ISSUE THREAD

**Issue by kav** [tektoncd/triggers#187]
# Expected Behavior
EventListeners, TriggerBindings, and TriggerTemplates can be installed by a helm chart, flux, jenkinsx gitops or other process that does not allow users to specify object creation order. In the event an object can not function, e.g. an event listener referencing a non-existing template, that object should report status rather than refusing to install.

# Actual Behavior
EventListeners, TriggerBindings, and TriggerTemplates must be created in a specific order to prevent validation errors.

# Steps to Reproduce the Problem
1. Create an EventListener, TriggerBinding, and TriggerTemplate json files
2. Install the EventListener first

## Alternatively
1. create a helm chart that contains an EventListener, TriggerBinding, and TriggerTemplate
2. attempt to install your chart

# Additional Info
Note in helm installs objects in a standardized order that can not be controlled via naming, sorting, position in file, etc. post install hook seemed fruitful but ultimately don't work. See the below issue for history and motivation:
https://github.com/helm/helm/issues/1228

**Comment by dibyom** [comment]
Fixed in #263 
/close
