### ISSUE TITLE
Handle arbitrary event payloads

### ISSUE THREAD

**Issue by vtereso** [tektoncd/triggers#19]
# Expected Behavior
The main strength of `tektoncd/triggers`, and more specifically, a `triggerBinding` is that it will act as the glue enabling you to extract fields of an event payload to be used in a `triggerTemplate` to create arbitrary resources. 

# Current Behavior
We don't have anything for this

# Background
Since events can have any structure, we will not always have a definition for the struct to unmarshal into as done prior [here](https://github.com/tektoncd/experimental/blob/master/tekton-listener/cmd/tekton-listener/main.go#L155). Further, likely only a few of the many fields will be utilized within a `triggerTemplate` where unmarshalling the entire structure will be costly/wasteful. 

# Ideas
- Have a code gen step that will inject the library and specific type into the `triggerBinding` pods/listeners AOT, but this seems unnecessary, costly (as mentioned previous) and in conflict with the idea of having a dynamic solution. 
- I made a quick prototype using the internal `encoding/json` library and `map[string]interface{}`, but there are some tools out there (https://github.com/tidwall/gjson seems like a good option) that are much more performant.

**Comment by vincent-pli** [comment]
Could we use `reflect`

**Comment by bobcatfish** [comment]
> Could we use `reflect`

With the caveat that this is something I've heard other people say, and not something I've really experimented with myself, I'm under the impression that using reflection has a significant performance impact. (That and code that uses reflection can be a little confusing to follow!)

**Comment by vtereso** [comment]
> I made a quick prototype using the internal encoding/json library and map[string]interface{}
This is the approach using reflect, but as mentioned, there is a considerable performance impact.

**Comment by bobcatfish** [comment]
Another way to tackle this would be to initially target only creation of `PipelineResources` and `PipelineRuns`, which would reduce the scope required a bit and we could add support for arbitrary resources later (but if we can get it all at once then great!)

**Comment by vtereso** [comment]
> Another way to tackle this would be to initially target only creation of `PipelineResources` and `PipelineRuns`, which would reduce the scope required a bit and we could add support for arbitrary resources later (but if we can get it all at once then great!)

I understood this work item to just be the event side extraction only, which be the logic to set `TriggerBinding` params

**Comment by bobcatfish** [comment]
> I understood this work item to just be the event side extraction only, which be the logic to set TriggerBinding params

Oh good call! My bad, I didn't read it fully and assumed it was about specifying arbitrary templates in the Template - just ignore me 😅
