### ISSUE TITLE
Question: Multiple triggers, listeners

### ISSUE THREAD

**Issue by adjavaherian** [tektoncd/triggers#199]
So, Without any sort of conditionals in the trigger templates, what is the current recommendation for assigning different pipelines to different event types?

For example, on PRs, I want to have a full build => deploy pipeline for a preview environment.
But for a commit to a dev branch, I simply want to build an artifact (to be deployed in a separate process).

Do you all do this with multiple triggers now?  This seems to be overkill, considering that each trigger requires an ingress and listener and hook too.  Any suggestions?

**Comment by dibyom** [comment]
Filters should be in the upcoming 0.2 release. Until then, the workaround would be to use a interceptor as @ncskier mentioned.
