### ISSUE TITLE
unknown field "bindings" when creating the getting-started example

### ISSUE THREAD

**Issue by daniyalj** [tektoncd/triggers#222]
# Expected Behavior

When creating the `triggers.yaml` an EventListener is created

# Actual Behavior

After changing the `DOCKERREPO-REPLACEME` variable run: 
```
kubectl apply -f ./docs/getting-started/triggers.yaml
triggertemplate.tekton.dev/getting-started-triggertemplate created
triggerbinding.tekton.dev/getting-started-pipelinebinding created
Error from server (InternalError): error when creating "listener.yaml": Internal error occurred: admission webhook "triggers-webhook.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "bindings"
```

# Steps to Reproduce the Problem

1. Following the getting started guide [here](https://github.com/tektoncd/triggers/tree/master/docs/getting-started#getting-started-with-triggers)
2. Deploy triggers.yaml

# Additional Info
Environment details: GKE version 1.13.11-gke.9

**Comment by dibyom** [comment]
hi @daniyalj ...sorry for the trouble...the getting started guide you are following is from the master branch which has some backwards incompatible changes (e.g. bindings vs binding) from the currently released version. 
You could try following the getting started guide for the installed branch instead: https://github.com/tektoncd/triggers/tree/v0.1.0/docs/getting-started#getting-started-with-triggers

**Comment by daniyalj** [comment]
thanks for the quick reply @dibyom `binding` worked for me
