### ISSUE TITLE
Patch kubernetes objects from trigger templates

### ISSUE THREAD

**Issue by sbose78** [tektoncd/triggers#231]
In addition to supporting creation of new kubernetes objects in a Trigger Template, could we support 'patching' of an existing object as well ?

**Comment by vdemeester** [comment]
@sbose78 you mean "Additionally" instead of "Instead" right ? :sweat_smile: 

/kind question
/kind feature

**Comment by sbose78** [comment]
I meant, "instead of ONLY" :P but I will fix the description.

**Comment by sbose78** [comment]
My ambitious use case is: 

I wish to store the Pipeline definition yamls in a Github repo, and when a new changes to the same is merged changes, I would the webhook to trigger the following:

1. Patch the Pipeline definition, followed by:
2. Create a new PipelineRun

**Comment by bobcatfish** [comment]
Oh interesting @sbose78 ! (ps are you in the triggers WG meeting right now or was this a coincidence?? haha :D )

So is this pretty much just the difference b/w a `kubectl apply` vs a `kubectl create`?

Another option: you could have a Pipeline that applies the new Pipeline definition, vs. creating it in Triggers?

**Comment by sbose78** [comment]
> Another option: you could have a Pipeline that applies the new Pipeline definition, vs. creating it in Triggers?

Correct, that's an option! 

> So is this pretty much just the difference b/w a kubectl apply vs a kubectl create?

Correct ;)

> Oh interesting @sbose78 ! (ps are you in the triggers WG meeting right now or was this a coincidence?? haha :D )

Haha! I wanted to join, but had a conflict, Kevin pinged me about it :)
