### ISSUE TITLE
Add nightly releases?

### ISSUE THREAD

**Issue by ston1th** [tektoncd/triggers#237]
Hello tekton team,

I would like to propose nightly releases based on the `master` branch, to be able to test out new features more easily.

Currently the latest container image is `v0.1.0`.

What do you guys think?

**Comment by vdemeester** [comment]
We are already doing that for `tektoncd/pipeline` so it shouldn't be hard to automate for `triggers`. I can take a look if needed (soon-ish).

/kind feature
/cc @dibyom

**Comment by bobcatfish** [comment]
@wlynch "volunteered" to take a shot at this as well! in the interests of some dogfooding 🐶 (and @vdemeester not having to do everything haha)

@ston1th do you have any requirements timeline-wise? I think we're assuming that it's fine if it's within the next few weeks?

**Comment by ston1th** [comment]
@bobcatfish no not really - the next few weeks are fine :+1: 

In the meantime I'll just build stuff myself.

**Comment by dibyom** [comment]
NIghtly releases have been around for a while now!

/close
