### ISSUE TITLE
Support multiple interceptors

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#249]
# Expected Behavior

A trigger can specify multiple interceptors. 

# Actual Behavior

A trigger can only have a single interceptor.

# Additional Info

Would be needed if we go with Option 3 from the [Filters design doc](https://docs.google.com/document/d/1c-cGLdRb4LuH2_rUn50cIhHPabAoj4iQvw49L4T2nSU/edit#) (#49)

**Comment by wlynch** [comment]
I'm happy to pick this up.

/assign wlynch

**Comment by dibyom** [comment]
Adding this to 0.2 Milestone since this will be needed for Filters as Interceptors approach from https://github.com/tektoncd/triggers/issues/49#issuecomment-561350595
