### ISSUE TITLE
K8S-styled templating - remove triggers' XYZTemplates, template types, template definitions, and variable interpolations from trigger controllers and triggers API

### ISSUE THREAD

**Issue by xihaLong** [tektoncd/triggers#25]
Tekton going forward, as of last week's working group meeting, is following the template style of K8S, which can be interpreted as specifically avoiding a few things. https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/declarative-application-management.md#what-about-parameterization

2/3rds of that K8S document applies directly to how Tekton will want to pursue templates and reuse of items. I am trying to find exceptions to the rules I have found in that document, though I have none currently. Everything that can be expressed with a template within our API/controller could instead be pre-processed outside of Tekton's view and applied as API calls to Tekton.

In fact, if following a couple of the models for apply -f/ apply -k/ and merging YAML/JSON in a way transparent to K8S, there is a chance to additionally unroll patches and recover original values if desired - though that is not going to be required for now.

Where am I going with this?

Tekton will avoid templating most forms of variable interpolation at the API layer for Tekton.

This will also mean avoiding creating any objects named "XYZTemplate" and/or "XYZTemplateType" in favor of allowing external tools to be chosen by a developer for generating the API calls/YAML/JSON files.

I propose any templating options be pushed to a CLI wrapper layer that makes the user experience for Tekton nicer, though leaves the controllers and API simpler for Tekton itself.

So, I think I am not going too far out there to state: Let us not add too many intelligent forms of template logic into the controllers.

It may be argued that Pipelines and PipelineRuns also follow a similar template logic (PipelineRun is just providing a patch of values over the Pipeline template), though that is a discussion for the pipeline team rather than for Triggers.

It follows to me that Tekton can be simpler and still achieve its goals. What to consider for removal? Anything performing variable interpolation/variable substitution that the user could have provided directly instead. Additionally, most other items that might be interpolated can potentially be generated and turned into a full API call/fully filled out YAML/filled out JSON. If not, then the extra state can be considered exposed via ConfigMap, Secret, or creating a resource/file/envvar for ingestion further along (each with different implications for debugging). I am not 100% sure how we might emulate or reuse the DownwardAPIVolumeFiles variant of handing information along, though it is also a pattern to consider from K8S.

I will first refer to https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/declarative-application-management.md for consideration

https://docs.google.com/document/d/1h_3vSApIsuiwGkrqSiegi4NVaYG4oVzBquGAhIN6qGM

**Comment by xihaLong** [comment]
https://github.com/tektoncd/triggers/blob/master/config/300-triggertemplate.yaml As a simple edit, I will remove this file in a pull request. This suggestion is open for comments
Will of course also impact https://github.com/tektoncd/triggers/blob/master/pkg/apis/triggers/v1alpha1/trigger_template_types.go among other locations, though those can come in other pull requests

If Triggers wants to make its own templating decisions independent of Tekton's overall decisions on templating, that may also be discussed in this context

Better to ask and decide on this now, while the API is still in alpha and many parts are not-yet-implemented

**Comment by xihaLong** [comment]
https://github.com/tektoncd/pipeline/issues/850

**Comment by dlorenc** [comment]
Hey! Thanks for opening this. I think the discussion last week you're citing here has a few impacts on the rest of the project, and we especially need to think carefully through how to apply these rules to the triggering project here.



> Tekton will avoid templating most forms of variable interpolation at the API layer for Tekton.

I agree here. Where possible interpolation should happen before calling the API. Some notable exceptions in k8s already exist though. Here is one: https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/#using-environment-variables-inside-of-your-config



> This will also mean avoiding creating any objects named "XYZTemplate" and/or "XYZTemplateType" in favor of allowing external tools to be chosen by a developer for generating the API calls/YAML/JSON files.

I don't think this is quite accurate, and `Template` is unfortunately an overloaded name. See the way `PodTemplate`s are exposed in k8s Deployment objects for a case where `Template` is being used correctly by the core k8s system: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

I think that's the logical equivalent of what we're trying to do in Triggers. Provide a declarative mechanism for a Trigger to create a Resource on demand, similar to the way a Deployment can create a Pod on demand.

> So, I think I am not going too far out there to state: Let us not add too many intelligent forms of template logic into the controllers.

+1 to this!

**Comment by xihaLong** [comment]
affects pipelines and triggers https://docs.google.com/document/d/11QWLYPP-yj_K_ghQqHr3LFonFE9bfHwtooYq6qPhn8w Less Template, More Tekton

**Comment by xihaLong** [comment]
@dlorenc Let's consider to not publicly publish a mechanism for cookie-cutting from a set of intermediate template resources, even if similar mechanisms are used internally or encouraged externally such as in a git repository or using a template publishing tool. I saw fairly convincing arguments in the "Declarative Application Management" document https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/declarative-application-management.md I prefer doing less where possible, and this document outlines methods appealing to that side of me

**Comment by dlorenc** [comment]
I'm pretty familiar with that document, but I'm not sure I follow how we would address the same use cases without having a mechanism to create resources when an event is triggered. 

Could you explain more? I'm hesitant to remove any of these features until we fully understand the replacements.

**Comment by bobcatfish** [comment]
As mentioned in https://github.com/tektoncd/triggers/pull/26#issuecomment-512532701 and https://github.com/tektoncd/triggers/pull/24#issuecomment-513025973 I'm hoping we can reduce the number of places we are discussing completely removing our templating & template types so I'd like to close this issue for now.
