### ISSUE TITLE
TriggerTemplate params work without the spec.params field

### ISSUE THREAD

**Issue by ncskier** [tektoncd/triggers#255]
# Expected Behavior
I expect that when my TriggerTemplate does not have the `spec.params` field, the resource template parameter substitution will not work.

# Actual Behavior
When I do not specify the `spec.params` field, parameter substitution still appears to work. [Here](https://github.com/pipeline-hotel/example-pipelines/blob/master/triggers-resources/config/simple-pipeline/simple-pipeline-template.yaml) is an example of a TriggerTemplate that works without its `spec.params` field.

# Steps to Reproduce the Problem

1. Delete all the parameters from one of your TriggerTemplates (delete the entire `spec.params` field)
2. Use the TriggerTemplate like you normally would

**Comment by dibyom** [comment]
Looks like we need to add some validation for the templates?

**Comment by dibyom** [comment]
cc @bigkevmcd in case you are looking to pick up any issues :stuck_out_tongue:
