### ISSUE TITLE
Inconsistent types for Header values extracted from bindings 

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#260]
If I use `$(header)`, the values are an array of strings. If I use `$(header.key)`, the values are string.

I noticed this when working on #241. I think using strings instead of arrays would be the more expected behavior. This is also the behavior we use in most cases.

**Comment by bigkevmcd** [comment]
Possibly a good first task?

Affected tests are https://github.com/tektoncd/triggers/blob/master/pkg/template/event.go#L151 and https://github.com/tektoncd/triggers/blob/master/pkg/template/event_test.go#L597

**Comment by dibyom** [comment]
Hey @bigkevmcd I think #241 should fix this actually
