### ISSUE TITLE
Uninstalling Triggers can potentially uninstall Pipelines as well

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#262]
# Expected Behavior

Triggers should not be responsible for creating/deleting the tekton-pipelines namespace since installing pipelines is a pre-requisite.

# Actual Behavior
Reported by @AlanGreene on Slack:

Hi folks, quick question regarding install and uninstall of triggers. Is it known / expected that removing triggers (via. kubectl delete --filename https://storage.googleapis.com/tekton-releases/triggers/latest/release.yaml) removes the tekton-pipelines namespace? For me at least this was unexpected and meant I had to reinstall other projects in that namespace. Since pipeline is a pre-req, I wouldn’t have expected the triggers project to be responsible for laying down the `tekton-pipelines` namespace and thus including it in its cleanup. Is removing https://github.com/tektoncd/triggers/blob/master/config/100-namespace.yaml something we could consider?

# Steps to Reproduce the Problem

1. kubectl delete --filename https://storage.googleapis.com/tekton-releases/triggers/latest/release.yaml

# Additional Info

**Comment by ncskier** [comment]
Are we happy running everything under the `tekton-pipelines` namespace, or should we use our own namespace like `tekton-triggers`?

Thoughts @dibyom @wlynch ?

**Comment by wlynch** [comment]
I suspect that most users will want triggers to be in the same namespace as pipelines by default. We default to the current namespace in the EventListener if one is not explicitly provided, and that feels like behavior that makes sense.

As Dibyo pointed out, pipeline is a prerequisite for triggers - we can probably just remove the namespace config and things should just work.
