### ISSUE TITLE
FR: Add URL option to WebhookInterceptor

### ISSUE THREAD

**Issue by wlynch** [tektoncd/triggers#270]
# Expected Behavior

[WebhookInteceptor](https://godoc.org/github.com/tektoncd/triggers/pkg/apis/triggers/v1alpha1#WebhookInterceptor) docs say: `Either objectRef or url can be specified`

# Actual Behavior

There is no `url` field. We should add it!

**Comment by wlynch** [comment]
https://github.com/knative/pkg/blob/d9a38f13e8b9aa736f714b793ee28788de1b30e0/apis/duck/v1beta1/destination.go#L26-L47

Is a good example of how we can represent this.

**Comment by dibyom** [comment]
We should add an URI field just like https://github.com/knative/pkg/blob/master/apis/duck/v1beta1/destination.go#L46 
(we could try seeing if we can the Destination struct itself)
