### ISSUE TITLE
Make sure that tabs vs. spaces will be caught by presubmit linting

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/triggers#28]
# Expected Behavior

Our codebase should consistently use tabs or spaces, and if code is submitted that is inconsistent, it should be caught by our presubmit linting checks.

# Actual Behavior

Although #4 added linting, #21 added some files with spaces instead of tabs (https://github.com/tektoncd/triggers/pull/21#discussion_r305946629) and our linting didn't catch it :O

**Comment by ncskier** [comment]
PR https://github.com/tektoncd/triggers/pull/40 closes this issue.
