### ISSUE TITLE
CEL base64 decoder

### ISSUE THREAD

**Issue by wlynch** [tektoncd/triggers#339]
Similar to #329, we should add a function for base64 decoding message payloads! This would be useful for processing Google Cloud Pubsub events, where the `message.data` field is base64 encoded.

https://cloud.google.com/pubsub/docs/push#receiving_push_messages

/kind feature
/cc @bigkevmcd

**Comment by bigkevmcd** [comment]
This is fairly trivial, here it is on top of the cel-munging branch https://github.com/tektoncd/triggers/compare/master...bigkevmcd:base64-decoding happy to open a PR.

As to the name of the function...

**Comment by bigkevmcd** [comment]
@wlynch I think we could close this out?

**Comment by dibyom** [comment]
This has been added: https://github.com/tektoncd/triggers/blob/master/docs/cel_expressions.md
/close
