### ISSUE TITLE
All existing types should have validation

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/triggers#35]
# Expected Behavior

When the webhook notices that one of our trigger CRD types is created, it will invoke each type's validation. When that validation is invoked, it should look at the fields of each CRD and make sure they are valid.

# Actual Behavior

We have the skeleton webhook added, but our validation functions are empty, e.g.

https://github.com/tektoncd/triggers/blob/357fee5b70356dfd25eb26422310f9108c92fb85/pkg/apis/triggers/v1alpha1/trigger_template_validation.go#L24-L30

# Additional Info

This issue might not make any sense yet sine none of the types actually do anything, and we're still working on adding arbitrary event payloads in #19 so feel free to close this if I'm totally off base XD

**Comment by vincent-pli** [comment]
@bobcatfish  
Can you assign this issue to me, I will add basic validation based on current design.

**Comment by vtereso** [comment]
From the WG discussion:

With the typing structure of Triggers, following references will likely be necessary for validation. For example, parameter validation of an `EventListener` trigger will need to cross reference the corresponding `TriggerTemplate` and `TriggerBinding`. Our validation function does not have access to a client, but it would likely be the best place to store this logic. The admission controller would fast fail if the resources don't exist, which seems like the better option instead of having to parse some status/logs.  We can do this in the reconciler for a first pass if modifying the admission controller becomes cumbersome.

**Comment by vincent-pli** [comment]
@vtereso 
😓 Missing the WG meeting.
Right, validation function is the right place to do that, I will check it and back here later.

**Comment by vincent-pli** [comment]
To restrict that:
One `TriggerTemplate` should include at least one `Pipelinerun`, is that make sense?

**Comment by vtereso** [comment]
@vincent-pli I don't think any verification of the params being used in the templates is necessary. In this way, I don't think we need to check for particular resources in the templates (e.g `PipelineRun`). What restrictions are you referring to?

**Comment by vincent-pli** [comment]
Actually I want to find a signal which can express that: 
`The process triggered by the coming event has done, then please collect the garbage if necessary.`
I think the status of `Pipelinerun` could play the role, so I think the restriction is needed.

**Comment by ncskier** [comment]
I agree with @vtereso. I don't think that we should force users to trigger PipelineRuns (event though in most cases they will be doing this).

I don't think that we want to delve into parsing the status of a triggered PipelineRun at the moment. Currently, Triggers isn't concerned with the resources after they've been created, and I don't think we should complicate things by watching a PipelineRun's status. That seems like the responsibility of whoever is using Triggers. I do think that we should make it easy for someone to clean up the Triggered resources, but that's already covered in #64.

**Comment by dibyom** [comment]
@vincent-pli as part of #83 , I'm adding some validation for trigger templates. Not verifying that the trigger templates contains a pipelinerun but verifying that it contains at least one resource template and at least one param

**Comment by ncskier** [comment]
> verifying that it contains at least one resource template and at least one param

@dibyom I understand wanting to have at least one resource template, but I don't think that we should force the user to have at least one param. I could potentially see a use case where someone would want to trigger something without reading any of the event information, and I don't think we get much by forcing the user to have at least one param.

**Comment by dibyom** [comment]
Good point, no params might be useful for Cronjobs/periodic pipelineruns among other things!

**Comment by dibyom** [comment]
Closed by #160
