### ISSUE TITLE
How to expose an EventListener via Knative

### ISSUE THREAD

**Issue by JCzz** [tektoncd/triggers#351]
Trying to create [Webhooks](https://github.com/tektoncd/experimental/blob/master/webhooks-extension/docs/GettingStarted.md) and expose a listener to Internet/github.com

I found [this](https://github.com/tektoncd/triggers/issues/153) and got a little scared, so I just want to get a verification -  is this the way to go to expose EventListener using Knative urls?

If using Ingress, do you setup a Loadbalancer for each - and how? 
It would be nice to be able to use the same Ingress/routing to save on creating Loadbalancers.

**Comment by vtereso** [comment]
@JCzz Can you be a bit more explicit on the use case? The Triggers sink is an addressable, which should be compatible with Knative Eventing.

**Comment by vdemeester** [comment]
As @vtereso said, I don't think it's possible yet (to exposed the event listener using knative serving), but I feel it would be nice to have that option somehow in triggers :angel: (aka being able to have the service as a knative service if the user wants)

**Comment by dibyom** [comment]
Yeah, deploying the event listener sink as a Knative service would be cool :)

You can definitely use Knative eventing in front of the event listener -- one example here: https://github.com/iancoffey/brokers-tekton

You should also be able to use a non load balancer service type and then expose it to the outside world using an ingress (just like with any other k8s service)
