### ISSUE TITLE
Question : gitlab interceptor / triggerbinding variable interpolation

### ISSUE THREAD

**Issue by DanielBFox** [tektoncd/triggers#361]
# Expected Behavior
Be able to access HTTP JSON body parameters of Gitlab push hook event 

# Actual Behavior
I try to access the **ref** parameter from the body of a Gitlab push hook event 
But I receive this error message from the event listener pod : 
{"level":"error","logger":"eventlistener","caller":"sink/sink.go:144","msg":"failed to ApplyEventValuesToParams: &{%!w(string=failed to replace JSONPath value for param gitrevision: {string $(body.ref) []}: &{%!w(string=ref is not found)})}","knative.dev/controller":"eventlistener","/triggers-eventid":"f7rh6","/trigger":"trigger-gitlab","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\t/workspace/go/src/github.com/tektoncd/triggers/pkg/sink/sink.go:144\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\t/workspace/go/src/github.com/tektoncd/triggers/pkg/sink/sink.go:93"}

# Steps to Reproduce the Problem

**Gitlab push hook** 
Request headers:
Content-Type: application/json
X-Gitlab-Event: Push Hook
X-Gitlab-Token: ...
Request body:
{
  "object_kind": "push",
  "event_name": "push",
  "before": "8d910b6b871c270f63548a84f51c486f67015084",
  "after": "b5266fdec6473cb223fd146987c0e238dd5eed86",
  "**ref**": "refs/heads/master",
  "checkout_sha": "b5266fdec6473cb223fd146987c0e238dd5eed86",
  "message": null,
...

**TriggerBinding interceptor**
"
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: ci
  namespace: staging-mycalculator
spec:
  params:
    - name: gitrevision
      value: **$(body.ref)**
    - name: gitrepositoryurl
      value: $(body.repository.git_ssh_url)
    - name: gitrepositoryname
      value: $(body.repository.name)

---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
  namespace: staging-mycalculator
spec:
  serviceAccountName: staging
  triggers:
    - name: trigger-gitlab
      interceptors:
        - gitlab:
            eventTypes:
            - Push Hook
      bindings:
        - name: ci
      template:
        name: ci
"

# Additional Info
I installed the latest releases of triggers and pipelines

**Comment by aitchjoe** [comment]
Same problem!

I also tried CEL/Github/WebHook interceptors, the result is even worse:

> panic: runtime error: invalid memory address or nil pointer dereference

and the eventlistenersink pod crashed.

**Comment by aitchjoe** [comment]
I tried $(body) and it is null. But from [gitlab_test.go](https://github.com/tektoncd/triggers/blob/d182697ec591cbae1954deceaa663cd5aff7a814/pkg/interceptors/gitlab/gitlab_test.go#L104):
````
		{
			name: "valid event",
			GitLab: &triggersv1.GitLabInterceptor{
				EventTypes: []string{"foo", "bar"},
			},
			args: args{
				eventType: "foo",
				payload:   []byte("somepayload"),
			},
			wantErr: false,
			want:    []byte("somepayload"),
		},
```

this test confirm payload/body is not null, so I think the problem maybe within sink.go.

**Comment by dibyom** [comment]
I think this might be related to #357 

Does this still happen with the 0.2.1 preview build? https://github.com/tektoncd/triggers/releases/tag/v0.2.1-preview

**Comment by DanielBFox** [comment]
Hello,

I just tried with the release v0.2.1 and it works now like a charm.

{"level":"info","logger":"eventlistener","caller":"sink/sink.go:147","msg":"params: %+v[{gitrepositoryurl {string git@gitlab.com:danielbfoxg/mycalculator/go/add.git []}} {gitrepositoryname {string add []}} {gitrevision {string refs/heads/master []}}]","knative.dev/controller":"eventlistener","/triggers-eventid":"dlfgs","/trigger":"trigger-gitlab"}

Thanks for the great job
