### ISSUE TITLE
Upgrade to v0.2.0 requires recreating event listeners

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/triggers#366]
# Expected Behavior
Upgrading to triggers v0.2.0. Event listeners should be up and running.

# Actual Behavior
Event listeners are in crashloop, with the following error:
```
2020/01/20 14:18:55 Error loading logging configuration: lstat /etc/config-logging: no such file or directory

```

# Steps to Reproduce the Problem

1. Run triggers v0.1.0
2. Create event listeners
3. Upgrade to triggers v0.2.0

# Additional Info
To fix this issue:
- [ ] Update Release notes to say that the Params field has been removed and explicitly mention that Params field will not work at all and users will have to create `TriggerBindings` with static values instead.
- [ ]  Add a `DeperecatedParams` field to fix the sink `CrashLoopBackoff`

**Comment by dibyom** [comment]
Two things here:

1. We deprecated and removed the params field from the EventListener. So, when we upgrade from 0.1 to 0.2 and the reconciler tries to [upgrade `binding` and `interceptor` to `bindings` and `interceptors`](  https://github.com/tektoncd/triggers/blob/v0.2.0/pkg/reconciler/v1alpha1/eventlistener/eventlistener.go#L142), the webhook fails because it cannot parse the deleted `params` field.

2. The new event listener sink image expects `/etc/config-logging` to be [mounted](https://github.com/tektoncd/triggers/blob/v0.2.0/cmd/eventlistenersink/main.go#L63). However, due to 1., the reconcile fails and the deployment is never updated with the `config` mount.

**Comment by dibyom** [comment]
I think fixing 1. will also fix 2. We can add a `DeprecatedParams` field though it will do nothing but prevent the crashes. 
Also, since the sink is a Deployments, while the new Pod will get into a `CrashLoopBackoff` state, the old pod should still keep running:

```
NAME                           READY   STATUS             RESTARTS   AGE
el-listener-56d76b6767-snwdq   0/1     CrashLoopBackOff   8          18m
el-listener-7775b9c9df-h6zzs   1/1     Running            0          23m
```

**Comment by dibyom** [comment]
To fix this issue:
- [ ] Update Release notes to say that the Params field has been removed and explicitly mention that Params field will not work at all and users will have to create `TriggerBindings` with static values instead.
- [ ]  Add a `DeperecatedParams` field to fix the sink `CrashLoopBackoff`

**Comment by dibyom** [comment]
```
{"level":"info","logger":"controller.eventlistener-controller","caller":"eventlistener/eventlistener.go:363","msg":"Updated EventListener Deployment el-listener in Namespace default","knative.dev/controller":"eventlistener-controller"}
{"level":"warn","logger":"controller.eventlistener-controller","caller":"eventlistener/eventlistener.go:132","msg":"Failed to update EventLi
stener statusInternal error occurred: admission webhook \"triggers-webhook.tekton.dev\" denied the request: mutation failed: cannot decode incoming old object: json: unknown field \"params\"","knative.dev/controller":"eventlistener-controller"}
{"level":"error","logger":"controller.eventlistener-controller","caller":"controller/controller.go:350","msg":"Reconcile error","knative.dev
/controller":"eventlistener-controller","error":"Internal error occurred: admission webhook \"triggers-webhook.tekton.dev\" denied the reque
st: mutation failed: cannot decode incoming old object: json: unknown field \"params\"","stacktrace":"github.com/tektoncd/triggers/vendor/kn
ative.dev/pkg/controller.(*Impl).handleErr\n\t/workspace/go/src/github.com/tektoncd/triggers/vendor/knative.dev/pkg/controller/controller.go
:350\ngithub.com/tektoncd/triggers/vendor/knative.dev/pkg/controller.(*Impl).processNextWorkItem\n\t/workspace/go/src/github.com/tektoncd/tr
iggers/vendor/knative.dev/pkg/controller/controller.go:336\ngithub.com/tektoncd/triggers/vendor/knative.dev/pkg/controller.(*Impl).Run.func1\n\t/workspace/go/src/github.com/tektoncd/triggers/vendor/knative.dev/pkg/controller/controller.go:285"}
{"level":"info","logger":"controller.eventlistener-controller","caller":"controller/controller.go:337","msg":"Reconcile failed. Time taken: 72.172736ms.","knative.dev/controller":"eventlistener-controller","knative.dev/traceid":"8b1ec8e5-6cf1-4456-8533-9aa2a761ec83","knative.dev/key":"default/listener"}
```
