### ISSUE TITLE
Create an end to end test (in go) that creates an EventListener

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/triggers#37]
# Expected Behavior

We should have a suite of end to end tests that we can use to test triggers functionality. We can start with a simple one that:

1. Creates an EventListener
2. Confirms it is created
3. Deletes the EventListener
4. Confirms it is deleted

(If #36 happens first, this test can actually look for a running container, otherwise this will be a very light test!)

# Actual Behavior

We've got [a dummy test](https://github.com/tektoncd/triggers/blob/master/test/dummy_test.go) but not actually invoking any of our libs yet :D

# Additional Info

One question at this point is do we want to use the knative test lib? I think it's probably simpler to use it, e.g.:

https://github.com/tektoncd/pipeline/blob/b91640d7db3d2de6fcb8c30c618a417047a03c12/test/embed_test.go#L69-L70

However it's not that complicated to implement our own (this is an example of what's required to hit most of the common stuff we'd need to do) https://github.com/bobcatfish/testing-crds/blob/master/client-go/test/cat_test.go#L136

Up to the implementer of this issue 😉 and also something we can easily change later!

**Comment by ncskier** [comment]
@bobcatfish @vdemeester 
For these Tekton Triggers go tests, should we follow the Pipeline repo's test format, and use the [knative.dev/pkg/test](https://github.com/tektoncd/pipeline/blob/master/test/init_test.go#L35) library?

**Comment by vdemeester** [comment]
I think so, yes

**Comment by ncskier** [comment]
Ok, thanks

**Comment by ncskier** [comment]
Closing this issue because we merged PR https://github.com/tektoncd/triggers/pull/53 👍
