### ISSUE TITLE
Reducing the pods related to EventListener

### ISSUE THREAD

**Issue by khrm** [tektoncd/triggers#370]
# Expected Behavior
There should be fewer pods or deployments related to EventListener. 

# Actual Behavior
At present, you can any number of pods handling EventListener logic. This led to wastage of resources due to the proliferations of these pods.

# Additional Info
Current Proposal:
https://docs.google.com/document/d/1is5sJMkqWMnOa4fP87H39auTnWR1IKFu7TxTkMNJV5c/edit#

**Comment by khrm** [comment]
Summary of Discussion on this &
https://github.com/tektoncd/triggers/issues/456

1.  Design recommended in both scenarios are based on having URL to determine EL or TriggerCRD .
2.  Main issue with these designs are RBAC. Should be give RBAC permissions similar to controller for a global EventListener?
3. If we don't want to 2, then we would need to give permission to create Pod with a particular SA in every namespace to EL deployment which relates to Triggers. Now this creates another security issue that a lot of transient pods could be created by just hitting the URL.

**Comment by dibyom** [comment]
Similar to https://github.com/tektoncd/triggers/issues/456 -> part of TEP-009 and TEP-008. I think we can keep this closed and open other issues for those two.
