### ISSUE TITLE
Create builder package for tests

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/triggers#38]
# Expected Behavior

[The builder package in pipelines](https://github.com/tektoncd/pipeline/tree/master/test/builder) is super handy for instantiating instances of the pipeline CRDs in unit tests! Would be great to have something like this (and tests for the builders themselves in triggers :D

# Actual Behavior

We don't have this yet!

When @vdemeester added this to pipelines it took him quite a long time and I can tell you from experience that refactoring tests to use these builders later is not a ton of fun, so it'd be great if we could get these in sooner rather than later 💃

**Comment by bobcatfish** [comment]
example of how this can make tests more succinct https://github.com/tektoncd/pipeline/pull/1044/files

**Comment by dibyom** [comment]
Fixed in #52
