### ISSUE TITLE
Nested TriggerBinding expressions $($())

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#385]
Following the discussion in https://github.com/tektoncd/triggers/pull/376#discussion_r370209602
let's discuss what the behavior should be for nested Tekton expressions in TriggerBindings

## Current documented behavior

- Nested expressions are allowed. However, only the text in innermost `$()` is evaluated as JSONPath, the rest is treated as regular strings. From the [docs](https://github.com/tektoncd/triggers/blob/master/docs/triggerbindings.md#event-variable-interpolation):

If the `$()` is embedded inside another `$()` we will use the contents of the innermost
`$()` as the JSONPath expression

```shell script
$($(body.b)) -> $(body.b)
$($($(body.b))) -> $(body.b) 
```

## Questions
- Is there an actual use case for this?
- Should we just return an error instead of the behavior above?

**Comment by vtereso** [comment]
In this format, it seems like we are allowing for the inner value to be resolved recursively rather than just taking the text. I think an error is probably better?

**Comment by dibyom** [comment]
This is another "unintentional" feature/bug that we should fix

**Comment by dibyom** [comment]
Still a bug that we need to fix :)

**Comment by jmcshane** [comment]
@dibyom what is the "correct" behavior here? has that ever been decided?

**Comment by dibyom** [comment]
Leaning towards just making this an error.
