### ISSUE TITLE
Clean up sink_test.go

### ISSUE THREAD

**Issue by ncskier** [tektoncd/triggers#394]
The [sink_test.go](https://github.com/tektoncd/triggers/blob/master/pkg/sink/sink_test.go) file has a lot of messy tests with repeated code (especially for the `HandleEvent()` function). It's difficult to write clean tests for this file, because it's pretty high-level. However, I think that we can clean up some of the code, and hopefully use some [table driven tests](https://github.com/golang/go/wiki/TableDrivenTests) to abstract away some of the testing logic.

**Comment by dibyom** [comment]
#413 fixed most of this -- most setup is now abstracted out into helper functions. Table driven tests will be a bit harder here given the variety of things were are asserting.
Closing for now
/close
