### ISSUE TITLE
Get linting running against repo

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/triggers#4]
## Expected behavior

Every PR should have logic applied to it to make sure that:
* Go code is formatted as expected
* Markdown files are formatted as expected and links they contain work

## Actual behavior

We don't have any code, or any automation :O

## Additional info

* These are called ["build-tests"](https://github.com/tektoncd/plumbing/blob/master/prow/config.yaml#L397) in the prow config which is generally referring to linting and building, basically smoke test / linting but not actually running any tests <-- for now we should probably just copy this and do exactly what it does
* The config that prow uses to determine what to run against what repo is in [this config.yaml](https://github.com/tektoncd/plumbing/blob/master/prow/config.yaml) and the instructions for updating it are [in this readme](https://github.com/tektoncd/plumbing#prow) (you might need the assistance of someone with cluster access to apply the config)

**Comment by vtereso** [comment]
@vdemeester has already pushed the https://github.com/tektoncd/triggers/blob/master/test/presubmit-tests.sh file, which handles linting using the defaults in the `tektoncd/plumbing` repo
