### ISSUE TITLE
Decouple from Pipeline or Align with Pipeline release

### ISSUE THREAD

**Issue by khrm** [tektoncd/triggers#415]
# Expected Behavior
Whenever a new pipeline is released, tkn-cli should have no problem in updating to it and at the same time using Triggers.

# Actual Behavior
At present, this causes a dependency issue at tkn-cli side. We need to update Pipeline in Triggers before in tkn-cli.

# Additional Info
Either decoupling or aligning Triggers with Pipeline release would solve this issue.

**Comment by dibyom** [comment]
The main usage of pipeline in triggers is the the `Param` type. Maybe we don't need to reuse param...I don't think we are using ArrayParams anyway!

**Comment by dibyom** [comment]
For the 0.3 release, we decided that I can co-ordinate with CLI/Pipeline to ensure we have the pipeline version we need

**Comment by vtereso** [comment]
We can close this issue/readdress once we sync in 0.4.

**Comment by vdemeester** [comment]
@vtereso how so ? this will be an issue after 0.4 right ?
@dibyom if it's only for Param types, it might be worth "duplicating" those (acting like a completely separate client, using the API only, no shared code)

**Comment by ncskier** [comment]
> @dibyom if it's only for Param types, it might be worth "duplicating" those (acting like a completely separate client, using the API only, no shared code)

I agree with @vdemeester that it shouldn't be a problem to create our own Param types.

---

Trying to create a quick summary, currently I think we use Pipelines for:
- tests
- Params
- clientset for creating resources (the two files mentioned in [this](https://github.com/tektoncd/triggers/issues/494) issue)

Is there anything else that I'm missing?

**Comment by dibyom** [comment]
I think that's about it

**Comment by dibyom** [comment]
I like Vincent's idea though I think this can wait till 0.5.

**Comment by dibyom** [comment]
I found one other usage of Params  (incl. ArrayParams): Header values in webhook interceptor. Though I'm wondering if we can always use []string like Go header values instead of arrayOrString.

**Comment by ncskier** [comment]
Another option is to use Go's [http Header type](https://golang.org/pkg/net/http/#Header).
Although, that's a `map[string][]string`, so it would change the interceptor YAML syntax a bit.
