### ISSUE TITLE
New TestEventListenerCreate test fail because cluster level resources are not deleted

### ISSUE THREAD

**Issue by zhangtbj** [tektoncd/triggers#418]
# Expected Behavior
When I run the e2e test, it should pass as before

# Actual Behavior
TestEventListenerCreate test fails because the cluster level resources are not deleted:

1. clusterrolebinding.rbac.authorization.k8s.io "my-rolebinding"
2. clusterrole.rbac.authorization.k8s.io "my-role"
3. clustertriggerbinding.tekton.dev "my-clustertriggerbinding"

# Steps to Reproduce the Problem

1. have a new cluster
2. run e2e test and DO NOT clean the environment
3. re-run the e2e test, it will fail because cluster level resources are not deleted

# Additional Info
https://github.com/tektoncd/triggers/blob/master/test/eventlistener_test.go#L156-L216

After I removed them manually, the second test passed.

Pls clean these resources after test

**Comment by dibyom** [comment]
cc @piyush-garg 

I wonder how CI is passing :thinking:

**Comment by piyush-garg** [comment]
@dibyom I think the CI is passing because we always spin a new environment for CI

**Comment by zhangtbj** [comment]
Thank you all!
