### ISSUE TITLE
Task trigger within a pipeline

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/triggers#44]
This is a proposed feature that would help orchestrating asynchronous pipelines.

The use case is as follows: as a user I want to be able to include in a pipeline a component that is executed asynchronously and possibly externally i.e. Tekton on a different cluster or something that is not Tekton at all.

For instance a pipeline may include a Task that sends a cloud event on completion. The cloud event triggers an external system that does a certain amount of processing, and sends a call back via cloud event. In the pipeline below, tasks A and C are started in parallel. Task B is only executed once A is complete. Task D is only executed when a cloud event is received. In this specific example this event is a call-back from an event that was sent by Task C to an external system.

![task_trigger_in_pipeline](https://user-images.githubusercontent.com/2205608/61993572-bbc5d200-b065-11e9-96a9-762387e5b50c.png)

In this example the pipeline helps us orchestrate the execution of an external task, since the overall pipeline condition exposed for the pipeline resource via the k8s API includes the execution and result of a process on an external system.

The UX model I had in mind for this feature is that a CloudEventPipelineResource could be extended to be used as an input, include a reference to a template, and Tekton would setup a binding implicitly for the Task that as that input resource.

**Comment by vtereso** [comment]
To my understanding and regarding the initial proposed design, Triggers should be able to create any resource as specified in the [`TriggerTemplate`](https://github.com/tektoncd/triggers/blob/master/docs/triggertemplates.md).

> For instance a pipeline may include a Task that sends a cloud event on completion.
IIUC, a `PipelineRun` with a referenced `Pipeline` (or `TaskRun`) should very well be able to internally emit a cloud event. As I mentioned in a [recent comment](https://github.com/tektoncd/triggers/issues/42#issuecomment-515600172) on the `CloudEvent` proposal, perhaps it might be advantageous to consider a `CloudEvent` callback to events rather than this "indirect" route through Tekton. Here, I also talk about`Conditionals`.

> The use case is as follows: as a user I want to be able to include in a pipeline a component that is executed asynchronously and possibly externally i.e. Tekton on a different cluster or something that is not Tekton at all.
As I understand this, it seems more of a feature request for `Pipelines`/`PipelineRuns` to be able to execute `TaskRuns` in a different cluster, or at least to wait for some response external to proceed with the execution of a run. Maybe you see this as being more viable in `Triggers` since there is already the notion of an `Addressable` endpoint? I might not understand your point.

**Comment by afrittoli** [comment]
Depending on how this is implemented in may impact `triggers` or `pipeline` or both, but I created this in the triggers project because this is where folks with interest on event driven workflows will hang out :).

Normally a `TaskRun` is created by the `PipelineRun` controller for each `Task` in the referenced `Pipeline`. The `PipelineRun` controller will only create the `TaskRun`  when the correspending `Task` is ready to be executed, i.e. all input resources are available and `runAfter` condition satisfied. 

In this case the input would be different, it would the receipt of an event from a binding. 
In terms of the trigger project, this means that the `TaskRun` and some of the `PipelineResources` will potentially have been provisioned by the `PipelineRun` controller - or alternatively triggers must be able to provision them based on input received from the pipelinerun cointroller. Either case this will probably require changes in both projects.

**Comment by ncskier** [comment]
Hi @afrittoli, I like this use case of asynchronous Pipelines! 

If I'm not mistaken, our current design will support this architecture already, but without using a CloudEventResource as an input PipelineResource. Instead, Triggers would receive the CloudEvent, and the TriggerBinding + TriggerTemplate would pass the relevant information from the CloudEvent to Task D. So, we don't currently have a design for passing events "through" Triggers, although you could probably achieve something similar with our current design. So, I think your example workflow would change to look like this:

![Screen Shot 2019-07-29 at 11 25 47 AM](https://user-images.githubusercontent.com/16961496/62060745-ad0d2580-b1f3-11e9-9e5a-abbf0db2bffb.png)

Do you think this workflow would suit your use case? Also, what would the input CloudEventResource that you're proposing look like, and do you think it will be necessary?

**Comment by vincent-pli** [comment]
`Trigger` will create `task/taskrun` referred by another `pipeline`? 🤔 
I don's saw any clue in the design document.
I always think `Trigger` only create `pipelineResource` and `pipelineRun`!

If that's in the scope, we need interact with `pipelineRun` controller, expect is emit `CloudEvent`. That's big change.

For the case from @afrittoli, the asynchronous `task` in a `pipeline`, I think it should be leverage to `Condition`, a `Condition` who will check if a `CloudeventResource` is rendered, but we need enhance `pipelineRun` controller to make it do not check if the resource ready at the very beginning.

Alternatively, make `Task D` as an independent `Pipeline` triggered by `Trigger` after receive the event.

**Comment by ncskier** [comment]
Oh, my mistake. I didn't realize that all of the tasks had to be under one Pipeline. So, the current plan for Triggers can achieve the same functionality, but will not be able to trigger a Task in a Pipeline. That seems like a problem that will have to be tackled under the Pipelines project. Triggers will be able to create the proposed CloudEventResource, so if the Pipelines project is able to wait for the creation of this resource (maybe with a type of conditional?), then I guess the above scenario will work 👍
