### ISSUE TITLE
FR: Configurable Services/Deployments for EventListener Sinks

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#440]
# Expected Behavior

A user should have more control over their EventListener sink. Today the only option we provide is the `serviceType`. Users might want to control the number of replicas for their deployments, loadBalancerIPs etc.

# Actual Behavior

We don't provide a declarative way for users to configure any of these. Users may modify the created sink objects directly but we do not provide any guarantees that the EL reconciler will not overwrite the user changes

# Additional Info

1. Some related discussion in #370 
2. An alternative to explore - instead of adding more configuration for the users, add different modes of deployments e.g. deploy the EL sink as a knative service instead

**Comment by akihikokuroda** [comment]
The requirement for the service is already covered but here is information for EKS configuration: https://github.com/tektoncd/experimental/blob/master/webhooks-extension/docs/GettingStarted.md#notes-for-amazon-eks

**Comment by dibyom** [comment]
Closing in favor of #505 
/triage duplicate
/close
