### ISSUE TITLE
Cloud Event example

### ISSUE THREAD

**Issue by ncskier** [tektoncd/triggers#450]
# Expected Behavior
Cloud Events are a relatively common way of sending and receiving events. Triggers currently supports receiving HTTP requests with JSON payloads, so I think that we should have an example in the repository for a CloudEvent.

# Actual Behavior
There are currently no Triggers examples for receiving a CloudEvent.

# Additional Info
I created this issue because of a question raised in the Triggers Slack channel about how to use Triggers with CloudEvents: https://tektoncd.slack.com/archives/CKUSJ2A5D/p1582042428110600.

**Comment by dibyom** [comment]
I think we've been using the pattern of pipelines emitting cloud Events that are sent to a Triggers repo that then run a task based on the event in tektoncd/plumbing

**Comment by iancoffey** [comment]
I have an example I can add for this 👍
