### ISSUE TITLE
Multi-Tenant EventListener

### ISSUE THREAD

**Issue by khrm** [tektoncd/triggers#456]
# Expected Behavior
It should be feasible to use multi-tenant EventListener.
 

# Actual Behavior
EventListener can create tekton resources if it has appropriate clusterroles but multi-tenant EventListener isn't possible.

# Steps to Reproduce the Problem
The following flow isn't possible if we deploy multi-tenant EventListener:

1. Using admin account

- Create a namespace foo
- Create EventListener in the namespace foo with service account of clusterrole which can create resources in any namespace.
- Create a namespace bar 
- Create a service account bar-svc for namespace bar with permission to get EL, create Tekton Pipeline resources, TriggerBindings and TriggerTemplates.

2. Using bar-svc

Create a Pipeline.
Create TriggerBindings(TB) and TriggerTemplates(TT).

Now we want that EL to somehow refer to Trigger(TT+TB) that we have created.  

# Additional Info
This problem can be solved if we follow the approach in pr: https://github.com/tektoncd/triggers/pull/427
Here we have a Trigger CRD. We hit el URL with /foo/bar where foo is the namespace and bar is Trigger. EL fetches bar Trigger and executes that instead of looping through all the Triggers in the Spec reference. EL get Trigger ref in the URL.

**Comment by khrm** [comment]
@gabemontero @wlynch @ncskier
I was discussing this scenario.

**Comment by ncskier** [comment]
@khrm I understand your use-case of wanting your EventListener in Namespace `foo` to be able to use TriggerTemplates and TriggerBindings in Namespace `bar` and other Namespaces.

However, is your goal to truly have multi-tenancy, or just multiple users of one organization? I'm honestly not very knowledgable about the subject of multi-tenancy, but if I understand correctly, multi-tenancy comes with a number of problems that the Triggers project would have to address; for example, cluster-scoped resources, data security, etc.

**Comment by khrm** [comment]
@ncskier For now, we are just focusing on just multiple users of one organization. Where every project/user is assign a namespace.

**Comment by ncskier** [comment]
Trying to write up the use-case to see how it would work with https://github.com/tektoncd/triggers/pull/454 which adds ServiceAccounts per Trigger.

## Use-case

If I understand the use-case correctly, the idea is to support having multiple users where each use has their own Namespace. In this Namespace, each use will have their own TriggerTemplates + TriggerBindings as well as their own ServiceAccounts + Roles + RoleBindings.

### Example:

Namespace **`system`**
- EventListener `system-el`
- ServiceAccount `system-sa` (authorized to get TriggerTemplates, TriggerBindings, and ServiceAccounts/Secrets from any Namespace)
- ClusterRole `system-cr`
- ClusterRoleBinding `system-crb` (attach ClusterRole `system-cr` to ServiceAccount `system-sa`)

Namespace **`user1`**
- TriggerTemplate `user1-tt`
- TriggerBinding `user1-tb`
- ServiceAccount `user1-sa` (authorized to create resources in the TriggerTemplate `user1-tt`)
- Role `user1-r`
- RoleBinding `user1-rb` (attach Role `user1-r` to ServiceAccount `user1-sa`)

...

Namespace **`userN`**
- TriggerTemplate `userN-tt`
- TriggerBinding `userN-tb`
- ServiceAccount `userN-sa` (authorized to create resources in the TriggerTemplate `userN-tt`)
- Role `userN-r`
- RoleBinding `userN-rb` (attach Role `userN-r` to ServiceAccount `userN-sa`)

## Security concerns

If I understand correctly, the security concerns stem from the cluster-wide permissions that we're giving the EventListener's ServiceAccount `system-sa` to get ServiceAccounts/Secrets.
> ServiceAccount `system-sa` (authorized to get TriggerTemplates, TriggerBindings, and ServiceAccounts/Secrets from any Namespace)

## Potential solutions (so far)

- Put all user ServiceAccounts + Roles + RoleBindings (`userN-sa`, `userN-r`, `userN-rb`) in the EventListener's Namespace `system`.

FYI @dibyom @vtereso @khrm @gabemontero did I accurately capture the intended use-case and the security concerns?

**Comment by gabemontero** [comment]
> Trying to write up the use-case to see how it would work with #454 which adds ServiceAccounts per Trigger.
> ## Use-case
> 
> If I understand the use-case correctly, the idea is to support having multiple users where each use has their own Namespace. In this Namespace, each use will have their own TriggerTemplates + TriggerBindings as well as their own ServiceAccounts + Roles + RoleBindings.
> ### Example:
> 
> Namespace **`system`**
> 
>     * EventListener `system-el`
> 
>     * ServiceAccount `system-sa` (authorized to get TriggerTemplates, TriggerBindings, and ServiceAccounts/Secrets from any Namespace)
> 
>     * ClusterRole `system-cr`
> 
>     * ClusterRoleBinding `system-crb` (attach ClusterRole `system-cr` to ServiceAccount `system-sa`)
> 
> 
> Namespace **`user1`**
> 
>     * TriggerTemplate `user1-tt`
> 
>     * TriggerBinding `user1-tb`
> 
>     * ServiceAccount `user1-sa` (authorized to create resources in the TriggerTemplate `user1-tt`)
> 
>     * Role `user1-r`
> 
>     * RoleBinding `user1-rb` (attach Role `user1-r` to ServiceAccount `user1-sa`)
> 
> 
> ...
> 
> Namespace **`userN`**
> 
>     * TriggerTemplate `userN-tt`
> 
>     * TriggerBinding `userN-tb`
> 
>     * ServiceAccount `userN-sa` (authorized to create resources in the TriggerTemplate `userN-tt`)
> 
>     * Role `userN-r`
> 
>     * RoleBinding `userN-rb` (attach Role `userN-r` to ServiceAccount `userN-sa`)
> 
> 
> ## Security concerns
> 
> If I understand correctly, the security concerns stem from the cluster-wide permissions that we're giving the EventListener's ServiceAccount `system-sa` to get ServiceAccounts/Secrets.
> 
> > ServiceAccount `system-sa` (authorized to get TriggerTemplates, TriggerBindings, and ServiceAccounts/Secrets from any Namespace)
> 
> ## Potential solutions (so far)
> 
>     * Put all user ServiceAccounts + Roles + RoleBindings (`userN-sa`, `userN-r`, `userN-rb`) in the EventListener's Namespace `system`.
> 
> 
> FYI @dibyom @vtereso @khrm @gabemontero did I accurately capture the intended use-case and the security concerns?

at least for me @ncskier this captures a valid scenario and concerns that could be addressed by my PR, given it provides for more granular/specific authorization across multiple users.

And as this scenarios has been fleshed out, I *believe* we may have to answer to a TODO question I currently have in my PR's changes:  https://github.com/tektoncd/triggers/blob/29146ce2c30d98ce6d427b9dba9e63364b1d07a6/pkg/apis/triggers/v1alpha1/event_listener_types.go#L76

Where the answer is "no", and we want to leave `ServiceAccount` as a `*corev1.ObjectReference` to properly satisfy what you have articulated.

**Comment by khrm** [comment]
I created this short design after abstracting earlier discussion from older design document.
https://docs.google.com/document/d/1NX0ExhPad6ixTM8AdU0b6Vc3MVD5hQ_vIrOs9dIXq-I/edit#

**Comment by dibyom** [comment]
I think @ncskier 's comment captures the scenario well. @gabemontero 's per trigger changes should allow for the scenario mentioned. In the last WG meeting, it was suggested that we have some kind of  a best practices doc on how to go about setting up Triggers in multi-tenant scenarios. I'm wondering if this is an example scenario that we should present. Alternatives could be - each namespace has one listener that can be shared among all users within that namespace and each namespace has multiple listeners (which is what seems to be recommended now)

**Comment by dibyom** [comment]
I think @ncskier 's comment captures the scenario well. @gabemontero 's per trigger changes should allow for the scenario mentioned. In the last WG meeting, it was suggested that we have some kind of  a best practices doc on how to go about setting up Triggers in multi-tenant scenarios. I'm wondering if this is an example scenario that we should present. Alternatives could be - each namespace has one listener that can be shared among all users within that namespace and each namespace has multiple listeners (which is what seems to be recommended now)

**Comment by khrm** [comment]
> 1.  Design recommended  are based on having URL to determine TriggerCRD .
> 2.  Main issue with these designs are RBAC. Should be give RBAC permissions similar to controller for a global EventListener?
> 3. If we don't want to go with 2, then we would need to give permission to create Pod with a particular SA in every namespace to EL deployment which relates to Triggers. Now this creates another security issue that a lot of transient pods could be created by just hitting the URL.

**Comment by dibyom** [comment]
/lifecycle frozen

This is being worked on in TEP-009. Though maybe we should open newer, more targeted issues for this? @khrm

**Comment by patcito** [comment]
@dibyom would you have a link to TEP-009? I can't seem to find it here https://github.com/tektoncd/community/tree/dec14d2a9b9a15b114e3955885f702c0e73eb2c4/teps

**Comment by AlanGreene** [comment]
https://github.com/tektoncd/community/pull/148
