### ISSUE TITLE
Problem upgrading to v0.3.0

### ISSUE THREAD

**Issue by ncskier** [tektoncd/triggers#459]
# Expected Behavior
I expect to be able to upgrade to v0.3.0 without changing my EventListener.

# Actual Behavior
When upgrading to v0.3.0, the EventListener no longer works properly. When it receives an event, there seem to be errors extracting event data.

Here's an example error:
```
Get error when upgrading: {"level":"error","logger":"eventlistener","caller":"sink/sink.go:153","msg":"couldn't create resource with group version kind \"tekton.dev/v1alpha1, Resource=pipelineresources\": namespaces \"$(params.webhooks-tekton-target-namespace)\" not found","knative.dev/controller":"eventlistener","/triggers-eventid":"g8pzc","/trigger":"ghe-test-triggers-3-push-event","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:153\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:95"}
```

I think that I also saw a case when the $(params.example) were not filled in the TriggerTemplate.

I've found that these errors go away after deleting and recreating the EventListener resource. However, we have not announced this as a breaking change. Also, I think that we should fix this unless there's a good reason why it is breaking.

# Steps to Reproduce the Problem

1. Install Triggers v0.2.1
2. Create a working EventListener + TriggerBinding + TriggerTemplate with parameters being extracted from the event.
3. Install Triggers v0.3.0
4. Send an HTTP event to the EventListener and see if everything works properly

**Comment by akihikokuroda** [comment]
Issue is missing `b.kind` in the TriggerBindings

**Comment by dibyom** [comment]
Yeah, we set the default in the reconciler but never persist it. And the ResolveTrigger function in the sink expects a Kind to be set
