### ISSUE TITLE
Add ability to trigger on kubernetes resouces, not only web hooks

### ISSUE THREAD

**Issue by dbazhal** [tektoncd/triggers#478]
# Expected Behavior

Any way to trigger on some in-cluster event/resource required.
Watch-list objects of some type, or watch kubernetes events, and when an object meets some conditions - then take some infro from it, and trigger as tekton triggers usually do - create object(usually taskrun/pipelinerun).

# Actual Behavior

Now we can only trigger on some external http events.

**Comment by vtereso** [comment]
I like the idea of this. However, most resources have their own controller so I don't entirely know the use case.

**Comment by dbazhal** [comment]
> I like the idea of this. However, most resources have their own controller so I don't entirely know the use case.

I won't be inventing new ideas, my own goals for example are to:
- lower automation entry level for my users, so they could do anything even not knowing golang/kubernetes api internals
- watch apps behaviour and launch self-healing/notification tasks/pipelines
- watch different objects change and launch pipeline that bakes immutable artifact as compilation of many factors and delivers it through many testing environments to production unchanged

**Comment by dbazhal** [comment]
Oh, and another reasons came to mind.
1. kubernetes deployments watch themself and run rollout on change
2. in okd <= 3.11 there is buildconfigs/deploymentconfigs, and they all can trigger when themselves change

Tekton pipelines and tasks do not run themselves on change, because they are separated from their runs.
So there must be some tool to run tekton pipeline then it changes. Tekton triggers could be such tool.

**Comment by wlynch** [comment]
You might be interested in https://knative.dev/docs/eventing/samples/kubernetes-event-source/ which would allow you to produce events that could then be consumed/filtered by Tekton Triggers.

**Comment by dbazhal** [comment]
> You might be interested in https://knative.dev/docs/eventing/samples/kubernetes-event-source/ which would allow you to produce events that could then be consumed/filtered by Tekton Triggers.

Oh, thank you. We're looking into knative eventing right now, but that seem to be pretty complex tool, yet pretty rigid, so writing our own small trigger controller looks easier and more flexible in short term.

**Comment by dbazhal** [comment]
Can this please be reopened?) Would like to see this in future

**Comment by ibotty** [comment]
It's still relevant.  Please remove label.

**Comment by jmcshane** [comment]
one thing to note here is that if you use case is to trigger on something around a pipelinerun/taskrun executing, you can use the cloudevent configuration on the `config-defaults` tekton-pipelines configmap to send those events to a target eventlistener. if you need to send those across multiple eventlisteners, you can use a forwarder to send those events to multiple targets (without needing to deploy knative).

**Comment by jmcshane** [comment]
https://tekton.dev/docs/pipelines/events/#events-via-cloudevents

**Comment by ibotty** [comment]
On OpenShift/OKD I'd like to trigger on Changes in ImageStreamTags.  I'd like to reopen that issue.

**Comment by dibyom** [comment]
@ibotty Would you mind opening a new GH issue for that? Thanks!

**Comment by ibotty** [comment]
But wouldn't it be the same issue as that one?  Or do you mean specifically for ImageStreamTags?
