### ISSUE TITLE
Support creating v1beta1 Pipeline resources

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#481]
# Expected Behavior
Triggers should be able to create both v1alpha1 and v1beta1 Tekton resources

# Actual Behavior
Triggers can only create both v1alpha1 and v1beta1 Tekton resources

# Steps to Reproduce the Problem

1. Use a TriggerTemplate with a v1beta1 Tekton API

# Additional Info
See: https://github.com/tektoncd/triggers/pull/469#issuecomment-598890208

**Comment by bobcatfish** [comment]
Couple places i noticed to update:

* https://github.com/tektoncd/triggers/blob/master/pkg/client/dynamic/clientset/tekton/tekton.go#L11
*  https://github.com/tektoncd/triggers/blob/master/pkg/apis/triggers/v1alpha1/trigger_template_validation.go#L25
