### ISSUE TITLE
https://github.com/tektoncd/triggers/blob/master/examples/example-pipeline.yaml file is a Task. Name indicates its a Pipeline.

### ISSUE THREAD

**Issue by dewan-ahmed** [tektoncd/triggers#483]
# Expected Behavior
File is a Task YAML
# Actual Behavior
File is a Pipeline YAML

# Steps to Reproduce the Problem

1. Go to https://github.com/tektoncd/triggers/blob/master/examples/example-pipeline.yaml

# Additional Info

**Comment by ncskier** [comment]
There's a Pipeline at the bottom of the file. The Tasks at the beginning are used in the Pipeline: https://github.com/tektoncd/triggers/blob/master/examples/example-pipeline.yaml#L59.

**Comment by dewan-ahmed** [comment]
Got it. Thanks!

**Comment by ncskier** [comment]
No problem 👍
