### ISSUE TITLE
Allow Secret Access in CEL Interceptor

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#486]
# Expected Behavior
The CEL interceptor should provide a way to access Kubernetes secrets
Potential syntax: https://github.com/tektoncd/dashboard/issues/1129#issuecomment-597562963

# Actual Behavior
No way to access secrets from CEL at the moment. So folks who need to "hide" information have to use something like https://github.com/tektoncd/dashboard/issues/1129

# Additional Info
* We should consider what use cases we are trying to support via this feature. The current use case is verifying a shared secret header using CEL.

* One Alternative - built-in interceptor for generic payload validation: https://github.com/tektoncd/dashboard/issues/1129#issuecomment-597699067

* Security implications for exposing secrets via CEL esp. if we allow the EL pod to have access to all secrets/service account in the namespace/cluster #454

**Comment by ncskier** [comment]
> Security implications for exposing secrets via CEL esp. if we allow the EL pod to have access to all secrets/service account in the namespace/cluster #454

I think that we're already doing this for the GitHub & GitLab interceptors; for them to work the EL Pod must have access to all Secrets in the namespace. So, I think the security concern here probably applies to all Interceptors as a whole.

**Comment by dibyom** [comment]
Fixed by #492
