### ISSUE TITLE
Add a debug interceptor

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/triggers#491]
# Expected Behavior
This is a feature request. It would be nice to have a stock interceptor in triggers that one could deploy and use to debug, namely dump the payload and headers to the log.
 
# Actual Behavior
It can be hard to troubleshoot format / content issues in the payload if one does not control the source.

**Comment by bigkevmcd** [comment]
What would you like this to look like?

Logging of headers and payload?

I've seen GitHub hook events with a payload over 1.5MiB, dumping those in log the isn't cheap.

**Comment by bigkevmcd** [comment]
My first thought was something similar to https://golang.org/pkg/net/http/httputil/#DumpRequest

**Comment by ncskier** [comment]
As an alternative idea, could we add a debug log line in the EventListener sink that prints the information that you want (payload & headers)?

Then, to view this information, you could change the logging ConfigMap `config-logging-triggers` to `debug` to enable these logs (`loglevel.eventlistener: debug`). We have some information about this in the docs [here](https://github.com/tektoncd/triggers/blob/master/docs/eventlisteners.md#logging).

**Comment by bigkevmcd** [comment]
Or another option, would be a webhook interceptor that just returned 200 and headers/bodies after logging out the fields you wanted

**Comment by jmcshane** [comment]
@afrittoli I'd love to have something like this as well. With the new interceptor capabilities, this could be deployed as a separate service in an eventlistener namespace easily. I think I could implement in a separate repo for now, and then we can figure out where it would live in tekton.

**Comment by afrittoli** [comment]
Thanks @jmcshane - I'd love to see this one in experimental or in plumbing.
