### ISSUE TITLE
PortForward in e2e test is brittle

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#496]
In /test/eventlistener_test.go TestEventListenerCreate, we port forward to the EventListener sink. To do this, we exec out to kubectl and sleep for a few seconds. A more robust way would be to use something like https://godoc.org/k8s.io/client-go/tools/portforward

/area testing
/kind cleanup

**Comment by NavidZ** [comment]
I wanted to take a stab at this. @dibyom qq regarding this. When I run this test locally it fails [here](https://github.com/tektoncd/triggers/blob/master/test/eventlistener_test.go#L425) as is. I was just wondering whether something is wrong with my setup or is that the flakiness you are referring too. I feel like it is probably my setup as it always fails.

**Comment by dibyom** [comment]
Thanks for looking into this @NavidZ I just tried it on my setup (test running locally, pointing to a GKE cluster running 1.15.9-gke.24) and it works. So, I'm guessing it is probably related to your setup.

What is the response status code when it fails? Maybe we could try printing out the whole request?

**Comment by NavidZ** [comment]
It was actually accepting the request with 202 which was not expected.
For the time being I just returned right before that error (as there was another request before it and it was passing anyway), so I could test the port forwarding logic that happens earlier and I sent a PR for it. Btw, I'm new to both Go and this project. So I wasn't sure for example whether I should have committed the vendor folder along with this change or not. But feel free to comment on the PR.

**Comment by NavidZ** [comment]
> GKE cluster running 1.15.9-gke.24) and it works. So, I'm guessing it is probably related to your setup.

Regarding the test I was trying to run it against a locally run cluster with 1.16. When I switched to GKE it started working and passed the whole test. I'm looking into the bot failures on the PR. But I need to maybe dig a little deeper later to see if everything can also easily work with say a docker desktop k8s instance.
