### ISSUE TITLE
Update ingress and webhooks tasks to v1beta1

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#499]
# Expected Behavior
docs/create-ingress.yaml and docs/create-webhook.yaml should be v1beta1 tasks.

# Actual Behavior
They are v1alpha1 tasks

# Additional Info
The biggest change is probably switching the params/resources from inputs.params to just params.

cc @ncskier @akihikokuroda 
/kind cleanup

**Comment by ncskier** [comment]
Do we know if people are using these? Also, should they be moved to the [Tekton Catalog](https://github.com/tektoncd/catalog)?

**Comment by dibyom** [comment]
Yeah moving them to the Catalog is a good idea 💯

**Comment by akihikokuroda** [comment]
I'll do this in 3 steps (pullrequest):
1. Change the create_ingress.yaml and create_webhook.yaml in the triggers/docs
2. Create these tasks in catalog
3. Change the triggers/docs/README.md, triggers/docs/exposing-eventlisteners.md and triggers/docs/getting-started/README.md. Delete the  create_ingress.yaml and create_webhook.yaml in the triggers/docs
