### ISSUE TITLE
Get unit tests running against PRs

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/triggers#5]
## Expected behavior

Every PR should have all unit tests (i.e. `go test ./...`) executed against it.

## Actual behavior

We don't have any code, or any automation :O

## Additional info

* [This is the config for the Pipeline unit tests](https://github.com/tektoncd/plumbing/blob/33ee852094dd0f62f95a92e49d9a3c189729c1ca/prow/config.yaml#L431) <-- for now we should probably just copy this and do exactly what it does
* The config that prow uses to determine what to run against what repo is in [this config.yaml](https://github.com/tektoncd/plumbing/blob/master/prow/config.yaml) and the instructions for updating it are [in this readme](https://github.com/tektoncd/plumbing#prow) (you might need the assistance of someone with cluster access to apply the config)

**Comment by vtereso** [comment]
@vdemeester has already pushed the https://github.com/tektoncd/triggers/blob/master/test/presubmit-tests.sh file, which handles `go test` using the defaults in the tektoncd/plumbing repo
