### ISSUE TITLE
[webhook] No v0.4.0 tagged image ?

### ISSUE THREAD

**Issue by eddycharly** [tektoncd/triggers#534]
There is no `v0.4.0` image available for webhook ?

Looking at [gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/webhook](gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/webhook) there doesn't seem to be an image with the `v0.4.0` tag, though tags for other versions are available.

**Comment by dibyom** [comment]
@eddycharly I've manually added the tags for now. 

I'm guessing something with wrong with the tagging mechanism in the Task that we use for the release. It added the latest tag but not the version tag (https://github.com/tektoncd/triggers/blob/master/tekton/publish.yaml#L134).

**Comment by eddycharly** [comment]
Thanks @dibyom 
Dis you add the tag on other images also ? I forgot to update the issue but it was missing on controller and eventlistenersink images too.

**Comment by dibyom** [comment]
Yes, I tagged all 3!

**Comment by eddycharly** [comment]
Perfect 👍 
Thank you !

**Comment by dibyom** [comment]
Re-opening since this was found in v0.5.0 as well
