### ISSUE TITLE
TriggerBinding doesn't support params of Array type

### ISSUE THREAD

**Issue by savitaashture** [tektoncd/triggers#545]
# Expected Behavior
TriggerBinding should not expect params of array type 

# Actual Behavior
TriggerBinding allow user to provide params of array type 

# Steps to Reproduce the Problem

1. Create a triggerbinding by providing params with array type
2. TriggerBinding create successfully 

# Additional Info
For more info https://github.com/tektoncd/triggers/pull/543#issuecomment-616490309 , https://github.com/tektoncd/triggers/pull/543#issuecomment-616638153

**Comment by dibyom** [comment]
From the WG today, we decided that we'll keep Params in bindings to only strings for now. In #532, we'll start using our own Param types that only have string values so there should be any confusion!

/close
