### ISSUE TITLE
Rework TriggerBindingSpec

### ISSUE THREAD

**Issue by vtereso** [tektoncd/triggers#56]
Currently, the TriggerBindingSpec is defined as follows:
```go
// +k8s:deepcopy-gen=true
type TriggerBindingSpec struct {
	TemplateBindings []TemplateBinding `json:"templatebindings,omitempty"`
}

// +k8s:deepcopy-gen=true
type TemplateBinding struct {
	TemplateRef TriggerTemplateRef   `json:"templateref,omitempty"`
	Event       TriggerTemplateEvent `json:"triggertemplateevent,omitempty"`
	Params      []pipelinev1.Param   `json:"params,omitempty"`
}
```
This means we have multiple _distinct_ event bindings within a `TriggerBinding`. Currently, we have a one-to-many mapping from `EventListener` to `TriggerBinding` and well as a one-to-many mapping from `TriggerBinding` to `TriggerTemplates`. As I understood it, we wanted to support this? 

I believe this may not be the best design decision after consideration for issues like [naming modifiers](https://github.com/tektoncd/triggers/issues/50). To be brief, there will be no way to refer to resources being generated between templates (on the same `TriggerBinding`).

**Comment by ncskier** [comment]
From what I understood, I thought we wanted a one-to-one mapping between TriggerBinding and event; for example a TriggerBinding cannot have a `push` event and `pull_request` event, it can only have one of them. I've created a PR [here](https://github.com/tektoncd/triggers/pull/57) to address this. Please let me know if this changes functionality in a negative way.

**Comment by ncskier** [comment]
I think this was resolved under issue https://github.com/tektoncd/triggers/issues/55
