### ISSUE TITLE
Release Triggers v0.5.0

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#563]
# Steps
1.  Publish release candidate build followingI v0.5.0-rc1: https://github.com/tektoncd/triggers/tree/master/tekton#create-an-official-release
1.  Organize the release notes in the draft release
1. Wait for feedback for 1-2 days
1. If there are no major issues, publish a v0.5.0 build https://github.com/tektoncd/triggers/tree/master/tekton#create-an-official-release

1. Post a message on Slack

1. Fill out release [retrospective](https://docs.google.com/document/d/1sfLRvTaksSCKjjjTZ5904715W4jWkkR7ap2v-AGPKlM/edit#)

**Comment by dghubble** [comment]
Thanks for the great work!

Minor feedback: Its small, but having the Github releases and tagged image availability aligned would probably help get more eyes on release candidates. We detect new releases, but have to manually check gcr.io and inspect example yaml to find the specific images you're intending to use.

**Comment by dibyom** [comment]
@dghubble yeah, that definitely isn't intentional. Sounds like a bug. Will investigate.

**Comment by dibyom** [comment]
Ok, got to the bottom of the problem - our release task tags the regional registires (us.gcr.io, eu.gcr.io, asia.gcr.io) but not the global one i.e. gcr.io.
