### ISSUE TITLE
payload signature check failed

### ISSUE THREAD

**Issue by xishengcai** [tektoncd/triggers#567]
# Expected Behavior
when github push, not normal trigger pipline
# Actual Behavior
{"level":"error","logger":"eventlistener","caller":"sink/sink.go:210","msg":"payload signature check failed","knative.dev/controller":"eventlistener","/triggers-eventid":"wlnbz","/trigger":"github-interceptor","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.executeInterceptors\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:210\ngithub.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:147\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:97"}
# Steps to Reproduce the Problem

# Additional Info
webhook-run run success completed

**Comment by dibyom** [comment]
hello, could you provide some more info. Would be helpful to know what the EventListener configuration is.

The error is "msg":"payload signature check failed" so I'm guessing you are using the GitHub interceptor...perhaps the secret used to validate is not correct?
