### ISSUE TITLE
Use Knative to create an EventListener Pod

### ISSUE THREAD

**Issue by savitaashture** [tektoncd/triggers#571]
Currently triggers use Kubernetes resources to create EventListener pod and services with this existing solution how are we addressing some of the below scenario  
1. How Autoscale achieved if there are multiple requests ?
2. How to manage resources when EL pod is in idle state ?
3. Which solution are we going to use to expose EL pod as discussed in this [issue](https://github.com/tektoncd/triggers/issues/351)
as EventListener pod has been created by Kubernetes resources

To achieve the above listed case we can use **Knative** to create an EventListener pod which by default address all those out of the box
1. Autoscale
2. Efficient resource management 
3. Exposing endpoints 

**Note**
For `Trigger-Knative` integration right now i can see one of the difficulty is dependency on Knative

**Comment by savitaashture** [comment]
Initial discussion draft : https://docs.google.com/document/d/1GtCfpzgGFPt224A7xNE5sjN8REytytmNL8E9oXAk4Uc/edit

**Comment by dibyom** [comment]
/lifecycle frozen

Part of Roadmap and has been proposed in TEP-008

**Comment by dibyom** [comment]
I think we can close this out now?
