### ISSUE TITLE
Accept knative trigger event to eventListener

### ISSUE THREAD

**Issue by llhhbc** [tektoncd/triggers#575]
# Expected Behavior
I can receive event from knative eventing, and post msg to eventListener to do trigger.

# Actual Behavior
EventListener  can only accept http request, but not knative event.

# Steps to Reproduce the Problem

# Additional Info

**Comment by dibyom** [comment]
> EventListener can only accept http request, but not knative event.

Does knative not emit HTTP cloudevents? I was under the impression that they do. If so, the event listener should be able to handle them

**Comment by llhhbc** [comment]
@dibyom Knative event trigger can only send Get request, and can't send with head and body. Knative event trigger can send cloudEvent to service, but EventListener can't deal.

**Comment by rektide** [comment]
@llhhbc what's the status of those neat [eventadapters](https://github.com/llhhbc/triggers/commit/5d9ea8903d976917f6da250bdb36efd0fdfd15b2) you were working on? should i continue to track this ticket or is there something else to follow too? cool effort thanks good luck.

**Comment by vdemeester** [comment]
Note, @savitaashture is working on this too, see
- [duck-typing on tektoncd/triggers](https://hackmd.io/Y-Gmz1rpTCWcrGuNXINH8A)
- [Use knative for eventlistener pod](https://docs.google.com/document/d/1GtCfpzgGFPt224A7xNE5sjN8REytytmNL8E9oXAk4Uc/edit)
