### ISSUE TITLE
Change event listener port

### ISSUE THREAD

**Issue by sebgoa** [tektoncd/triggers#586]
question:

Is it possible to change the event listener port ?

Right now it serves on 8080, I would like to change it to 80.  Editing the services and setting the port does not work (I guess the controller is overriding it)

**Comment by ncskier** [comment]
Unfortunately, I don't think this is an officially supported feature. However, you could modify your Tekton Triggers controller deployment called `tekton-triggers-controller` to change the [`-el-port`](https://github.com/tektoncd/triggers/blob/master/config/controller.yaml#L59) to 80:
```yaml
          "-el-port", "8080",
```

I don't think that this has been thoroughly tested, so I'll mark this issue as a feature request 👍 

/kind feature

This is related to https://github.com/tektoncd/triggers/issues/505, which is also about customizing the EventListener Service/Deployment.
