### ISSUE TITLE
Get end to end tests running against PRs

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/triggers#6]
## Expected behavior

Every PR should have all end to end tests (i.e. tests in the `test` dir which use [the `e2e` build label](https://github.com/tektoncd/pipeline/blob/master/test/README.md#running)) executed against it.

## Actual behavior

We don't have any code, or any automation :O

## Additional info

* [This is the config for the Pipeline end to end tests which are called "integration tests" in this config](https://github.com/tektoncd/plumbing/blob/33ee852094dd0f62f95a92e49d9a3c189729c1ca/prow/config.yaml#L465) <-- for now we should probably just copy this and do exactly what it does
* The config that prow uses to determine what to run against what repo is in [this config.yaml](https://github.com/tektoncd/plumbing/blob/master/prow/config.yaml) and the instructions for updating it are [in this readme](https://github.com/tektoncd/plumbing#prow) (you might need the assistance of someone with cluster access to apply the config)

**Comment by vtereso** [comment]
Thanks again to @vdemeester for setting this up [here](https://github.com/tektoncd/plumbing/blob/master/prow/config.yaml#L703)

**Comment by ncskier** [comment]
Closing this issue because of the previous comment, and PR https://github.com/tektoncd/triggers/pull/18 adds a basic e2e test for `ko apply -f config/`
