### ISSUE TITLE
Trigger - Event 

### ISSUE THREAD

**Issue by 2020testuser** [tektoncd/triggers#604]
Hi,
Just started looking at trigger.

Could you please clarify on the below?

1. Does  tekton trigger uses Prow or Lighthouse internally?

2. If  tekton trigger doesn't use Prow or Lighthouse internally, does all its 3 components handle webhook?

Thanks in advance!

**Comment by wlynch** [comment]
Tekton Triggers does not use Prow or Lighthouse for its handling of webhooks.

- Interceptors allow you to filter / validate incoming webhooks.
- TriggerBindings allow you to extract information out of incoming events (e.g. branch, commit information)
- TriggerTemplates allow you to specify the Tekton Pipelines resources you want to create in response to the Trigger.

For more information, check out the docs! https://github.com/tektoncd/triggers/tree/master/docs
