### ISSUE TITLE
Triggers with webhooks

### ISSUE THREAD

**Issue by 2020testuser** [tektoncd/triggers#605]
Hi,
Could anyone please clarify on the below?

1. Does tekton triggers internally use prow?

2. Can lighthouse be used  with tekton triggers ? If so, are there any samples/information on this?

3. Can prow be used with tekton triggers (if ans for 1 is no) ?
If so, are there any samples/information on this?
Thanks !

**Comment by 2020testuser** [comment]
Can anyone please provide details for the above? Looking for some information to get started. Thanks in advance!

**Comment by dibyom** [comment]
> Does tekton triggers internally use prow?

No, we don't

> Can lighthouse be used with tekton triggers ? If so, are there any samples/information on this?

This lighthouse? https://github.com/jenkins-x/lighthouse#lighthouse 
I don't know a lot about it but I haven't heard of anyone using them together yet.

> Can prow be used with tekton triggers (if ans for 1 is no) ?

Is the use case triggering ProwJobs using TektonTriggers? If so, then the answer is no. Right now, Triggers is limited to creating only Tekton resources (though being able to create other resources has come up from time to time)

**Comment by 2020testuser** [comment]
@dibyom - Thank You! This helps.
