### ISSUE TITLE
Interceptors should be able to "pass" on a result

### ISSUE THREAD

**Issue by bigkevmcd** [tektoncd/triggers#612]
# Expected Behavior

Currently, if an interceptor returns an error, it causes the trigger to stop processing, and it's logged out as an error.

https://github.com/tektoncd/triggers/blob/master/pkg/interceptors/github/github.go#L87
https://github.com/tektoncd/triggers/blob/master/pkg/interceptors/cel/cel.go#L89

These are not really "errors" as such, and it can be a bit alarming to see them logged out as such.

Perhaps, like `io.EOF` we should have a marker error (or specific error type) that indicates "stop processing".

# Actual Behavior

The errors are logged out as errors

# Steps to Reproduce the Problem

1. Curl a request body with a different event-type than is allowed for in the GitHub/CEL/GitLab configuration, and an error is logged out.

# Additional Info

**Comment by dibyom** [comment]
seens related to: https://github.com/tektoncd/triggers/issues/336

**Comment by bigkevmcd** [comment]
@dibyom ooops, yes, I should've remembered that one :-)

I'm happy to close this out
