### ISSUE TITLE
how to get poll scm like jenkins?

### ISSUE THREAD

**Issue by zgfh** [tektoncd/triggers#626]
because my network limit, I can not use github webhook 
this is a way like jenkins poll scm to check git change ?

# Additional Info
https://stackoverflow.com/questions/41114251/what-is-the-difference-between-poll-scm-build-periodically-in-jenkins/41114307

**Comment by TomaszKlosinski** [comment]
As far a I know, it's not possible currently with Tekton Triggers.

**Comment by khrm** [comment]
@zgfh 
There's no way to do using only Triggers You can solve this problem in the following steps: 

1. Write a k8s cronjob which checks for git repo change.
https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/
2. When the job finds any changes, it sends a request with payload to EventListener.
3. Now EventListener can execute the Triggers and create resources.

**Comment by zgfh** [comment]
@khrm @TomaszKlosinski thanks
