### ISSUE TITLE
Update Knative Dependencies to Align with Pipelines

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/triggers#627]
# Expected Behavior

To be able to deploy triggers without issues.

# Actual Behavior

On some distributions of Kubernetes, the following error can occur due to the version of Knative dependencies used by triggers:

```
tekton-triggers-controller {"level":"fatal","logger":"controller","caller":"sharedmain/main.go:149","msg":"Version check failed","error │
│ ":"kubernetes version \"\" is not compatible, need at least \"v1.15.0\" (this can be overridden with the env var \"KUBERNETES_MIN_VERSI │
│ ON\")","stacktrace":"knative.dev/pkg/injection/sharedmain.MainWithConfig\n\tknative.dev/pkg@v0.0.0-20200207155214-fef852970f43/injectio │
│ n/sharedmain/main.go:149\nknative.dev/pkg/injection/sharedmain.MainWithContext\n\tknative.dev/pkg@v0.0.0-20200207155214-fef852970f43/in │
│ jection/sharedmain/main.go:114\nknative.dev/pkg/injection/sharedmain.Main\n\tknative.dev/pkg@v0.0.0-20200207155214-fef852970f43/injecti │
│ on/sharedmain/main.go:98\nmain.main\n\tgithub.com/tektoncd/triggers@/cmd/controller/main.go:32\nruntime.main\n\truntime/proc.go:203"}
```

The workaround is to set the `KUBERNETES_MIN_VERSION` environment variable on the deployments for the triggers controller/webhook to be the version of the cluster being used. This was also previously a problem for pipelines as well before https://github.com/tektoncd/pipeline/pull/2721. 

The error comes from how the server version is validated [here](https://github.com/tektoncd/triggers/blob/700e5df278fba2f8163b245726499b9492ac91ee/vendor/knative.dev/pkg/version/version.go), which has been [updated in pipelines](https://github.com/tektoncd/pipeline/blob/1de0c3e919e7ddddd2c8ac16b4df035236925539/vendor/knative.dev/pkg/version/version.go).

Is there any reason for building around the Knative dependencies currently used?

/kind bug

**Comment by dibyom** [comment]
> Is there any reason for building around the Knative dependencies currently used?

Not that I'm aware of. We just need to bump our dependencies!
