### ISSUE TITLE
Pick up genreconciler

### ISSUE THREAD

**Issue by mattmoor** [tektoncd/triggers#635]
I did this for pipelines, and can either help or guide this here, but the general idea is that you can decorate types with:

```
// +genreconciler
```

... and we will generate a type reconciler shell for it, which hold most of Knative's upstream controller best practices.

You can see an example of this migration [here](https://github.com/tektoncd/pipeline/pull/2771).

It's also notable that if you jump all the way forward (https://github.com/tektoncd/pipeline/pull/2846 👀 ) you will also start having the ability to enable fine-grained leader election and sharded reconciliation with little-to-no code changes 🤩 

cc @vdemeester @afrittoli @ImJasonH

**Comment by dibyom** [comment]
I think this might also address #627 

I'll try to pick this up next week...unless someone beats me to it 😉

**Comment by dibyom** [comment]
I made some progress here: https://github.com/tektoncd/triggers/compare/master...dibyom:genreconciler?expand=1

I still need to fix up some of our reconciler tests that were testing unexported functions
