### ISSUE TITLE
CEL feature: string casing functions

### ISSUE THREAD

**Issue by bitsofinfo** [tektoncd/triggers#638]
Would be great to have toUpper, toLower etc for strings

https://github.com/google/cel-go/issues/370

**Comment by bigkevmcd** [comment]
This is waiting on a new release of google/cel-go with the functionality.

**Comment by bigkevmcd** [comment]
@TristonianJones any chance of a release of cel-go with the strings library?

**Comment by TristonianJones** [comment]
I can put together a release today if that works for you.

**Comment by TristonianJones** [comment]
Actually, the v0.5.0 should have the strings library in it I think.

**Comment by bigkevmcd** [comment]
@TristonianJones Sorry, I should've been clearer, it's really the upper/lower casing things I'm looking for https://github.com/google/cel-go/pull/372

A release would be great, thank you

**Comment by TristonianJones** [comment]
@bigkevmcd I just realized it was the upper/lower. I'll get that sorted out for you.

**Comment by TristonianJones** [comment]
https://github.com/google/cel-go/releases/tag/v0.6.0
