### ISSUE TITLE
Unable to create Event Listener without ref and spec included in YAML.

### ISSUE THREAD

**Issue by wajid-poernomo** [tektoncd/triggers#639]
# Expected Behavior

I've followed the instructions in:

https://github.com/tektoncd/triggers/blob/master/docs/getting-started/README.md

working off the files in master.

I expect to be bale to run the following command to create a triggertemplate, triggerbinding and eventlistener.

# Actual Behavior

Get the following error:

triggertemplate.triggers.tekton.dev/getting-started-triggertemplate unchanged
triggerbinding.triggers.tekton.dev/getting-started-pipelinebinding unchanged
Error from server (BadRequest): error when creating "./docs/getting-started/triggers.yaml": admission webhook "validation.webhook.triggers.tekton.dev" denied the request: validation failed: expected exactly one, got neither: spec.triggers[0].bindings[0].Ref, spec.triggers[0].bindings[0].Spec

# Steps to Reproduce the Problem

1. Run kubectl apply -f ./docs/getting-started/pipeline.yaml
2. kubectl apply -f ./docs/getting-started/triggers.yaml
3. Results in error unless **ref** and **spec** are included in the EventListener spec.triggers[0].bindings[0] section.

# Additional Info

**Comment by wajid-poernomo** [comment]
[

](url)

**Comment by dibyom** [comment]
hi @wajid-poernomo which version of Triggers are you using?

**Comment by dibyom** [comment]
Ahh, I see our getting-started EventListener still uses `name` instead of a `ref` to refer to bindings.

/kind bug
