### ISSUE TITLE
CEL feature: URL extension

### ISSUE THREAD

**Issue by andrey-carerix** [tektoncd/triggers#640]
To make a secure integration with Bitbucket Cloud it is necessary to inspect the incoming webhook URL query parameters to extract pre-shared secret value (e.g. https://mywebhook/?token=icWo3SV9lbx0lm4n) to be validated with existing CEL extension function compareSecret.

**Comment by dibyom** [comment]
Hi @andrey-carerix we recently added a `parseURL()` function in https://github.com/tektoncd/triggers/pull/591
I think that should do the trick?
/kind question

**Comment by andrey-carerix** [comment]
@dibyom yes, I am aware of that function. But it's meant to parse some attributes within the json body. I am looking for a way to get a reference to the URL the webhook listener was invoked with by a callee (e.g. bitbucket cloud service). Basically URL extension that gives me access to the original HTTP request URL object similar to what body and header extensions provide.

**Comment by dibyom** [comment]
ahh I see, we need to expose the url as well as the body and headers

**Comment by andrey-carerix** [comment]
@dibyom exactly. Here is the real-life use case to support this feature request:

- bitbucket cloud has a webhook configured with a secret as query parameter, e.g. https://mywebhook/?token=icWo3SV9lbx0lm4n. Note: unlike bitbucket server there is no other way to secure your webhook endpoint other than bake a pre-shared secret as URL query parameter.
- bitbucket cloud invokes the above webhook URL whenever a change occurs in git repo
- tekton eventlistener with CEL interceptor receives the incoming HTTP request from bitbucket cloud 
- cel filter is configured to read the query parameter 'token' and match it against k8s secret to verify the authenticity of the webhook request

The desired behaviour as pseudo CEL expression:

`url.query('token').compareSecret('namespace', 'bitbucket-secret', 'tokenKey') `

**Comment by dibyom** [comment]
yeah, currently we have `$(body)` and `$(header)`. We can add a `$(url)` or `$(fullUrl)` field that is accessible to the bindings.
