### ISSUE TITLE
CEL expressions, debugging, better error messages

### ISSUE THREAD

**Issue by bitsofinfo** [tektoncd/triggers#641]
Here is one of the more common error messages I get in CEL interceptors that do a `filter`

```
{"level":"error","logger":"eventlistener","caller":"sink/sink.go:145","msg":"error making the evaluation context: invalid character 'p' looking for beginning of value","knative.dev/controller":"eventlistener","/triggers-eventid":"4zzsm","/trigger":"my-triggered-deploy-v1-interceptor","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\tgithub.com/tektoncd/triggers@/pkg/sink/sink.go:145\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\tgithub.com/tektoncd/triggers@/pkg/sink/sink.go:93"}
```

Its pretty cryptic, i don't know if its a problem w/ my filter, or the input. Leads to a lot of trial and error time. None of my inputs start with `p`

**Comment by dibyom** [comment]
cc @bigkevmcd

**Comment by bigkevmcd** [comment]
Can you provide an example of the sort of expression that's generating that.

Generally, we return the error that CEL is giving back, I could include the expression that failed in the error return.

**Comment by bitsofinfo** [comment]
yes including the expression back in the log would definitely aid and save some time.  I get it occasionally during dev for all sorts of expressions where there might be a typo or unexpected data etc.

**Comment by bigkevmcd** [comment]
@bitsofinfo do you think the changes in #646 will help.

I had another look at the log entry...

`{"level":"error","logger":"eventlistener","caller":"sink/sink.go:145",
"msg":"error making the evaluation context: invalid character 'p' looking for beginning of value",
"knative.dev/controller":"eventlistener","/triggers-eventid":"4zzsm",
"/trigger":"my-triggered-deploy-v1-interceptor",
"stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\tgithub.com/tektoncd/triggers@/pkg/sink/sink.go:145\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\tgithub.com/tektoncd/triggers@/pkg/sink/sink.go:93"}
`

And I was able to determine that it was during the parsing of the JSON body, the error you should see now will look like this https://github.com/tektoncd/triggers/pull/646/files#diff-c2aa50129ed591836d448804e0c09a19R173

**Comment by bitsofinfo** [comment]
yes, the more info the better, thx!

**Comment by dibyom** [comment]
@bigkevmcd Is there more we can do here short term or can we close this given we now add the expression that failed in the logs as well

**Comment by bigkevmcd** [comment]
@dibyom I don't think so, if cel-go develops debugging functionality, I'd definitely incorporate that, but otherwise, I can't see what else we could add.

**Comment by dibyom** [comment]
Based on @bigkevmcd 's comment above I'm going to close this issue. We can revisit later if CEL adds additional debugging facility.
