### ISSUE TITLE
CEL doc: compareSecret: parameter description needed

### ISSUE THREAD

**Issue by bitsofinfo** [tektoncd/triggers#643]
https://github.com/tektoncd/triggers/blob/master/docs/cel_expressions.md

The `compareSecret` functions just say `<string>.compareSecret(string, string, string) -> bool` leaving the reader with no clue as to which parameter is what.... 3 args, but i don't know which one is the secret sub key/prop to be used, which is the secret name and which is the namespace. Its clearly described here: https://github.com/tektoncd/triggers/blob/5348837b14624898ff67b1e7c4b72a6f03982415/pkg/interceptors/cel/triggers.go#L107

**Comment by bigkevmcd** [comment]
It's _partially_ a rendering issue https://tekton.dev/docs/triggers/cel_expressions/ renders the table in a better way (you can see the example).

But I'll look at what I can do there, balancing the output, with the common-format for CEL documentation.

**Comment by TristonianJones** [comment]
@bigkevmcd those docs look great. If you'd like improvements on the CEL documentation I'm happy to take a FR and any pro-tips you have to offer for syncing docs between API reference and implementation.

**Comment by bigkevmcd** [comment]
@TristonianJones Thank you, that's mostly a copy and paste and post-edit.

If there are any better ways, I'd be up for it (or contributing to).

If you had time to look over the way CEL is used in triggers, and spot any issues, I'd be really grateful :-)

**Comment by bigkevmcd** [comment]
@bitsofinfo can you say a bit more about what more you’re looking for?

**Comment by dibyom** [comment]
I think we can just update the Description column with what the 3 param values are?
