### ISSUE TITLE
Support secure connection between service to EventListener pod

### ISSUE THREAD

**Issue by savitaashture** [tektoncd/triggers#650]
# Expected Behavior
Supporting secure connection between EventListener service to pod.

# Actual Behavior
Currently we can achieve secure connection till ingress/service but cannot achieve secure connection from service to eventlistener pod. 

# Additional Info
Trigger should support end to end secure connection within and outside the cluster which helps a lot in security requirements.

/kind feature

**Comment by verokarhu** [comment]
Wouldn't this be solved by deploying a service mesh?

**Comment by savitaashture** [comment]
> Wouldn't this be solved by deploying a service mesh?

Hey @verokarhu sorry for the late reply

Yes that is one option but with that we will have dependency on thirdparty installation

And as part of this we are planning to support https connection to eventlistener pod as an inbuilt feature

**Comment by csantanapr** [comment]
This is great to see that is being worked on. 👍 

I know about Istio but is a too heavy requirement for a simple use case where OpenShift Ingress Route comes with reencrypt and passthrough out of the box.

I'm using tekton via a downstream of OpenShift Pipelines, and the enterprise client wants a solution that goes along the same way OpenShift deals with this using Route reencrypt and passthrough

**Comment by csantanapr** [comment]
Yay 🎉 haply to see implemented
