### ISSUE TITLE
Add securityContext Option for PodTemplates

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/triggers#654]
# Expected Behavior

I should be able to specify a `securityContext` to run containers as a non root user when I create an EventListener. This issue is a result of using a Kubernetes cluster that enforces containers being run as non root:

```
Error: container has runAsNonRoot and image will run as root
```

The container image running as root is `gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/eventlistenersink:v0.6.0`.

# Actual Behavior

```
admission webhook "webhook.triggers.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "securityContext"
```

At this point, the main workaround is to give elevated permissions to a serviceaccount associated with the EventListener. 

/kind bug

**Comment by jorgemoralespou** [comment]
Or maybe the image shouldn't need to be run as run.

**Comment by vdemeester** [comment]
For what is worth, it should be possible for those to not be run as root, see https://github.com/tektoncd/pipeline/pull/2606 for the same thing done on pipeline.

**Comment by danielhelfand** [comment]
Yes, if it can be run as nonroot, I think that’s the better approach here. 

But in general, I still can’t help but feel there should be more pod template options for EventListeners. However, perhaps we can wait for those use cases to reveal themselves as other issues.

**Comment by ibexmonj** [comment]
i ran into the same issue with `EventListerner` in my PSP enabled namespace. 

Any workarounds here ?

**Comment by danielhelfand** [comment]
@ibexmonj I believe this should be resolved in v0.7.0 of triggers after updating triggers images to use a non root base image: https://github.com/tektoncd/triggers/pull/672.

If upgrading is not an option, you could assign privileged permissions to a ServiceAccount and associate that ServiceAccount with the EventListener.

**Comment by ibexmonj** [comment]
Thanks @danielhelfand. we are on 0.3.1 to ensure kubernetes version compatibility. i was going to try setting a rolebinding up for the eventlisterner SA, just wanted to reach out here for an alternative. Thanks again

**Comment by savitaashture** [comment]
Hey @danielhelfand if nothing to be addressed as part of this issue can we close it ?

Because its hanlded by https://github.com/tektoncd/triggers/pull/672 as part of 0.7.0 release

**Comment by danielhelfand** [comment]
@savitaashture Yeah, I think it makes sense to close.

**Comment by tuananh** [comment]
runas non root is not enough for openshift, as they enforce the user id as well. any particular reason why we don't support `securityContext` in podTemplate?
