### ISSUE TITLE
EventListener return a 2xx status on failure

### ISSUE THREAD

**Issue by khrm** [tektoncd/triggers#656]
When I test a trigger and it fails, the event listener pod logs messages with a level: error. But the status code returned by the event listener is in the 2xx range which is confusing. Github seems to think that the web hooks worked.

# Expected Behavior
In case of an error, the event listener should return a status code in the 500's

# Actual Behavior
In Github, I can see that the webhook was executed after a push but despite receiving messages like the following with a "level" of "error", the event listener returns a status code in the 200's which seems like a success until you dig into the logs.

{"level":"error","logger":"eventlistener","caller":"sink/sink.go:164","msg":"failed to ApplyEventValuesToParams: failed to marshal event: failed to unmarshal request body: invalid character 'p' looking for beginning of value","knative.dev/controller":"eventlistener","/triggers-eventid":"75t66","/trigger":"","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\t/opt/app-root/src/go/src/github.com/tektoncd/triggers/pkg/sink/sink.go:164\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\t/opt/app-root/src/go/src/github.com/tektoncd/triggers/pkg/sink/sink.go:97"}
{"level":"error","logger":"eventlistener","caller":"sink/sink.go:164","msg":"failed to ApplyEventValuesToParams: failed to replace JSONPath value for param pusher-name:

{string $(body.name) []}
: name is not found","knative.dev/controller":"eventlistener","/triggers-eventid":"wz9kj","/trigger":"","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\t/opt/app-root/src/go/src/github.com/tektoncd/triggers/pkg/sink/sink.go:164\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\t/opt/app-root/src/go/src/github.com/tektoncd/triggers/pkg/sink/sink.go:97"}

# Steps to Reproduce the Problem

1. Created a sample task. I replaced the $(input.params.appName) by a string to output hello world and removed the parameter appname
2. Created a pipeline with this task alone
3. Added a trigger using the "Add Trigger" option
4. Used the provided url in my Github repository that I use to test the trigger (https://github.com/joellord/triggertest)
5. Use format form-urlencoded in the Github web hook configuration to force an error
Test the hook

# Additional Info
Reported by: Joel Lord

**Comment by dibyom** [comment]
Yeah, this is confusing behavior. But I'm not convinced we should return a 5xx in this scenario. 

The error here seems to be forced by sending form-urlencoded bodies instead of JSON. This is something we explicitly do not support. So, IMO, a 4xx makes a better return code than 5xx here.

The best practices for integrating with GithHub webhook states that 5xx should be reserved for catastrophic scenarios and using 2xx to "to acknowledge receipt of payload that won't be processed".

https://developer.github.com/v3/guides/best-practices-for-integrators/#use-appropriate-http-status-codes-when-responding-to-github

**Comment by khrm** [comment]
Yes, 4xx makes sense to me also.
