### ISSUE TITLE
Trigger controller managed multi-eventlistener service

### ISSUE THREAD

**Issue by skaegi** [tektoncd/triggers#681]
When I create a new EventListener in a namespace I would like the trigger controller to handle the service handling bits instead of generating a new Pod.

At a high-level this would mean:
1) The controller runs an http service where all events are delivered (I'll call it trigger-svc for now)
2)  When an EventListener is created, the controller will create a Service in the EventListener's namespace with a unique name based on the EL uid, but the Service will be an ExternalName service that points back to the controller run instance -- e.g. trigger-svc.tekton-pipelines.svc.cluster.local
3) When an Event arrives for the "trigger-svc" it looks at the Host to figure out which EventListener to lookup and then runs the trigger logic as the ServiceAccount associated with the EventListener

Also see https://github.com/tektoncd/triggers/issues/456

**Comment by dibyom** [comment]
As discussed in yesterday's WG, this is similar to the "mode based" EventListener proposal (see the alternatives section in https://github.com/tektoncd/community/pull/148/files

**Comment by dibyom** [comment]
With @khrm 's Trigger CRD work (TEP-009); it should be possible to have a single cluster wide EventListener that can handle Triggers across multiple namespaces.
(The path based  triggers portion of the proposal should allow you to hit only a certain subset of triggers and not all of them).

Does this address your use case @skaegi ?
