### ISSUE TITLE
EventListener ServiceAccountName should default to... default

### ISSUE THREAD

**Issue by skaegi** [tektoncd/triggers#682]
In the docs -- https://github.com/tektoncd/triggers/blob/master/docs/eventlisteners.md#serviceaccountname -- it states that ServiceAccountName is required. In our environment an EventListener author would never know what ServiceAccounts are available so we would like to use "default" in this case or better still follow Tekton Pipelines logic -- https://github.com/tektoncd/pipeline/blob/db66eca6112d1c003e6b2ddb129858e829484c7f/docs/pipelineruns.md#specifying-custom-serviceaccount-credentials

**Comment by dibyom** [comment]
Using a default serviceAccountName from a `defaults` configMap sounds good to me.
The difference between the service account name in Pipeline vs Triggers is that while there are some use cases where the default SA makes sense (a task that needs no access to any secrets or anything) for Pipelines, in Triggers the SA must always have roles to create Task/PipelineRuns (which I don't think the default service account) has.

**Comment by juanri0s** [comment]
I can work on this!😁 Just let me know the route the team wants to go with this. I know a default option in a config is what was brought up above. 

Is this a new config or am I updating a keyvalue in an existing one?

**Comment by dibyom** [comment]
Awesome! We'd have to create a new configMap and add the key-value there.
The pipelines repo does something similar that you could use for inspiration: https://github.com/tektoncd/pipeline/blob/master/config/config-defaults.yaml

and 
https://github.com/tektoncd/pipeline/blob/master/pkg/apis/config/default.go

**Comment by juanri0s** [comment]
Okay I'm taking a look now.

I have it named as `defaults.yaml` with `defaults` name under config 

Are we okay with `tekton-pipelines` namespace? 

```yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: defaults
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
```

**Comment by dibyom** [comment]
I'd suggest calling it `triggers-defaults` instead of defaults

**Comment by juanri0s** [comment]
okay so apart from the config addition, do we have to set up anything to read from the default config values in the case where a SA isn't provided? I know you linked the pipeline `default.go` example but where are we expecting these methods to be called?

**Comment by dibyom** [comment]
There is a setDefaults method here: https://github.com/tektoncd/triggers/blob/master/pkg/apis/triggers/v1alpha1/event_listener_defaults.go#L24

We should check if the spec contains a serviceAccountName, if it doesn't we should add the default one

**Comment by juanri0s** [comment]
yupp that makes sense. Thank you for the info! Will add it in soon

**Comment by juanri0s** [comment]
Just wanted to give context into the issues I was running into/thinking. But if I'm taking too long or too off from the solution we want, maybe this is something I could pair with someone on?

The default yaml is fine.
The default.go file is fine.

I understand that when an `EventListenerTrigger` is given, it doesn't require a SA. So we need to read the default SA from the config. The two example links given made sense but the type for SA here is `corev1.ObjectReference` from the core API, which is looking for `kind, namespace, name, uid, API version, resource version, and field path` so apart from the `name` what would the other fields contain from this default? The way I think of it, we would be given an `EventListenerTrigger`, check if the SA is there, if not, read from config and grab the SA and set it.

There's also the issue of reading in the config itself. Here `defaultBindings` is just reading in constants for setting defaults, so we need to move over to a config approach so when I look at the examples provided from the pipelines project I don't see how the config is read in unless I missed something.

Once I figure out how the config read in. I assume it returns a (*Defaults, error), and then we can set the EventTrigger from those values.

**Comment by dibyom** [comment]
Hey @juanri0s sorry missed your last update. You brought up a good point. The SA for the EventListenerTrigger is an ObjectRef  -- (we are changing that in https://github.com/tektoncd/triggers/pull/705)

However, what I am thinking is we default not the [EventListenerTrigger SA](https://github.com/tektoncd/triggers/blob/master/pkg/apis/triggers/v1alpha1/event_listener_types.go#L91) but rather the [EventListener SA ](https://github.com/tektoncd/triggers/blob/master/pkg/apis/triggers/v1alpha1/event_listener_types.go#L55)(which acts as the default SA for all triggers in that Listener.

Hope that helps. If not, let me know and I'd be happy to pair next week!

**Comment by savitaashture** [comment]
@juanri0s hey friendly check
Are you still working on this issue?
If not i am interested to work as this is required for downstream project (Openshift)
