### ISSUE TITLE
Design for cron triggering

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/triggers#69]
# Expected Behavior

Folks will want to run Pipelines periodically, e.g. very night or every few hours they may want to trigger CI. Some use cases:

- To run long running Pipelines that take too long to run on every commit
- To pull in external changes on a regular basis (e.g. new versions of dependencies)
- To do nightly releases

# Actual Behavior

We've been discussing and designing solutions for event based triggering where the event comes from an external system like GitHub.

Hopefully this design will be super similar :D

# Additional Info

Definitely not something we need for our first milestone but ppl have been asking for it so we can track it here and ppl can add details if needed :D

**Comment by EliZucker** [comment]
Considering our current design is focused around HTTP requests, and all events don't necessarily come in that format, my understanding is that we will eventually end up having a separate event-adapter library (or will recommend lightweight adapter(s) that already exist; for example [vincent's github adapter](https://github.com/vincent-pli/gitlabsource/)). 

With this in mind, I think the best way to approach this is to have an adapter that will produce an HTTP event or CloudEvent when the cronjob is supposed to execute. Knative eventing has something similar [here](https://github.com/knative/eventing-contrib/tree/master/samples/cronjob-source), although it isn't as light on dependencies as we would like.

**Comment by vincent-pli** [comment]
Agree with @EliZucker , this part should not in the scope of `Trigger`. 
Any reason we don't leverage `Knative eventing` or `Knative contrib`? not light enough?
if so i guess we need consider to create tekton's event source repo.

**Comment by bobcatfish** [comment]
The solution could be that we recommend `Knative eventing`, I don't want to jump to any conclusions just yet!

Basically if I wanted to use Tekton as a complete CI solution (and I do! :D https://github.com/tektoncd/pipeline/issues/267) then I would need to be able to setup cron triggering somehow. And if I found the "triggering" part of the project but found no guidance about how to setup triggering based on the passage of time (i.e. cron) I'd be very frustrated.

So this issue is just to track that at the very least we should have docs to help users set this up - but we should also do some investigation and make sure we're happy with whatever we suggest (and decide what and if we want to implement anything ourselves).

**Comment by TheJaySmith** [comment]
One thing we could do is recommend third party sources such as Google Cloud Scheduler, or easy cron. 

also, you can declare cron jobs within [Kubernetes](https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/).

**Comment by cc189** [comment]
This feature will be very handy!
Maybe we can add
- `schedule` filed in `EventListener`'s spec
- `lastTriggeredTime` field in `EventListener`'s status

**Comment by vtereso** [comment]
Closing for now thanks to https://github.com/tektoncd/triggers/pull/162
