### ISSUE TITLE
Make instructions in DEVELOPMENT guide work

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/triggers#7]
# Expected behavior

Folks who try to follow along with our DEVELOPMENT.md should be able to actually run the commands.

(of course one way to meet this would be to delete the stuff we don't have yet, but I think it would put us in a great position to add all the supporting code we need to just make it work!)

# Actual behavior

We have no code yet, so most of the contents of the DEVELOPMENT.md would not work.

I copied most of the DEVELOPMENT.md contents from https://github.com/tektoncd/pipeline/blob/master/DEVELOPMENT.md but didn't copy the supporting code (e.g. hack dir).

Some things I noticed that we could probably make work fairly easily, that would set us up nicely:
- adding the supporting scripts in the `hack`  dir (update-deps, update-codegen)
- making update-codegen work by adding an empty or nearly empty _type.go file.
- getting `ko apply -f config/` to work, an easy way to do this would be to copy a lot of the config from https://github.com/tektoncd/pipeline/tree/master/config maybe without the bit to deploy the controller and webhook cuz we don't have those yet
- Note that in #8 we'll create a skeleton controller and in #9 we'll create a skeleton webhook

# Additional info

* DEVELOPMENT.md is being added in https://github.com/tektoncd/triggers/pull/2
* This is going to require vendoring in a lot of the deps we need; the first step to make that work will be to figure out what to vendor to get [`update-deps.sh` (or similar)](https://github.com/tektoncd/pipeline/tree/master/hack) to work.

**Comment by ncskier** [comment]
@bobcatfish to clarify, are we making it possible to install `triggers` independently from `pipeline`? If so, we'll need to add yaml for our own Namespace, ClusterRole, ServiceAccount, ClusterRoleBinding, etc. (some of these might be duplicates from `pipeline`; for example, the Namespace could be the same yaml file that's in `pipeline`?).

**Comment by ncskier** [comment]
I followed up with @bobcatfish about my previous comment, and I will proceed with this issue under the assumption that users can install `triggers` without having installed `pipelines` (although they will work best together). The `triggers` project will be installed into the `tekton-pipelines` namespace, but will use its own ServiceAccount.

**Comment by ncskier** [comment]
Closing this issue now that `ko apply -f config/` works, the `hack` directory (with `update-deps` and `update-codegen`) works, and the skeleton controller & webhook exist.

Relavent PRs:

- docs update: https://github.com/tektoncd/triggers/pull/30
- skeleton webhook: https://github.com/tektoncd/triggers/pull/21
- skeleton controller: https://github.com/tektoncd/triggers/pull/18
- types & `hack` code: https://github.com/tektoncd/triggers/pull/17

**Comment by bobcatfish** [comment]
niiiiice 🎉

![image](https://user-images.githubusercontent.com/432502/61720869-8e131d00-ad35-11e9-8657-0bab6472b668.png)
