### ISSUE TITLE
triggerbinding  can use the cel get the value

### ISSUE THREAD

**Issue by bibi520** [tektoncd/triggers#711]
triggerbinding：
![image](https://user-images.githubusercontent.com/42456284/90231670-189d5180-de4e-11ea-9486-e5c53fc39cf2.png)

I just want to master this value what should I do

![image](https://user-images.githubusercontent.com/42456284/90231606-03c0be00-de4e-11ea-8a4c-64a523baa4bd.png)

**Comment by dibyom** [comment]
You'd want to use a CEL overlay to create a field for that and then use that in your binding. As an example:

```
            - key: extensions.branch_name
              expression: "body.ref.split('/')[2]"
```
https://github.com/tektoncd/triggers/blob/master/examples/eventlisteners/cel-eventlistener-multiple-overlays.yaml#L15


and the use $(body.extensions.branch_name) in your binding.

**Comment by bibi520** [comment]
Thanks for taking care of it

**Comment by dibyom** [comment]
Sure thing @bibi520 I'm going to close this issue. Feel free to re-open if this did not solve your problem.
/close
