### ISSUE TITLE
Inconsistent naming of container in release.yaml

### ISSUE THREAD

**Issue by piyush-garg** [tektoncd/triggers#713]
The container name is `tekton-triggers-controller` in Controller Deployment while the name of the container in Webhook Deployment is `webhook`

Link for controller deployment: https://github.com/tektoncd/triggers/blob/master/config/controller.yaml#L53

Link for webhook controller: https://github.com/tektoncd/triggers/blob/master/config/webhook.yaml#L53

Is there any specific reason for this? Or is this left by some mistake?

/kind question
/kind bug

**Comment by dibyom** [comment]
Hmm, this does not sound intentional. Sounds like a bug we should fix!

**Comment by khrm** [comment]
Interestingly, this issue is there in pipelines also. 
https://github.com/tektoncd/pipeline/blob/f618ff57d1df60f02db009153fb0e8ff79d97dd4/config/controller.yaml#L56
https://github.com/tektoncd/pipeline/blob/f618ff57d1df60f02db009153fb0e8ff79d97dd4/config/webhook.yaml#L59

**Comment by piyush-garg** [comment]
I have created the issue on pipelines also https://github.com/tektoncd/pipeline/issues/3113

**Comment by dibyom** [comment]
/remove-lifecycle stale

@piyush-garg any updates on this?

**Comment by piyush-garg** [comment]
I can raise the PR if this looks good to you. Was looking for feedback on this
