### ISSUE TITLE
Use another NodeSelector value in EventListener tests

### ISSUE THREAD

**Issue by barthy1** [tektoncd/triggers#718]
Question: Is it possible to change in the tests https://github.com/tektoncd/triggers/blob/79884efba46bcdbfd2794a01129fe9c36084d0bb/test/eventlistener_test.go#L290 and https://github.com/tektoncd/triggers/blob/79884efba46bcdbfd2794a01129fe9c36084d0bb/test/eventlistener_scale_test.go#L54 NodeSelector specification from `beta.kubernetes.io/arch=amd64` to `beta.kubernetes.io/os=linux`?

I am working to verify that triggers e2e tests will work for s390x architecture, and amd64 arch in NodeSelector fails 2 tests. 
As I don't see any amd64 specific code in the tests, my guess that it's more test for NodeSelector option here, so another meaningful value should be also ok?

This is part of "other architectures support" activity https://github.com/tektoncd/plumbing/issues/495

**Comment by dibyom** [comment]
Yeah, that sounds reasonable to me! PR welcome :)

**Comment by GwonsooLee** [comment]
@barthy1  Great. This is actually I worried when I added nodeSelector in the test code :) Thank you so much for suggesting group idea! 
If no one wants to assign this issue, then I will fix this! Thanks :)
