### ISSUE TITLE
Ask what the default variables are for the TriggerTemplate

### ISSUE THREAD

**Issue by bibi520** [tektoncd/triggers#731]
Something like this doesn't pass the variables that come with the TriggerTemplate
![image](https://user-images.githubusercontent.com/42456284/91516519-45f20100-e91e-11ea-95fe-10ab1eff0c3c.png)

**Comment by bibi520** [comment]
Is there a date variable

**Comment by bigkevmcd** [comment]
The `$(uid)` field is documented in the TriggerTemplates documentation https://tekton.dev/docs/triggers/triggertemplates/

And there's no date field just now.

**Comment by bibi520** [comment]
ok  3q

**Comment by bibi520** [comment]
Will you consider adding variables later

**Comment by bigkevmcd** [comment]
I guess the tricky thing is what does "a data variable" look like?

Is it simply a 64-bit unix-time long integer?

is there formatting of the date/time allowed?

**Comment by bibi520** [comment]
For example： 2020-08-27-10-44-05

**Comment by dibyom** [comment]
We were discussing this in the Working Group today. One idea is to allow access to some context variables (date can be one such variables) -- I opened a feature request in #737 

A different way might be to add a CEL function to get the date.

**Comment by bigkevmcd** [comment]
I pondered a CEL function (it would be fairly trivial), and it could return a https://github.com/google/cel-go/blob/master/common/types/timestamp.go

But, it opens up questions like parsing, and formatting.

**Comment by dibyom** [comment]
> But, it opens up questions like parsing, and formatting.

Yeah, I guess one can always write a task to take a timestamp and parse it to their liking 😛

**Comment by dibyom** [comment]
Closing out due to inactivity. We can consider adding more default variables like dates if the use cases arise!
/close
