### ISSUE TITLE
FR: Metrics for EventListener

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#736]
# Expected Behavior

The EventListener sink should be instrumented to emit metrics in order to help with monitoring and observability. As an example, knowing the number of triggers processed would be very helpful in debugging #687 

# Actual Behavior

The EventListener does not emit any metrics today. One workaround is to read/parse the log messages instead.

# Additional Info
Some ideas for metrics to add would be a counter for the number of total requests processed by the listener, a counter for per trigger invocations, gauge for number of concurrent requests, avg/95 percentile request duration etc.

The EL sink should be instrumented to emit metrics at a documented metrics HTTP port. Users can then use their monitoring tools to scrape metrics and build dashboards. 

One option would be to use something like the Prometheus client or OpenCensus to instrument -- this should add some default metrics in addition to any custom ones we define.
https://prometheus.io/docs/guides/go-application/
https://opencensus.io/guides/http/go/net_http/

(We should probably open a TEP with a design first before implementing this.)

/kind feature

**Comment by ekarlso** [comment]
@dibyom I guess OpenTelemetry is a better / newer way to do this

**Comment by jmcshane** [comment]
i think this project should match the approach taken by the pipeline metrics, as documented here: https://tekton.dev/docs/pipelines/metrics/ and implemented for [pipelinerun](https://github.com/tektoncd/pipeline/blob/8bcfd8bd2f5f3ccef96196bd667800e8230f1022/pkg/reconciler/pipelinerun/metrics.go) and [taskrun](https://github.com/tektoncd/pipeline/blob/8bcfd8bd2f5f3ccef96196bd667800e8230f1022/pkg/reconciler/taskrun/metrics.go).

I would think initially fairly straightforward HTTP metrics that would help here, especially considering the differentiation in HTTP response by action in the eventlistener. Eventually, tagging a count events by trigger name would enable more complex monitoring of the operation of the EL.
