### ISSUE TITLE
Add a log library + logging config to the EventListener binary

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/triggers#76]
# Expected Behavior

It looks like [the EventListener binary](https://github.com/tektoncd/triggers/blob/master/cmd/eventlistener/main.go) is going to be doing a lot of work in the future, so we should treat it's logs like we would logs from our controller, e.g.:

- Be able to log at different levels (e.g. error vs warn vs debug)
- Allow the instantiator of the binary to control the log level (e.g. run at warn or error by default but it's possbile to turn on debug / verbose logging

# Actual Behavior

Right now we are using the go `log` library and logging everything the same way. The user has no control over it.

# Additional Info

Probably reasonable just to use the same log library as our controller (zap) and configure it in a similar way, e.g. https://github.com/tektoncd/triggers/blob/master/config/config-logging.yaml

But if whoever is doing this feels like it we could look into other logging libraries :D

**Comment by akihikokuroda** [comment]
PR: https://github.com/tektoncd/triggers/pull/202

**Comment by akihikokuroda** [comment]
@bobcatfish @dibyom After implementing this as the same way as the webhook and controller, we realized that the `config-logging-triggers` ConfigMap must be created in the same namespace as the eventlistener.  It is inconvenient to the user.   We are considering the option putting the logging config in the eventlistener crd but it requires extra work.  Is there any better options?

**Comment by akihikokuroda** [comment]
I probably create the default configmap only when the configmap doesn't exist at the eventlistener creation.  Is this a good option?

**Comment by dibyom** [comment]
Yeah, having the reconciler create a default configmap seems like a good place to start! We should make sure they get cleaned up though!

**Comment by akihikokuroda** [comment]
I opened a separate issue for the configmap clean up. https://github.com/tektoncd/triggers/issues/209

**Comment by ncskier** [comment]
Sounds like this issue is done 👍
