### ISSUE TITLE
Use Pods as Test Data in Mock Controllers

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/triggers#779]
The current resources available for seeding test data for mock controllers is shown [here](https://github.com/tektoncd/triggers/blob/45daf11629f2709c359b5d6a3d5fad37939e96ec/test/controller.go#L55). I am wondering if it would make sense to add Pods to this collection of resources to aid with unit testing EventListener logs for `tkn` amongst other testing use cases. Or is there an alternative way to make use of `SeedResources` to include Pods?

/kind question
/kind feature

**Comment by dibyom** [comment]
Sure, that seems reasonable. Is CLI using the test controller for testing?

**Comment by danielhelfand** [comment]
Yes, we use it for unit testing triggers commands quite a bit.
