### ISSUE TITLE
Support resources in podTemplate

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#792]
# Expected Behavior

Users can configure resource requirements for their Listeners

# Actual Behavior

Users have no way of doing this today.

# Additional Info

From: https://github.com/tektoncd/triggers/issues/505#issuecomment-690611723

/kind feature

**Comment by savitaashture** [comment]
@dibyom i have already created issue for the same https://github.com/tektoncd/triggers/issues/762

I think we need to close one of them

**Comment by dibyom** [comment]
ahh missed, that I'll close this.
/close
