### ISSUE TITLE
Event listeners -> Cel interceptors with lowerAscii() is failing

### ISSUE THREAD

**Issue by aii-ssvinoth22** [tektoncd/triggers#805]
# Expected Behavior
   Convert a repo name to lowercase using cel interceptors
# Actual Behavior
    Added interceptors to event listener as below
    `- name: eks-front-push
    interceptors:
        - cel:
            overlays:
            - key: extensions.repo_name
              expression: "body.repository.name.lowerAscii()"`

  but failed. as below 
   `"msg":"expression \"body.repository.name.lower │
│ Ascii()\" check failed: ERROR: <input>:1:32: undeclared reference to 'lowerAscii' (in container '')\n | body.reposit │
│ ory.name.lowerAscii()\n |`
# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

**Comment by afrittoli** [comment]
I tried this in a unit test and it worked fine:
```
		{
			name: "overlay with string library functions 2",
			CEL: &triggersv1.CELInterceptor{
				Overlays: []triggersv1.CELOverlay{
					{Key: "new", Expression: "body.ref.split('/')[2]"},
					{Key: "lower", Expression: "body.name.lowerAscii()"},
				},
			},
			payload: ioutil.NopCloser(bytes.NewBufferString(`{"ref":"refs/head/master","name":"Testing"}`)),
			want:    []byte(`{"lower":"testing","new":"master","ref":"refs/head/master","name":"Testing"}`),
		},
```

I wonder why it fails when running in the event listener

**Comment by afrittoli** [comment]
Could you share the version of tekton and kubernetes in the additional info?

**Comment by aii-ssvinoth22** [comment]
triggers.tekton.dev/release=v0.8.1

**Comment by dibyom** [comment]
loweAscii() was added in v0.9 -- could you try with v0.9.1?

**Comment by aii-ssvinoth22** [comment]
Yes i tried and it worked, thanks!
