### ISSUE TITLE
Dynamically add triggers to event listeners

### ISSUE THREAD

**Issue by afrittoli** [tektoncd/triggers#822]
### Feature request

As a Tekton user I would like to be able to add triggers to existing event listeners.

### Use case

The use case for this is a "native" notification system for Tekton.

Notifications are possible today in Tekton using the following setup:
- configuring tekton to send cloud-events to a specific event listeners
- adding triggers that:
  - match specific taskruns / pipelineruns by using CEL filters
  - extract the required info from the taskrun / pipelinerun using bindings
  - run a trigger template that includes the notification task as part of its resources

This requires a lot of configuration and since it has a lot of moving parts it's error prone and hard to debug.

I want to design a notification mechanism that solves this for users, by providing an abstraction on top.
The general idea is to have a notification CRD (I might call it differently since it would have other uses too), that would allow user to specify:
1. a source filter / condition on taskruns / pipelineruns (written in CEL, based on meta, status and event details)
1. a task or pipeline to be executed
1. inline bindings (written in JSONPath, based on the whole taskrun/pipelinerun payload and event details) to populate task/pipeline inputs 

The notification controller would dynamically:
- create a trigger template object
- create a trigger resource
- add the trigger resource to an existing event listener (which is the feature request here)

### Implementation Ideas

1. label based: create a trigger with a specific label. Event listener looks for all triggers in the namespace that match a label
2. config map based: the trigger name is patched to a configmap read by the event listener
3. patch based: the event listener is patched to add / remove triggers by the notification controller

I don't like options (2) and (3) because they share the same problem of a single resource managed by multiple controllers with all the issues that may derive from stale reads and overwrites. (3) would be possible without any change to triggers (I think).

**Comment by dibyom** [comment]
/cc @khrm 

The label based idea is essentially what @khrm proposed and is implementing as part of [TEP-009](https://github.com/tektoncd/community/blob/master/teps/0009-trigger-crd.md)

**Comment by afrittoli** [comment]
I should have read the TEP to the end.
That's great, I look forward to the selector feature!

**Comment by dibyom** [comment]
I'll close this out since selectors implement this. Feel free to re-open if that does not fully match your use case!
