### ISSUE TITLE
Restrict creation of Resources to just Pipeline Resources?

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/triggers#83]
# Expected Behavior

After discussing with @IMJasonH and @dibyom I'm thinking it would make sense to restrict the types of Resources a user can create with TriggerTemplates to just types that we know are needed for executing Tekton Pipelines (e.g. `PipelineResources`, `Conditions`, `PipelineRuns`, etc.).

I think this makes sense because:

- It's easier to expand the scope later than it is to restrict it
- I don't think we have any concrete use cases for creating other Resources (correct me if I'm wrong); we know we want to start `PipelineRuns` (maybe `TaskRuns` too) but it's not clear we want to create anything else - and afaik we don't want to replace other generic event triggering solutions such as knative eventing or argo events
- If we do restrict the types, we can validate the structure of `TriggerTemplates` before waiting for the `EventListener` to be invoked

# Actual Behavior

We explicitly decided that it should be possible for a user to create _any_ Resource in a kube cluster, e.g. they could create a Deployment (or a Role!) as long as the service account had permission to.

**Comment by vtereso** [comment]
I believe we already have the full scope since that is how it is implemented as per https://github.com/tektoncd/triggers/commit/c9537c0636218b51766dfc5dbab4db5bdbd0389d. If we wanted to restrict this to core tekton objects for the initial release, we could do so at the apiGroup/resource level.

**Comment by ncskier** [comment]
Sorry, I'm a little late adding my opinion to this issue.

One benefit I see of not restricting TriggerTemplates to only Tekton resources, is that it decouples the Triggers project from the Pipelines project. So, if Pipelines creates new resources, or modifies its resources (which will happen in the future since it's still in alpha), the Triggers project might become broken from these changes, and/or Triggers might need to be updated to support these changes. I think the benefits of keeping the Triggers project decoupled or loosely coupled to the Pipelines project might outweigh the costs stated above.

**Comment by vtereso** [comment]
From the WG discussion, we seem to be aligned that restricting resource creation to the `tekton.dev` apigroup makes sense for a first release. TBD on implementation. Should we add a `ConfigMap` whitelisting the permissible apigroups for creation? Use an environment variable?

**Comment by dibyom** [comment]
I think a `ConfigMap` makes sense! I'll take a stab at this

/assign

**Comment by vtereso** [comment]
@dibyom The root README specifies:
> This repo draws inspiration from Tekton, but can used stand alone since TriggerTemplates can create any Kubernetes resource.

Implementation specifics or otherwise, seems good to update this and potentially add some info other places.

**Comment by skaegi** [comment]
Gulp -- I'd like to be able to create Secrets too. e.g. the event contains information that I use to create a Secret needed later in my pipeline.

**Comment by dibyom** [comment]
So, chatted with @vtereso and here is what we are thinking:
* We'll keep the static restriction for 0.1

* In the future we'll add two checks:
1. does the EventListener ServiceAccount have access to the Resources in the template?

2. does the user creating the EventListener have access to the Resources in the template as well as the EventListener ServiceAccount?

Once we have these two checks we'll deprecate the static whitelist of allowed types.
