### ISSUE TITLE
Define policy for modification of TriggerBinding and TriggerTemplate

### ISSUE THREAD

**Issue by vincent-pli** [tektoncd/triggers#84]
# Expected Behavior
`TriggerBinding` and `TriggerTemplate` are designed for reusing, that's means one single `TriggerBinding` will be shared by several `EventListener`.
So if modification occurred on `TriggerBinding` or `TriggerTemplate` what should related `EventListener` do?
- Ignore (dev env)
- Stop working and send notification to avoid potential exception (production env)

I think we should enhance as below in `EventListener` type definition:
``` 
type Trigger struct {
        IgnoreChange  bool `json:"ignoreChange,omitempty"`   -- add this field to define the policy
	TriggerBinding  TriggerBindingRef  `json:"binding"`
	TriggerTemplate TriggerTemplateRef `json:"template"`
}
```

# Actual Behavior
Nothing about this part

# Additional Info
To achieve this, the controller of `EventListener` should watch both `TriggerBinding` and `TriggerTemplate`.

**Comment by vtereso** [comment]
@vincent-pli Thanks for raising this. I think this raises a few points to be considered:
- If updates are restricted, what about when either of these are deleted?
- Should we create reconcilers for `TriggerBindings` and `TriggerTemplates` to notify the `EventListener` about this sort of thing? If so, won't validation restriction this since modifying one of these resources at a time will invalidate the `EventListener` trigger?

**Comment by vincent-pli** [comment]
@vtereso Thanks for your comments.
>What about when TriggerBindings and TriggerTemplates are deleted?

This scenario is fatal error, should high light in the status of related `EventListener` immediately. The `pod` should keep running.

>Should we create reconcilers for TriggerBindings and TriggerTemplates to notify the EventListener of changes? Will validation restrict this since modifying one of these resources at a time will invalidate the EventListener trigger?

I prefer let controller of `EventListener` to watch `TriggerBinding` and `TriggerTemplate`.
In reconciler of `EventListener`, we could:
- Add specific tag to related `TriggerBinding` and `TriggerTemplate`, maybe the value of tag is the resource name of that `EventListener`
- Watching `TriggerBinding` and `TriggerTemplate`
- If related `TriggerBinding` or `TriggerTemplate` updated or deleted, the reconciler will triggered, then do validation and take action.

**Comment by vincent-pli** [comment]
Summary the solution here:
1. In `reconcile` of `EventListener` add specific tag to `TriggerTemplate` and `TriggerBinding`.  
2. Record the `Generation` of `TriggerTemplate` and `TriggerBinding` to the `EventListener.status.generations`
3. Watch the `TriggerTemplate` and `TriggerBinding`, when update occurred, the related `EventLister` (find by the label added in step 1) will enter the `work queue`.
4. In `reconcile`, check the `Generation` between `TriggerTemplate.Generation` and `EventListener.status.generations`, if not same, take action (emit event or whatever)

**Comment by vincent-pli** [comment]
Hi guys, the implements is not follow the upper design, more simple:
1. Start watcher in the `pod` which created by `EventListener`, the watcher will watch on related `TriggerBinding` and `TriggerTemplate`.
2. If any `Delete` and `Update` occurred on related `TriggerBinding` and `TriggerTemplate`, a k8s event will be send and bind to related `EventListener`
