### ISSUE TITLE
Cannot bind JSON objects like $body, $header, $body.changes etc.

### ISSUE THREAD

**Issue by wwu-cx** [tektoncd/triggers#841]
# Expected Behavior

A binding to an JSON Object that worked in v0.9.1 should continue working in v0.10.0

# Actual Behavior

Whenever is use a JSON Object in a TriggerBinding like

```
- name: header
  value: $(header)
```
or
```
- name: summary
  value: $(body.event_data.scan_overview.summary)
```

 i get 

`{"level":"info","logger":"eventlistener","caller":"sink/sink.go:237","msg":"ResolvedParams : [{Name:text Value:tkn help} {Name:header Value:{\"Content-Length\":\"301\",\"Content-Type\":\"application/json\",\"User-Agent\":\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36\",\"X-Forwarded-For\":\"192.168.201.136\",\"X-Forwarded-Host\":\"tekton.example.com\",\"X-Forwarded-Port\":\"443\",\"X-Forwarded-Proto\":\"https\",\"X-Real-Ip\":\"192.168.201.136\",\"X-Request-Id\":\"180d278ab9cca2ddea9c57a21edc6c0e\",\"X-Scheme\":\"https\"}} {Name:body Value:{\"bot\":false,\"channel_id\":\"oi5kcb6nJjNsALam8\",\"channel_name\":\"tekton\",\"message_id\":\"mBNyFMne34qXxLQpZ\",\"siteUrl\":\"https://rocketchat.example.com\",\"text\":\"tkn help\",\"timestamp\":\"2020-11-24T10:26:59.801Z\",\"token\":\"0c83su9yw6qn\",\"trigger_word\":\"tkn\",\"user_id\":\"goy9jzYRnbSyxr8Qi\",\"user_name\":\"wwu\"}} {Name:bot Value:false} {Name:channel_name Value:tekton} {Name:user_name Value:wwu}]","knative.dev/controller":"eventlistener","/triggers-eventid":"vv7ks","/trigger":"after-rocket"}`

followed by

`{"level":"error","logger":"eventlistener","caller":"sink/sink.go:240","msg":"couldn't unmarshal json: invalid character 'C' after object key:value pair","knative.dev/controller":"eventlistener","/triggers-eventid":"vv7ks","/trigger":"after-rocket","stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:240\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:128"}
`

p.s. I also added `tekton.dev/old-escape-quotes: "true"` to the template, but that didn't help either.

# Steps to Reproduce the Problem

1. Create a binding to a JSON Object ($body or $body.changes for a changeset etc.)
2. Trigger the Eventlistener
3. Observe the Log

# Additional Info

- Kubernetes version: v1.19.3
- Tekton Pipeline version: v0.18.1
- Tekton Triggers version: v0.10.0

--

**Comment by bigkevmcd** [comment]
There's mistake in the release notes, which we'll get fixed, but the documentation is correct https://github.com/tektoncd/triggers/blob/master/docs/triggertemplates.md#escaping-quoted-strings

you'll want to change that to `triggers.tekton.dev/old-escape-quotes: "true"`

**Comment by wwu-cx** [comment]
that worked, thank you
