### ISSUE TITLE
v0.10.0: even listener: cannot list resource "clustertriggerbindings"

### ISSUE THREAD

**Issue by r0bj** [tektoncd/triggers#846]
# Expected Behavior

Event listener works without generating errors.

# Actual Behavior

Using Role and RoleBinding from: https://github.com/tektoncd/triggers/tree/v0.10.0/examples/role-resources/triggerbinding-roles for tekton triggers. Event listeners generates error logs:
```
E1128 04:48:30.144241       1 reflector.go:178] k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible/tools/cache/reflector.go:125: Failed to list *v1alpha1.ClusterTriggerBinding: clustertriggerbindings.triggers.tekton.dev is forbidden: User "system:serviceaccount:tekton-execution:tekton-triggers" cannot list resource "clustertriggerbindings" in API group "triggers.tekton.dev" at the cluster scope
```

# Steps to Reproduce the Problem

1. Deploy triggers with Role and RoleBinding from https://github.com/tektoncd/triggers/tree/v0.10.0/examples/role-resources/triggerbinding-roles
2. Observe the event listener og

# Additional Info

- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:
```
Client version: 0.14.0
Pipeline version: v0.18.1
Triggers version: v0.10.0
```

**Comment by dibyom** [comment]
Ok, so it looks like we are missing a cluster role (required only for clustertriggerbindings) from the examples/. 
I'll update it but in the meantime the EL should still work as intended as long as you are not using a ClusterTriggerBinding.
