### ISSUE TITLE
Configurable timeout and/or retries on webhook interceptors

### ISSUE THREAD

**Issue by viniagostini** [tektoncd/triggers#861]
### Feature request
Currently, I have a webhook interceptor calling a service that sometimes takes more than 5 seconds to respond, and when it happens the trigger throws a Timeout error.

Would be nice if I could configure some retry strategy or increase this timeout.

**Comment by dibyom** [comment]
Hi, sorry about the delayed response. We discussed this during a Working Group meeting. Summarizing the discussion:

We're trying to decide between providing config options vs adding some standardized retry behavior for webhook interceptors. Adding a config option can lead to some complexity (e.g. we already have EL level timeouts...how will this interact with that). Maybe we could just do some standard retries e.g. 3 retries on failure with a timeout of 5 seconds  (utilizing the current EventListener's timeout values).

As a workaround for now, you could try increasing the EventListener's timeouts https://github.com/tektoncd/triggers/blob/master/docs/eventlisteners.md#response-timeout

There is also ongoing work on moving interceptor processing to a [new HTTP API](#271). Once that's done we could try standardizing retry behavior based on the kind of error and the already set EL level timeouts.
