### ISSUE TITLE
Add a configuration for SecurityContext to reconciled eventlistener Deployment

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/triggers#864]
With #862 is merged, eventlistener deployment are no more able to be created, *by default* on OpenShift.
The reason for it is that, by default, you cannot set `uid` for your Pods, OpenShift takes care of this. To be able to use `runAsUser: 65532` on OpenShift, you need to use `anyuid` which is a *higher* privilege than you usually need to. 

Before this change, the eventlistener pod(s), in OpenShift, would happily run with a random uid. With this change, the serviceAccount that runs the eventlistener pod(s) need to have the `anyuid` scc attached (see [here](https://docs.openshift.com/container-platform/4.6/authentication/managing-security-context-constraints.html))

The problem with #862 is that the behavior is not configurable, aka we can't disable it if we don't need it.
I propose to add a way to configure this behavior, most likely through a feature-flag (that would be enabled by default)

**Comment by MarcelMue** [comment]
I will try to provide a PR with a fix as I introduced the change.

**Comment by MarcelMue** [comment]
PR which adds a flag is open now. My main concern is that I am unable to test this properly - so would rely on someone trying this on openshift.

**Comment by MarcelMue** [comment]
I added some more unit tests and am fairly confident now, that this can be closed.
