### ISSUE TITLE
Allow TLS connections between EventListener and Interceptors

### ISSUE THREAD

**Issue by dibyom** [tektoncd/triggers#871]
### Feature request

EventListeners today communicate with Interceptors over HTTP. We should optionally allow TLS connections as well.
We will likely want to do this for the new pluggable interceptors API and not the old style webhook interceptors.

### Use case

* Using Triggers in an environment that mandates E2E TLS.

**Comment by khrm** [comment]
/remove-lifecycle rotten
Feature will be implemented soon.
@savitaashture
