### ISSUE TITLE
typo in getting-started input usage

### ISSUE THREAD

**Issue by isaaguilar** [tektoncd/triggers#879]
https://github.com/tektoncd/triggers/blob/045e704ce44d75e274e2490e3c1d98041dc74f60/docs/getting-started/pipeline.yaml#L74

I was getting an error until I changed this to `"$(resources.inputs.image-source.url)"`

**Comment by dibyom** [comment]
Ahh that's a really old syntax...looks like we need to update your getting-started docs.

/kind bug
