### ISSUE TITLE
Can't remove old EventListener in latest nightly

### ISSUE THREAD

**Issue by andrewrynhard** [tektoncd/triggers#883]
# Expected Behavior

`kubectl delete el X` should remove eventlistenter.
 
# Actual Behavior

Webhook fails to parse:

```
Error from server (BadRequest): error when deleting "tekton/trigger-bot.yaml": admission webhook "validation.webhook.triggers.tekton.dev" denied the request: decoding request failed: cannot decode incoming old object: json: unknown field "podTemplate"
```

# Steps to Reproduce the Problem

1. Create el with `podTemplate` on v0.10
2. Update to nightly
3. Delete/apply el

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.0-rc.2", GitCommit:"27bb2a4a0a5cb8330178d19e57fa61fffa895c98", GitTreeState:"clean", BuildDate:"2020-07-21T17:39:35Z", GoVersion:"go1.14.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}  ```

- Tekton Pipeline version:

```
Client version: 0.15.0
Pipeline version: v0.19.0
Triggers version: v20201230-f9f9ad66e5
Dashboard version: v0.12.0
```


<!-- Any other additional information -->

**Comment by khrm** [comment]
This is happening because we removed podTemplate and serviceType https://github.com/tektoncd/triggers/pull/852/files
I think we didn't handle deprecation properly here. We should have first setup defaults to change El and then remove those fields in next release.
