### ISSUE TITLE
Create a skeleton webhook that does nothing

### ISSUE THREAD

**Issue by bobcatfish** [tektoncd/triggers#9]
It will be easier for ppl to start adding functionality if we add an empty webhook that doesn't actually do anything (eventually this webhook controller will be used to verify Trigger types), just:

* Has all the config needed to build and deploy with `ko`
* Instantiates an admission controller that isn't actually doing anything, e.g.:

```go
	controller := webhook.AdmissionController{
		Client:  kubeClient,
		Options: options,
		Handlers: map[schema.GroupVersionKind]webhook.GenericCRD{
			// nothing actually here cuz we don't have any types yet
		},
		Logger: logger,
	}
```

## Additional info

Continuing to use knative/pkg is probably our best bet for now, in which case we can get a lot of this by more or less copying https://github.com/tektoncd/pipeline/tree/master/cmd/controller.

**Comment by vincent-pli** [comment]
//assign @vincent-pli

**Comment by bobcatfish** [comment]
I think this is fixed by https://github.com/tektoncd/triggers/pull/21 thanks @vincent-pli !!! (plz re-open if I'm wrong :D)
