### ISSUE TITLE
Getting started eventlisteners RBAC issues

### ISSUE THREAD

**Issue by gokula-krishna-dev** [tektoncd/triggers#902]
# Expected Behavior
Eventlistener pod run with no errors

# Actual Behavior
Eventlistener started with following error 

```
E0115 04:30:22.504882       1 reflector.go:178] k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible/tools/cache/reflector.go:125: Failed to list *v1alpha1.ClusterTriggerBinding: clustertriggerbindings.triggers.tekton.dev is forbidden: User "system:serviceaccount:getting-started:tekton-triggers-admin" cannot list resource "clustertriggerbindings" in API group "triggers.tekton.dev" at the cluster scope
E0115 04:30:22.505056       1 reflector.go:178] k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible/tools/cache/reflector.go:125: Failed to list *v1alpha1.EventListener: eventlisteners.triggers.tekton.dev is forbidden: User "system:serviceaccount:getting-started:tekton-triggers-admin" cannot list resource "eventlisteners" in API group "triggers.tekton.dev" in the namespace "getting-started"
E0115 04:30:22.505281       1 reflector.go:178] k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible/tools/cache/reflector.go:125: Failed to list *v1alpha1.TriggerBinding: triggerbindings.triggers.tekton.dev is forbidden: User "system:serviceaccount:getting-started:tekton-triggers-admin" cannot list resource "triggerbindings" in API group "triggers.tekton.dev" in the namespace "getting-started"
E0115 04:30:22.505418       1 reflector.go:178] k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible/tools/cache/reflector.go:125: Failed to list *v1alpha1.TriggerTemplate: triggertemplates.triggers.tekton.dev is forbidden: User "system:serviceaccount:getting-started:tekton-triggers-admin" cannot list resource "triggertemplates" in API group "triggers.tekton.dev" in the namespace "getting-started"
E0115 04:30:22.505652       1 reflector.go:178] k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible/tools/cache/reflector.go:125: Failed to list *v1alpha1.Trigger: triggers.triggers.tekton.dev is forbidden: User "system:serviceaccount:getting-started:tekton-triggers-admin" cannot list resource "triggers" in API group "triggers.tekton.dev" in the namespace "getting-started"
...
```

# Steps to Reproduce the Problem
I am following the instructions from the guides

https://github.com/tektoncd/triggers/tree/master/docs/getting-started
https://github.com/tektoncd/pipeline/blob/master/docs/install.md

1. minikube start --memory 6144 --cpus 2 --insecure-registry="127.0.0.1:5000"
2. minikube addons enable registry
3. minikube addons enable registry-aliases
4. minikube addons enable ingress
5. eval $(minikube -p minikube docker-env)
6. kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
7. kubectl create clusterrole tutorial-role --verb=* --resource=deployments,deployments.apps
8. kubectl create clusterrolebinding tutorial-binding --clusterrole=tutorial-role --serviceaccount=default:tutorial-service
9. kubectl apply --filename https://storage.googleapis.com/tekton-releases/triggers/latest/release.yaml
10. kubectl create secret docker-registry regcred --docker-server=https://registry-1.docker.io/v1/ --docker-username=sample --docker-password=****** --docker-email=sample@sample.com
11. kubectl create namespace getting-started
12. kubectl apply -f ./docs/getting-started/rbac/admin-role.yaml
13. kubectl apply -f ./docs/getting-started/rbac/webhook-role.yaml
14. kubectl apply -f ./docs/getting-started/pipeline.yaml
15. kubectl apply -f ./docs/getting-started/triggers.yaml # with modified DOCKER IMAGE replace
16. k logs -n getting-started el-getting-started-listener* # shows above error

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.14-dispatcher", GitCommit:"766e62361387c284022a97270f0997d67ae792d0", GitTreeState:"clean", BuildDate:"2020-12-01T16:13:56Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"} 
```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

```
Client version: 0.13.0
Pipeline version: v0.20.0
Triggers version: v0.10.2
```

**Comment by dibyom** [comment]
Hmm, looks like the roles in getting/started/rbac might be a bit out of date. I'll update the docs. In the meantime, the roles from examples/rbac.yaml should work.

**Comment by gokula-krishna-dev** [comment]
@dibyom Thank you for your support! 

There's is one more issue. The role in examples/rbac.yaml is pointing to default namespace. I saw in your PR you made a sym link with getting started role. I think the file should be duplicated and namespace should be updated to `getting-started` to make it work. Can I create a PR to fix it? Or is there a better approach?

**Comment by dibyom** [comment]
hey @gokula-krishna-dev copying would work though in the past this has led to issues where the file would get out of date. I updated the instructions for all the kubectl commands to always use `-n getting started` which should also solve the issue.

**Comment by jinzishuai** [comment]
@dibyom It seems that `kubectl -n getting-started apply -f ./docs/getting-started/rbac/admin-role.yaml` does not override the namespace for the ClusterRoleBinding for me. I had to change the yaml file for it work:
```diff
shijin@KLS-00106:triggers;kube=dv;git=master$ git diff examples/rbac.yaml
diff --git a/examples/rbac.yaml b/examples/rbac.yaml
index 407b04a4..453c6b8c 100644
--- a/examples/rbac.yaml
+++ b/examples/rbac.yaml
@@ -58,7 +58,7 @@ metadata:
 subjects:
 - kind: ServiceAccount
   name: tekton-triggers-example-sa
-  namespace: default
+  namespace: getting-started
 roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
```
Does this make sense? Maybe we cannot share the example with the getting-started doc?

**Comment by dibyom** [comment]
I think this should be fixed now. We added a cluster role binding with the right namespace.
