### ISSUE TITLE
Skip trigger by specific field

### ISSUE THREAD

**Issue by renhao-0518** [tektoncd/triggers#910]
Can a specific commit message be used to skip the trigger and execute ci，Sometimes the modification is not the code

**Comment by bigkevmcd** [comment]
Yes, you could use a [CEL interceptor](https://tekton.dev/docs/triggers/eventlisteners/#cel-interceptors) with a filter that returned false if the commit message field contained something like `[skip ci]`.

`filter: body.message.indexOf('[skip ci]') > 0 || body.message.indexOf('[ci skip]') > 0`

You'll need to change the `body.message` part to include the the path to the commit message in whatever event you're processing.

**Comment by renhao-0518** [comment]
filter: header.match('X-Gitlab-Event', 'Push Hook') && body.message.indexOf('[skip ci]') > 0 || body.message.indexOf('[ci skip]') > 0 && header.canonical('X-Gitlab-Token').compareSecret('secretToken', 'gitlab-secret')
```json
{"level":"info","ts":"2021-01-22T07:50:19.212Z","logger":"eventlistener","caller":"sink/sink.go:211","msg":"interceptor stopped trigger processing: rpc error: code = InvalidArgument desc = error evaluating cel expression: expression \"header.match('X-Gitlab-Event', 'Push Hook') && body.message.indexOf('[skip ci]') > 0 || body.message.indexOf('[ci skip]') > 0 && header.canonical('X-Gitlab-Token').compareSecret('secretToken', 'gitlab-secret')\" failed to evaluate: no such overload","knative.dev/controller":"eventlistener","/triggers-eventid":"vb2cn","/trigger":"gitlab-listener","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"github.com/tektoncd/triggers/pkg/sink/sink.go","line":"211","function":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger"}}
```
--------------------------------------------------------------------------------------
filter: header.match('X-Gitlab-Event', 'Push Hook') && body.commits.message.indexOf('[skip ci]') > 0 || body.commits.message.indexOf('[ci skip]') > 0 && header.canonical('X-Gitlab-Token').compareSecret('secretToken', 'gitlab-secret')

```json
{"level":"info","ts":"2021-01-22T07:58:04.270Z","logger":"eventlistener","caller":"sink/sink.go:211","msg":"interceptor stopped trigger processing: rpc error: code = InvalidArgument desc = error evaluating cel expression: expression \"header.match('X-Gitlab-Event', 'Push Hook') && body.commits.message.indexOf('[skip ci]') > 0 || body.commits.message.indexOf('[ci skip]') > 0 && header.canonical('X-Gitlab-Token').compareSecret('secretToken', 'gitlab-secret')\" failed to evaluate: unsupported index type 'string' in list","knative.dev/controller":"eventlistener","/triggers-eventid":"6mkkl","/trigger":"gitlab-listener","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"github.com/tektoncd/triggers/pkg/sink/sink.go","line":"211","function":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger"}}
```

**Comment by bigkevmcd** [comment]
What version of Triggers are you using?

Also, you could use the GitLab interceptor https://tekton.dev/docs/triggers/eventlisteners/#gitlab-interceptors

**Comment by bigkevmcd** [comment]
Ok, I've had a look at this, I can see that you're using GitLab...

https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#push-events indicates that the "commits" field of the event is a JSON array of JSON objects.

This expression `body.commits.message.indexOf('[skip ci]')` is basically trying to lookup element `message` in the array of objects, which because it's not an object, doesn't work.

You could try `body.commits[0].message` for this.

If it was me, I'd stack the GitLab interceptor before your CEL interceptor, this would simplify the event and secret checking, and then you could shorten your CEL expression to one that might be easier for you to debug.

**Comment by renhao-0518** [comment]
I agree with you, it should be written like this
```yaml 
 triggers:
    - name: gitlab-listener
      interceptors:
        - gitlab:
            secretRef:
              secretName: gitlab-secret
              secretKey: secretToken
            eventTypes:
              - Push Hook
        - cel:
            filter: "body.commits[0].message.indexOf('[skip ci]') > 0 || body.commits[0].message.indexOf('[ci skip]') > 0"
            overlays:
            - key: branch_name
              expression: "body.ref.split('/')[2]"
```

**Comment by bigkevmcd** [comment]
@renhao-0518 I realised that I made a mistake there, you want to filter ones out with skip ci-...

So, you probably want `body.commits[0].message.indexOf('[skip ci]') = 0 || body.commits[0].message.indexOf('[ci skip]') = 0`

That will fail if it detects `[skip ci]` or `[ci skip]` in the body (the indexOf returns the position within the string), which would cause the Trigger to not execute.

**Comment by renhao-0518** [comment]
if 0 > 0 then fasle 
if 1 > 1 then ture

No matter whether the content I submit contains [ci skip || skip ci] or not, it will always return false. Why is this so?

**Comment by renhao-0518** [comment]
Yes, I also encountered this problem just now

> @renhao-0518 I realised that I made a mistake there, you want to filter ones out with skip ci-...
> 
> So, you probably want `body.commits[0].message.indexOf('[skip ci]') = 0 || body.commits[0].message.indexOf('[ci skip]') = 0`
> 
> That will fail if it detects `[skip ci]` or `[ci skip]` in the body (the indexOf returns the position within the string), which would cause the Trigger to not execute.

Yes, I also encountered this problem just now

**Comment by renhao-0518** [comment]
The operation symbol should be ==, = the admission controller will not pass the verification

**Comment by renhao-0518** [comment]
> @renhao-0518 I realised that I made a mistake there, you want to filter ones out with skip ci-...
> 
> So, you probably want `body.commits[0].message.indexOf('[skip ci]') == 0 || body.commits[0].message.indexOf('[ci skip]') == 0`
> 
> That will fail if it detects `[skip ci]` or `[ci skip]` in the body (the indexOf returns the position within the string), which would cause the Trigger to not execute.

When i change to this ，Whatever I submit, he returns false，I suspect there is a problem with the controller，He had just succeeded once，After that, no matter what I submit, it returns false

**Comment by renhao-0518** [comment]
```shell
[root@localhost gtr]# git commit --allow-empty -m 'Hi Tekton'
[k8s-adapter 893591b] Hi Tekton
[root@localhost gtr]# git push origin k8s-adapter 
Counting objects: 1, done.
Writing objects: 100% (1/1), 181 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
remote: 
remote: To create a merge request for k8s-adapter, visit:
remote:   http://git.timevale.cn:8081/duanyu/gtr/merge_requests/new?merge_request%5Bsource_branch%5D=k8s-adapter
remote: 
To git@git.timevale.cn:duanyu/gtr.git
   c9cc91d..893591b  k8s-adapter -> k8s-adapter
```
```log
{"level":"info","ts":"2021-01-22T14:17:08.402Z","logger":"eventlistener","caller":"sink/sink.go:211","msg":"interceptor stopped trigger processing: rpc error: code = FailedPrecondition desc = expression body.commits[0].message.indexOf('[skip ci]') == 0 || body.commits[0].message.indexOf('[ci skip]') == 0 did not return true","knative.dev/controller":"eventlistener","/triggers-eventid":"cmmk7","/trigger":"gitlab-listener","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"github.com/tektoncd/triggers/pkg/sink/sink.go","line":"211","function":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger"}}
```

**Comment by bigkevmcd** [comment]
@renhao-0518 https://github.com/google/cel-go/blob/master/ext/strings.go#L52

It returns `-1` when the string isn't found.

**Comment by renhao-0518** [comment]
```yaml
      interceptors:
        - gitlab:
            secretRef:
              secretName: gitlab-secret
              secretKey: secretToken
            eventTypes:
              - Push Hook
        - cel:
            filter: body.commits[0].message.indexOf('[ci skip]') == 0 || body.commits[0].message.indexOf('[skip ci]') == 0
            overlays:
            - key: branch_name
              expression: "body.ref.split('/')[2]"
```

```shell
[root@localhost gtr]# git commit --allow-empty -m  "update images tag"
[k8s-adapter 5945e81] update images tag
[root@localhost gtr]# git push
warning: push.default is unset; its implicit value is changing in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the current behavior after the default changes, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Counting objects: 1, done.
Writing objects: 100% (1/1), 184 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
remote: 
remote: To create a merge request for k8s-adapter, visit:
remote:   http://git.timevale.cn:8081/duanyu/gtr/merge_requests/new?merge_request%5Bsource_branch%5D=k8s-adapter
remote: 
To git@git.timevale.cn:duanyu/gtr.git
   d85d64d..5945e81  k8s-adapter -> k8s-adapter
```

```log
{"level":"info","ts":"2021-01-22T16:13:11.244Z","logger":"eventlistener","caller":"sink/sink.go:211","msg":"interceptor stopped trigger processing: rpc error: code = FailedPrecondition desc = expression body.commits[0].message.indexOf('[ci skip]') == 0 || body.commits[0].message.indexOf('[skip ci]') == 0 did not return true","knative.dev/controller":"eventlistener","/triggers-eventid":"5dznt","/trigger":"gitlab-listener","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"github.com/tektoncd/triggers/pkg/sink/sink.go","line":"211","function":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger"}}
```
------------------------------------------------------------------------------------------------------------------------------------
```shell
[root@localhost gtr]# git commit --allow-empty -m  "skip ci"
[k8s-adapter a2b630b] skip ci
[root@localhost gtr]# git push
warning: push.default is unset; its implicit value is changing in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the current behavior after the default changes, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Counting objects: 1, done.
Writing objects: 100% (1/1), 178 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
remote: 
remote: To create a merge request for k8s-adapter, visit:
remote:   http://git.timevale.cn:8081/duanyu/gtr/merge_requests/new?merge_request%5Bsource_branch%5D=k8s-adapter
remote: 
To git@git.timevale.cn:duanyu/gtr.git
   5945e81..a2b630b  k8s-adapter -> k8s-adapter
```

```log
{"level":"info","ts":"2021-01-22T16:14:53.775Z","logger":"eventlistener","caller":"sink/sink.go:211","msg":"interceptor stopped trigger processing: rpc error: code = FailedPrecondition desc = expression body.commits[0].message.indexOf('[ci skip]') == 0 || body.commits[0].message.indexOf('[skip ci]') == 0 did not return true","knative.dev/controller":"eventlistener","/triggers-eventid":"qz8px","/trigger":"gitlab-listener","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"github.com/tektoncd/triggers/pkg/sink/sink.go","line":"211","function":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger"}}
```

I don't understand, where did I go wrong

**Comment by bigkevmcd** [comment]
@renhao-0518 you're matching on `[skip ci]` or `[ci skip]` but only sending `skip ci`.

**Comment by renhao-0518** [comment]
@bigkevmcd
```shell
body.commits[0].message.indexOf('[ci skip]') == 0 || body.commits[0].message.indexOf('[skip ci]')
```
When I submit normally, he always returns to fasle

**Comment by bigkevmcd** [comment]
@renhao-0518 The way the filters work, is that if the expression returns false, then the remainder of the interceptor is skipped.

In your filter, you're saying "only proceed if the message beings with `[skip ci]` or `[ci skip]`".

Likely want to say ` body.commits[0].message.indexOf('[skip ci]') == -1` because it returns `-1` when the message is not found in the string.

**Comment by renhao-0518** [comment]
@bigkevmcd  Sorry, there may be a misunderstanding, maybe my expression is not accurate enough，In fact, I want to execute the pipeline during normal submission，When the submission information contains [ci skip] or [skip ci], he will not execute the pipeline

**Comment by bigkevmcd** [comment]
@renhao-0518 I understand that, so, you need to return false (which stops the interceptor) when it contains the strings you're avoiding.

The log above:
```
expression body.commits[0].message.indexOf('[ci skip]') == 0 || body.commits[0].message.indexOf('[skip ci]') == 0 did not return true
```
For the example you gave, means that your test is inverted, you want to return false.

So, you want to say...

```
body.commits[0].message.indexOf('[ci skip]') == -1 && body.commits[0].message.indexOf('[skip ci]') == -1
```

i.e. return true _only_ if both conditions are met, which means that the commit message contains neither of the two strings ?

**Comment by renhao-0518** [comment]
@bigkevmcd Just meet one of the conditions，Now the problem has been solved, thanks for your help，```shell body.commits[0].message.indexOf('[ci skip]') == -1 ```  If used alone, it can work normally ，```shell body.commits[0].message.indexOf('[ci skip]') == -1 || body.commits[0].message.indexOf('[skip ci]') == -1 ``` If combined, it will return true no matter what is submitted

**Comment by bigkevmcd** [comment]
@renhao-0518 if you look at the last example I gave, I used `&&` i.e. if neither `[ci skip]` AND `[skip ci]` are in the message, it can continue.

Glad to hear it's sorted tho'

**Comment by renhao-0518** [comment]
@bigkevmcd Thanks, now everything is normal

**Comment by dibyom** [comment]
I'm going to close out this issue. Please re-open if you run into other issues.

/close
