### ISSUE TITLE
Allow to change default namespace tekton-pipelines.

### ISSUE THREAD

**Issue by leptonyu** [tektoncd/triggers#923]
https://github.com/tektoncd/triggers/blob/608bc75bfe6726d6db904f4b8fa018b64b76028a/pkg/interceptors/interceptors.go#L191

This code lead to following error, because it fix the namespace.

```json
  "level": "error",
  "ts": "2021-01-23T05:58:12.037Z",
  "logger": "eventlistener",
  "caller": "sink/sink.go:205",
  "msg": "Post \"http://tekton-triggers-core-interceptors.tekton-pipelines.svc/github\": dial tcp: lookup tekton-triggers-core-interceptors.tekton-pipelines.svc on 10.96.0.10:53: no such host",
  "knative.dev/controller": "eventlistener",
  "/triggers-eventid": "npcqp",
  "/trigger": "github-listener",
  "logging.googleapis.com/labels": {},
  "logging.googleapis.com/sourceLocation": {
    "file": "github.com/tektoncd/triggers/pkg/sink/sink.go",
    "line": "205",
    "function": "github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger"
  },
  "stacktrace": "github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:205\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:125"
}
```

**Comment by savitaashture** [comment]
OpenShift install Triggers component under `openshift-pipelines` namespace.
As we hardcoded namespace to `tekton-pipelines` we will face above error.

I agree to have this feature

I would propose that instead of hard coding namespace to `tekton-pipelines` we should able to get namespace value where Triggers controllers are installed @dibyom wdyt ?

**Comment by dibyom** [comment]
hmm yeah this is a bug :(

We should probably be using the value of the SYSTEM_NAMESPACE env var, and not rely on the default system namespace.

**Comment by dibyom** [comment]
We need to propagate the namespace that Triggers is installed in. The SYSTEM_NAMESPACE env var in the EL Pod propagates the namespace that the EL is installed in.
