### ISSUE TITLE
Proposal: Use standard k8s labels

### ISSUE THREAD

**Issue by ipedrazas** [tektoncd/triggers#938]
### Feature request

It would be great if we could incorporate the use of standard/recommended k8s labels to identify applications/components resources (https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/). 
```
        app.kubernetes.io/version: "v0.11.2"
        app.kubernetes.io/part-of: tekton-triggers
```

Since `pipelines` has already adopted some (https://github.com/tektoncd/pipeline/issues/2497), it would be great to adopt the same set of labels for all the tekton projects. This change does not really affect how triggers work, but it would help greatly when managing resources and debugging different scenarios.

### Benefits
The benefits would be:

Normalized labelling across projects
More flexible lookup process
Easy to document/test/debug

**Comment by jmcshane** [comment]
@ipedrazas which labels are not present and on what component? The same PR you reference in pipelines also links a PR on triggers, #556. Is there a specific component that does not receive these labels?

**Comment by dibyom** [comment]
Like @jmcshane said, we already add the recommended labels to the controller/webhook deployment. I'm going to close this but feel free to re-open if there are any labels that we are missing.

/close
