### ISSUE TITLE
Use watches on Triggers rather than loading them on each request to the Event Listener

### ISSUE THREAD

**Issue by jmcshane** [tektoncd/triggers#944]
### Feature request

Right now, every single request to the event listener has to gather all the associated triggers from the target namespaces and hardcoded in the eventlistener by the sink. Each sink could instead create a watch on the target k8s Triggers and maintain a list outside of the main sink request/response loop. This can lower sink processing time because it would reduce the API calls required for each eventlistener request.

### Use case

I have an event listener where lots of events are sent to the sink loop (more are discarded than create pipelines). This creates lots of pressure on the K8s API, especially as we scale events to this central event listener.

**Comment by dibyom** [comment]
What version of triggers are you on? We already use listers to get the resources which internally uses a cache to reduce the number of calls to the API server: https://github.com/tektoncd/triggers/blob/master/pkg/sink/sink.go#L58-L63

**Comment by jmcshane** [comment]
Ah shit, I didn't understand the listers correctly, sorry @dibyom. I'll close this
