### ISSUE TITLE
Question: Event Listener logs showing lot of unknown events

### ISSUE THREAD

**Issue by abhinavkhanna-sf** [tektoncd/triggers#951]
I am seeing event listeners is logging lot of events at least 2-3 events every second.

Not sure what the source is. Its not causing any issues. They fail to trigger as they are missing required headers.

Its causing lot of noise while debugging actual issues.

any pointers on how to stop them? Thanks

```
{"level":"info","ts":"2021-02-09T00:01:48.146Z","logger":"eventlistener","caller":"sink/sink.go:211","msg":"interceptor stopped trigger processing: rpc error: code = FailedPrecondition desc = no X-Hub-Signature header set","knative.dev/controller":"eventlistener","/triggers-eventid":"r7t52","/trigger":"proj-listener","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"github.com/tektoncd/triggers/pkg/sink/sink.go","line":"211","function":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger"}}
```

My Setup

AWS EKS 1.18
AWS Load Balancer
Tekton Triggers: v0.11.2
ArgoCD managing whole instance

**Comment by bigkevmcd** [comment]
That's coming from a GitHub interceptor, it looks like you've got a GitHub interceptor receiving events that are _not_ coming from GitHub?

**Comment by abhinavkhanna-sf** [comment]
@bigkevmcd Is there a way to figure out what's the source? (I did place Source IP restrictions on my ALB so its not external traffic from internet.)

**Comment by dibyom** [comment]
do you have some kind of a health check configured perhaps?

**Comment by abhinavkhanna-sf** [comment]
Thanks that helped. It was AWS Load Balancer`s Target Node Group. It was set at 15 seconds. I was seeing multiple times per second because of number of nodes. Target Group sends request on all nodes to check the status

I am running the event listener service as NodePort.

@dibyom Is there a way healthz endpoint for event listener?

**Comment by bigkevmcd** [comment]
This does maybe indicate that we're missing a log entry for the received URL?

**Comment by dibyom** [comment]
@abhinavkhanna-sf Yeah I was going to suggest using /live

@bigkevmcd I think we log the request at DEBUG not info

**Comment by bigkevmcd** [comment]
I've added the start of some documentation on debugging eventlisteners, there's a bit on debugging TriggerBindings already, but I added notes on how to enable debug logging, and the caveats etc, and I noticed that the debug-level log was missing the path.
