### ISSUE TITLE
How to configure github checks?

### ISSUE THREAD

**Issue by GabrielLasso** [tektoncd/triggers#967]
I did configure the EventListener and the TriggerTemplate so that a new TaskRun is created for every commit in my repository.

However, I'd like the status of the run to appear in the checks (that yellow ball next to the commit).

Is that possible using Tekton? How to do that?

**Comment by dibyom** [comment]
You could use a finally task in your pipeline to set the status: https://hub.tekton.dev/tekton/task/github-set-status

Also, you might get a faster response for questions like these if you post on slack :)

**Comment by dibyom** [comment]
I'm going to close out this issue now. If you have more questions, feel free to ask to the Slack!
