### ISSUE TITLE
any plan to support gitea for the type of interceptors？

### ISSUE THREAD

**Issue by AndrewOYLK** [tektoncd/triggers#968]
### Feature request

Gitea is used by our company for private respository，so I hope trigger can support gitea

**Comment by dibyom** [comment]
Hi @AndrewOYLK  We are working on a mechanism to easily add your own interceptor (https://github.com/tektoncd/community/blob/main/teps/0026-interceptor-plugins.md) 

Not too familiar with Gitea but assuming it supports webhooks like other SCMs it should be fairly easy to write one for Gitea.

**Comment by jmcshane** [comment]
@AndrewOYLK reading https://docs.gitea.io/en-us/webhooks/, it appears that the gitea webhooks are the same format as github webhooks, even including the same signature verification features as the github implementation. Could you attempt to point your gitea server webhook to an eventlistener service and use the `github` interceptor type and see if that does the trick?

**Comment by AndrewOYLK** [comment]
@dibyom @jmcshane Sorry for my late response. Thanks a lot, I will try.
