### ISSUE TITLE
Failed replacing params from json event values

### ISSUE THREAD

**Issue by c0ldd** [tektoncd/triggers#980]
# Expected Behavior
EventListener should start TaskRun with param value from event body

# Actual Behavior
EventListener failed to replacing params:
```{"level":"error","ts":"2021-03-04T13:45:28.858Z","logger":"eventlistener","caller":"sink/sink.go:230","msg":"failed to ApplyEventValuesToParams: failed to replace JSONPath value for param body: $(body.value): value is not found","knative.dev/controller":"eventlistener","/triggers-eventid":"hcpz2","/trigger":"test-event-trigger","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"github.com/tektoncd/triggers/pkg/sink/sink.go","line":"230","function":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger"},"stacktrace":"github.com/tektoncd/triggers/pkg/sink.Sink.processTrigger\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:230\ngithub.com/tektoncd/triggers/pkg/sink.Sink.HandleEvent.func1\n\tgithub.com/tektoncd/triggers/pkg/sink/sink.go:125"}```

# Steps to Reproduce the Problem

[main_yml](https://gist.github.com/c0ldd/ed825ae33304027f0852fe37ce4f719b)
[rbac](https://gist.github.com/c0ldd/390efe68152b8b22db74e9556f0d2f95)
kubectl port-forward svc/el-test-event-listener 8080:8080
curl -d '{"body":{"value":"Test value"}}' -H "Content-Type: application/json" -X POST http://localhost:8080/

Am i missing something ?

# Additional Info
Client version: 0.15.0
Pipeline version: v0.21.0
Triggers version: v0.11.2
minikube version: v1.12.1

**Comment by dibyom** [comment]
Does it work with `curl -d '{"value":"Test value"}' -H "Content-Type: application/json" -X POST http://localhost:8080/` or alternatively changing your TriggerBinding to use `$(body.body.value)`? 

(The `body` key is implicitly added to refer to anything in the incoming request body. You could also do `header.Content-Type` for example)

**Comment by c0ldd** [comment]
Yep it's worked. So according to [doc](https://github.com/tektoncd/triggers/blob/release-v0.11.x/docs/triggerbindings.md) where example with "Keys with dots ." is example wrong ? It should be 
$(body.body.tekton\\.dev) -> "triggers"
to be workable ?
